### ISSUE TITLE
Replace jsonrpc-v2

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#1006]
**ACs**
- [ ] Investigate Parity's `jsonrpc_core` crate, which is transport-agnostic, and might be more ergonomic for our use case.
- [ ] If it seems like it won't be too much trouble, implement it, replacing `jsonrpc-v2` for #706 .

**Notes**
We've been having enough issues with `jsonrpc-v2` that we're thinking the best idea at this point is to try a different crate.

**Comment by amerameen** [comment]
@cryptoquick has suggested that our current setup is satisfactory for now.
