### ISSUE TITLE
Markets Integration Unit Testing

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#1029]
**Issue Summary**
Goal is verifying go-fil-markets integration, which uses the payment channel RPC methods. 2k-3k lines of payment channel unit tests will need to be ported over from Lotus to test this functionality. Fixes for failing tests are within scope.

**Acceptance Criteria**
- [ ] Ensure all payment channel unit tests on Lotus pass

**Comment by LesnyRumcajs** [comment]
Stale.
