### ISSUE TITLE
Manual RPC and CLI Smoke Test (USAGE.md)

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#1040]
AC
- [x] Manual smoke testing for all currently-implemented Forest CLI and RPC commands
- [x] Comparison to existing Lotus calls, and examples of how those work with Forest
- [x] USAGE.md
  - [x] Sections with example usage for each CLI command
    - Forest CLI with Forest node
    - Lotus CLI with Forest node
    - HTTP JSON-RPC with Forest node

See also: #1118

**Comment by cryptoquick** [comment]
Some notes / thoughts...

- Separate test suites for mainnet read-only tests (interop, validation)
- vs. read-write local dev net tests (mining, posting storage contracts, and other operations that contribute to the blockchain)

**Comment by cryptoquick** [comment]
This will expand on the work done on #1118

**Comment by connormullett** [comment]
Should this be in the form of a script? or more of a "health check" command

**Comment by cryptoquick** [comment]
A bash script is fine too
