### ISSUE TITLE
Fix Clippy Lint Ignore

### ISSUE THREAD

**Issue by ec2** [ChainSafe/forest#1065]
**Issue summary**

Currently we are disabling `clippy::upper_case_acronyms` in the CI and Makefile. This is because to fix these would require new crate releases on a bunch of different crates. So I've decided to just ignore those new linting rules and fix them the next time we need to release new crates. 

**Other information and links**

**Comment by cryptoquick** [comment]
I'm not sure we'll ever get to this, or if we'll find a reason to get to this. I'd be in favor of closing the issue.

**Comment by q9f** [comment]
fixed in #1236 #1237 #1238 and #1239
