### ISSUE TITLE
RPC Client Library

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#1070]
Blocked by #1211 

Publish a crate which can be utilized by anything that needs to implement the RPC Method Interface, including a transport-specific RPC client, especially with regards to the CLI client, but also for external consumption for other Rust Filecoin projects with a minimal number of dependencies.

**Comment by ec2** [comment]
Release `rpc-client` next sprint.

**Comment by cryptoquick** [comment]
I think we should release both `rpc_client` and `rpc_api`. Probably with the `filecoin_` prefix.

**Comment by lemmih** [comment]
`rpc-api` and `rpc-client` are ready. Closing this issue.
