### ISSUE TITLE
RPC Encrypted Keystore Unlock

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#1083]
**Issue summary**

Currently we block on CLI input for passphrase. We need to concurrently spawn a mini HTTP JSON-RPC server so the node can be unlocked via an HTTP request (either via Curl or submitted via the Forest CLI when invoked by a script, especially remotely)

**ACs**

- [ ] `Forest.EncUnlock` can be called to bypass CLI password entry when the daemon is started with the `encrypt_keystore` option enabled.
- [ ] Forest CLI has a command, `forest auth unlock` that allows either a command line argument, or if none is passed, invokes `read_password`. This will allow for scripted and remote unlock use-cases.
- [ ] Detects whether HTTPS protocol has been used to call this endpoint via the [XFP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto), fails if the connection is unencrypted.
- [ ] A separate port must be used, for security purposes.

**Other information and links**

- This can either be solved by starting a miniature, temporary, single method tide server and jsonrpc_v2 combination that's separate from the full-fledged RPC server, or, the entire RPC server can be started concurrently, with the assumption that no other RPC method will be called without the keystore being unlocked. This mini RPC server will have a single `Forest.EncUnlock` method, and stop it once the keystore is decrypted. It will also need to use a separate port than the regular RPC API, for security purposes.

**Comment by cryptoquick** [comment]
Honestly, I'm not 100% sure how this can be implemented securely.

**Comment by cryptoquick** [comment]
Wait, no, I thought of an idea. The mini-server could have a separate port, which can easily be firewalled.

**Comment by lemmih** [comment]
We'll use a different architecture: https://github.com/ChainSafe/forest/discussions/2274
