### ISSUE TITLE
`lotus wallet list` not working

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#1085]
**Describe the bug**
No response from JSON-RPC API when attempting to list wallets via lotus. No errors in forest log.

**To Reproduce**
1. `make install`
1. `forest` (be sure to copy the `Admin token` printed after the keystore is initialized
1. Replace the token in this command, and create a new wallet like so: `FULLNODE_API_INFO="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.6stmBuYIVFCGPMnhFI7U1hNXcjPKUZTF4cTBQazD4gM:/ip4/127.0.0.1/tcp/1234/http" lotus wallet new`
1. Attempt to list wallets via: `FULLNODE_API_INFO="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXX0.6stmBuYIVFCGPMnhFI7U1hNXcjPKUZTF4cTBQazD4gM:/ip4/127.0.0.1/tcp/1234/http" lotus wallet list`
1. Wait roughly 30 seconds, lotus hangs, and then exits.

**Expected behaviour**
Expected to see a wallet list.

**Environment (please complete the following information):**
 - OS: I run Arch, btw
 - Rust version: 1.53.0-x86_64-unknown-linux-gnu
 - Branch/commit: main, `3771568cc9f1a9ecab8089aef8a7c9258056ea63`

Screenshot:
![Screenshot from 2021-07-27 18-21-17](https://user-images.githubusercontent.com/285690/127243992-0aa0f1c1-bb33-4193-badc-394ee68e98db.png)

**Comment by lemmih** [comment]
Lotus compatibility is no longer guaranteed. Closing.
