### ISSUE TITLE
Display clippy check comments on PR files

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/forest#1088]
**Issue summary**

Hi Team! 

Bother to ask if you are interested in displaying `clippy-check` comments on PR files through CircleCI, we just moved forward to CircleCI from Github Actions following the `config.yml` of the forest project and realized we lost the the `clippy-check` comments `actions-rs/clippy-check` provides...

Please ping me if anybody has interests in this feature!

**Other information and links**

ChainSafe/PINT#49

**Comment by cryptoquick** [comment]
We'd like more information on what's needed to make this happen. Is this something that works with CircleCI, and is this easy to do, or will we have to switch to GitHub Actions?
