### ISSUE TITLE
Create Prometheus Server & Grafana Stack

### ISSUE THREAD

**Issue by olibearo** [ChainSafe/forest#1096]
**Task summary**

Create a container stack that manages a Prometheus server and serves the Grafana webapp

**Specification reference**

The Prometheus server should collect metrics from the Forest process. The Grafana webapp should preload dashboards and come with documentation to update the dashboards.

**Other information and links**

**Comment by mxinden** [comment]
In case this is of some help, I wrote a docker-compose file in the past, starting multiple Substrate instances, Prometheus and Grafana (with preloaded dashboards):

https://github.com/paritytech/substrate/blob/master/.maintain/local-docker-test-network/docker-compose.yml
