### ISSUE TITLE
add a `rust-toolchain` file to set a specific version

### ISSUE THREAD

**Issue by dtynn** [ChainSafe/forest#1131]
**Issue summary**
for now, codes in main branch can not be compiled with stable (1.51.0, in my case) toolchain.
it could be better to add a `rust-toolchain` file to a specific  version.
[Managing versions](https://doc.rust-lang.org/edition-guide/rust-2018/rustup-for-managing-rust-versions.html#managing-versions)

**Other information and links**
this may also avoid issues caused by differences in the compilers, 
[A Polkadot Postmortem - 24.05.2021](https://polkadot.network/a-polkadot-postmortem-24-05-2021/)

**Comment by cryptoquick** [comment]
Yes, stable 1.52.1 is now a hard requirement. Good suggestion, I can take care of this today.

**Comment by dtynn** [comment]
> Yes, stable 1.52.1 is now a hard requirement. Good suggestion, I can take care of this today.

`echo "1.52.1" > rust-toolchain`

ok, 1.52.1 did work.
thanks
