### ISSUE TITLE
Pretty CLI Errors

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#1159]
**Task summary**

We currently print HTTP error codes to the command line. It has been brought to my attention that not everyone has those memorized, I guess.

**Specification reference**

When the following codes are found, print the associated error string for them:

- [x] 400 Bad Request
- [x] 403 Forbidden
- [x] 404 Not Found

**Other information and links**

This information is usually sent in the HTTP response body.

**Comment by LesnyRumcajs** [comment]
It can be reproduced by running `forest` in one tab, e.g. `forest --target-peer-count 50 --encrypt-keystore false` and running an JSON RPC command like:
```
❯ forest wallet list
 2022-07-05T06:38:50.906Z ERROR forest::cli > JSON RPC Error: Code: 403 Message: Error code from HTTP Response: 403
``` 
We expect it to be something along the lines of
```
❯ forest wallet list
 2022-07-05T06:38:50.906Z ERROR forest::cli > JSON RPC Error: Code: 403 (Forbidden) Message: Error code from HTTP Response: 403
```

**Comment by lemmih** [comment]
@connormullett Maybe you could take a look at this issue?
