### ISSUE TITLE
Implement Chain Selection

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/forest#118]
Chain Selection is an integral part of EC but needs to be accessible within the `ChainManager` and have the heaviest tipset value available in the `Store` struct. As per the spec chain selection definition can be found [here](https://filecoin-project.github.io/specs/#algorithms__expected_consensus__chain_selection) and may look like the following:

```
// ChainSelector chooses the heaviest between chains.
type ChainSelector interface {
	// IsHeavier returns true if tipset a is heavier than tipset b and false if
	// tipset b is heavier than tipset a.
	IsHeavier(ctx context.Context, a, b block.TipSet, aStateID, bStateID cid.Cid) (bool, error)
	// Weight returns the weight of a tipset after the upgrade to version 1
	Weight(ctx context.Context, ts block.TipSet, stRoot cid.Cid) (uint64, error)
}
```

Where the algorithm for determining the **weight** can be found:
- [Spec Definition ](https://filecoin-project.github.io/specs/#chain-weighting)
- [Go-Filecoin Weight Function](https://github.com/filecoin-project/go-filecoin/blob/master/internal/pkg/consensus/chain_selector.go#L49)
- [Lotus Weight Function](https://github.com/filecoin-project/lotus/blob/master/chain/store/weight.go#L16)

Where the algorithm for determining the **IsHeavier** can be found:
- [Spec Definition ](https://filecoin-project.github.io/specs/#chain-weighting)
- [Go-Filecoin IsHeavier Function](https://github.com/filecoin-project/go-filecoin/blob/master/internal/pkg/consensus/chain_selector.go#L97)
- [Lotus Heaviest Function](https://github.com/filecoin-project/lotus/blob/master/chain/sync_manager.go#L174)

**Tasks Required for completion:**
- [ ] `ChainSelection` trait
- [ ] `Weight` fn
- [ ] `Heaviest` fn

**Comment by austinabell** [comment]
This issue is pretty out of date, probably just needs to implement the templated function here: 
https://github.com/ChainSafe/forest/blob/8f8fd1e3242bc083029016bf4453269594a7a1c7/blockchain/chain/src/store/chain_store.rs#L64
