### ISSUE TITLE
Forest CLI asks for passphrase when keystore encryption is disabled

### ISSUE THREAD

**Issue by connormullett** [ChainSafe/forest#1195]
**Describe the bug**

When keystore encryption is disabled, the CLI will still ask for the keystore passphrase and panics afterward

**To Reproduce**
1. Build Forest for release with `cargo build --release`
2. Disable keystore encryption in `config.toml` (encrypt_keystore = false) 
3. Run forest as a node `target/release/forest -c ../path/to/config.toml`
4. Issue a command through the CLI ie chain head, auth api-info, wallet import etc

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```$FULLNODE_API_INFO="<token>:/ip4/127.0.0.1/tcp/1235/http" target/release/forest chain head
Enter the keystore passphrase: 

The keystore cannot be found from defaults, the environment, or provided arguments
 2021-07-16T17:49:25.290Z WARN  key_management::keystore > Encrypted keystore does not exist, initializing new keystore
thread 'main' panicked at 'Keystore initialized with a JWT private key: KeyInfo', forest/src/subcommand.rs:50:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```
</details> 

**Expected Behavior**
When encryption is disabled, the forest CLI should not require a passphrase

**Environment (please complete the following information):**
 - OS: Arch linux
 - Rust version: 1.53.0
 - Branch: main

**Comment by connormullett** [comment]
User issue. Resolved by including `--config <config file path>` when invoking CLI

**Comment by cryptoquick** [comment]
UX confusion like this puts a little more urgency on this issue:
https://github.com/ChainSafe/forest/issues/1191

We've got plenty of work to do for now, of course, but maybe in a month or two if nobody else picks it up, we can take it on.
