### ISSUE TITLE
Fix API Implementation Types Mismatches

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#1207]
**Task summary**

In the [Forest API Implementation report](https://github.com/ChainSafe/forest/blob/main/API_IMPLEMENTATION.md), there's a couple types that could benefit from the newtype pattern, and others are just encoded differently. Ideally all params and result types match Lotus's, such that the API report lists no more mismatches.

Also, ideally, we get this taken care of before publishing the RPC client library crate in #1070.

**Specification reference**

- https://github.com/ChainSafe/forest/blob/main/API_IMPLEMENTATION.md

**Other information and links**

**Comment by LesnyRumcajs** [comment]
This report is no longer present and will be replaced by a generated spec.
