### ISSUE TITLE
RPC Client Smoke Test

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#1216]
**Task summary**

Make a program that, when run, makes a number of calls to Lotus via the RPC Client. This will validate proper deserialization, decoding, param types, etc.

This can't be added as a unit test or tested in any of the ways we currently test, since it requires a running Lotus node.

Ideally this can also be run against a Forest node and work the same. Failing tests should be reported, but they shouldn't fully abort execution.

**Specification reference**

- `node/rpc-client-tests`
- Uses only `node/rcp-client` methods
- Tests kept in separate functions, and called in main fn
- Reports passing and failing tests
- Tests can test multiple scenarios, and there should be at least one test per method ([66 methods as of filing](https://github.com/ChainSafe/forest/blob/main/API_IMPLEMENTATION.md))

**Other information and links**

We may want to do this before we start on #1208, so that work can also include testing the additional RPC methods.

If desired, this can be down-scoped to maybe just Wallet methods (since we have a decent number of them and it tests straightforward functionality) for the first stab at this issue, and issues and epics filed for the other methods. It'll help just to have this so we have a place where tests can be added as needed.

**Comment by lemmih** [comment]
Done.
