### ISSUE TITLE
Forest stopped working with Lotus RPC

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#1222]
**Describe the bug**
When using the Forest CLI with the Lotus daemon, not only does it not authenticate correctly, it also doesn't parse unauthenticated responses properly.

**To Reproduce**

```
FULLNODE_API_INFO=/ip4/127.0.0.1/tcp/1234/http forest sync status
```

**Log output**

```
2021-08-30T14:18:07.816Z ERROR rpc_client > Parse Error: Response from RPC endpoint could not be parsed. Error was: EOF while parsing a value at line 1 column 0
JSON RPC Error: Code: 0 Message: Parse Error: Response from RPC endpoint could not be parsed. Error was: EOF while parsing a value at line 1 column 0
```

**Expected behaviour**

Expected the Forest CLI to print the Lotus sync status

**Screenshots**

N/A

**Environment (please complete the following information):**
 - OS: Arch
 - Rust version(e.g. `rustc --version`) rustc 1.53.0 (53cb7b09b 2021-06-17)
 - Branch/commit `hunter/fix-lotus-http-rpc-json`

**Other information and links**

This issue should be prioritized in order to properly test current PRs in-flight.

**Comment by connormullett** [comment]
This is definitely a serde issue. Haven't found the culprit yet. Going to diff out both of the outputs with curl calls. Most likely is an issue with capitalization.

**Comment by cryptoquick** [comment]
> This is definitely a serde issue. Haven't found the culprit yet. Going to diff out both of the outputs with curl calls. Most likely is an issue with capitalization.

🤗❤️☺️
