### ISSUE TITLE
Remove LGTM (Go)

### ISSUE THREAD

**Issue by q9f** [ChainSafe/forest#1232]
For some reason we have LGTM configured to check our Golang code quality, but it cannot find any Go files (no shit!) and there is no Rust support in LGTM. Let's remove that.

**Comment by ec2** [comment]
Yeah, that check kinda appeared randomly out of no where one day. I'll try to find out how I can remove it.

**Comment by ansermino** [comment]
It was given access to all of ChainSafe's repos. I have removed those permissions and added specific repos. Hopefully that will remove it from here 🤞

**Comment by q9f** [comment]
Yeah it's gone, thanks!
