### ISSUE TITLE
Forest dies after an extended period of syncing from snapshot

### ISSUE THREAD

**Issue by connormullett** [ChainSafe/forest#1254]
**Describe the bug**

After importing from a snapshot to test the NV 10 state migration, the node died after 2 hours of syncing. 

**To Reproduce**
1. Grab a snapshot from https://fil-chain-snapshots-fallback.s3.us-west-2.amazonaws.com/mainnet/minimal_finality_stateroots_549821_2021-03-03_20-00-00.car
2. `target/release/forest -c ../config.toml --import-snapshot ../snapshots/nv_10_migration_state.car`
3. node should die after an extended period of time

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 
No logs have been captured from this failure

**Expected behaviour**

The node syncs successfully

**Screenshots**

![image](https://user-images.githubusercontent.com/41083414/140827562-8bba1107-5b72-461d-bb84-e4c0e464b119.png)

**Environment (please complete the following information):**
 - OS: Arch
 - Rust version(e.g. `rustc --version`) 1.53.0
 - Branch/commit `connor/nv10-state-migration`

**Other information and links**

**Comment by lemmih** [comment]
This appears to have been resolved.
