### ISSUE TITLE
Document setting up metrics and monitoring 

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#1263]
- Add to Forest Documentation 
- Instructions for running metrics server and monitoring (prometheus, grafana)

**Comment by lemmih** [comment]
@samuelarogbonlo Could you write concise instructions for querying metrics and setting up grafana?

**Comment by LesnyRumcajs** [comment]
@lemmih I believe the instructions [here](https://github.com/ChainSafe/forest/tree/main/monitoring) are quite concise. It might make sense to close this issue in favour of https://github.com/ChainSafe/forest-docs-v2/issues/16. What do you think @lemmih ?

**Comment by lemmih** [comment]
Great. Closing.
