### ISSUE TITLE
F1: Multisig does not properly handle internal runtime errors when executing transactions

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#1265]
Description of the issue [HERE]( https://hackmd.io/eThp9-pyR0WfLJjBynFntA?view#F1-Multisig-does-not-properly-handle-internal-runtime-errors-when-executing-transactions)

**Comment by LesnyRumcajs** [comment]
@elmattic should this issue be closed?

**Comment by elmattic** [comment]
Yes!
