### ISSUE TITLE
F18: Missing validation step in ExpirationSet::add

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#1284]
Description of the issue [HERE](https://hackmd.io/eThp9-pyR0WfLJjBynFntA?view#F18-Missing-validation-step-in-ExpirationSetadd)

**Comment by RobQuistNL** [comment]
is there a way for us to view these issues?

**Comment by noot** [comment]
@RobQuistNL hey, the doc is currently private as it's part of an ongoing audit, but we'll likely publish it when it's complete.
