### ISSUE TITLE
[Tracking] Release 0.2.0-alpha

### ISSUE THREAD

**Issue by q9f** [ChainSafe/forest#1351]
Meta tracking ticket towards a second alpha release for `forest`.

Non-technical issues
- [x] Publish documentation
- [ ] Update Changelog, known issues #1246
- [ ] Create release pipeline on a tag to provide binaries (TBD?)

Technical issues
- _TBD, feel free to add release blockers_

**Comment by q9f** [comment]
#1343, #1342, and #1348

**Comment by noot** [comment]
@q9f all needed PRs are now merged :)

**Comment by q9f** [comment]
Ok, I will do the release next week if you don't mind. I want to check some things first.
