### ISSUE TITLE
Implement Block CBOR Encoding

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/forest#141]
We need this to implement CIDs correctly, this should be checked against Lotus for consistency.

Examples:
- [Lotus Serialize](https://github.com/filecoin-project/lotus/blob/master/chain/types/blockheader.go#L97)
- [Lotus Decode](https://github.com/filecoin-project/lotus/blob/master/chain/types/blockheader.go#L88)

**Comment by austinabell** [comment]
Block does not need to be cbor encoded. Only header and it maps the messages through the message root in the header
