### ISSUE TITLE
Add network specific databases

### ISSUE THREAD

**Issue by connormullett** [ChainSafe/forest#1418]
**Issue summary**

Forest currently has one database and is adding support for calibnet at time of this issue's creation. As a quality of life feature, Forest will need to be able to have a database for each network available. Currently users/devs have to delete the database when switching networks, or changing the data_dir in config.toml. Being able to use our network features ( #[cfg(feature = "calibnet")]), we can automatically pick a database to use without having to delete the others.

**Task summary**

- [ ] use feature propogation to create and manage separate db paths based on network that was built

**Acceptance Criteria**

- [ ] when using forest, users should be able to switch freely between mainnet and calibnet without having to modify the config.toml or deleting their database and be able to start up where the nodes left on, on that network

**Other information and links**

**Comment by q9f** [comment]
Use https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

something like

```rust
"{}/{}/{}",
env!("XDG_DATA_HOME"),
CLIENT,
NETWORK
```
