### ISSUE TITLE
Enable clippy for tests and non-default crate features

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1430]
**Issue summary**
# Unleash full power of Clippy!
Currently we don't lint our tests. 
https://github.com/ChainSafe/forest/blob/f7141b4a0ea9105c3b6d8cdf83bef92d608ffeba/Makefile#L59

Not sure if the project deals with any non-default features but it won't hurt to add the check. The task here is to modify `lint` target in `Makefile` to `cargo clippy --all-targets --all-features -- -D warnings` (as in https://github.com/rust-lang/rust-clippy/blob/master/README.md#travis-ci). Then deal with all the issues (there are currently ~20 of them, with nice explanations).

**Comment by q9f** [comment]
I wish we could rebuild this repository from the ground up by having all checks in place before actually committing code.
