### ISSUE TITLE
Handle execute_message error without panic

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1435]
**Issue summary**

This piece of code (on a PR branch, not yet merged to `main` when writing down the issue, make sure it's not obsolete before digging into it):
https://github.com/ChainSafe/forest/blob/63d37e6b7f5e629252da5667c84926d3f9441756/vm/interpreter/src/vm.rs#L694-L697

panics on error. Instead, we need to convert the underlying error from `execute_message` into a relevant `ActorError`. Some digging into the Filecoin specification may be needed to implement it correctly.

**Comment by lemmih** [comment]
Done in `lemmih/fvm` branch.
