### ISSUE TITLE
Create a `actor_types` seperate crate

### ISSUE THREAD

**Issue by rllola** [ChainSafe/forest#1446]
**Task summary**
Create a separate `actor_types` crate that could be use in WASM. The `actor` crate depends on some library that can't be compiled into WASM like `memmap`. It doesn't sound practical to modify all the library to avoid using this lib and might not be possible in the end so creating a crate looks like our best option.

A crate for each actor version would be required.

**Other information and links**

See https://github.com/Zondax/filecoin-signing-tools/pull/474

**Comment by anorth** [comment]
Do you mean something similar to https://github.com/filecoin-project/go-state-types, or do you mean something that has the full state schema for the actors?

**Comment by rllola** [comment]
> Do you mean something similar to https://github.com/filecoin-project/go-state-types, or do you mean something that has the full state schema for the actors?

I need the actor types. I am not quite sure I understand what you mean by the full state schema.

The goal is to use it to serialize/deserialize params. The temporary solution was to copy those types files in a `extras` crate (see https://github.com/Zondax/filecoin-signing-tools/tree/master/extras) but I want to get ride of it to avoid the redundancy. I hope that makes sense.

**Comment by anorth** [comment]
I'm not sure what you mean by types :-). It sounds like you're specifically looking for the method parameter and response types, but not the types of the actors' state.

Sorry I'm not well informed here, but are you planning to use the filecoin-project/builtin-actors repo? That's going to have to have wasm-compatible versions of this.

**Comment by rllola** [comment]
I am indeed looking for the parameters types. By "types" I was referring to the `types.rs` file (https://github.com/ChainSafe/forest/blob/main/vm/actor/src/builtin/multisig/types.rs) that define what the parameters and return object should look like. Sorry for the lack of context.

Like @anorth pointed out https://github.com/filecoin-project/builtin-actors should be helpful so I am closing this issue.
