### ISSUE TITLE
Reduce VM allocations

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1447]
**Issue summary**
In the current code (https://github.com/ChainSafe/forest/blob/main/blockchain/state_manager/src/lib.rs) we seem to spawn new instances of https://github.com/ChainSafe/forest/blob/main/vm/interpreter/src/vm.rs in several places (potentially even on every message). This is wasteful though without a proper benchmark it's hard to say what's the performance hit here.

**Task summary**
If possible, cache the VM instance and re-use it. Perhaps look for some inspiration in [ref-fvm](https://github.com/filecoin-project/ref-fvm/blob/lemmih/forest/fvm/src/executor/default.rs).

**Other information and links**

**Comment by lemmih** [comment]
Fixed in `lemmih/fvm` branch.
