### ISSUE TITLE
Failing `main` build notification on Slack

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1450]
**Issue summary**
So far if an issue appears on the `main` branch we don't get notified - basically, someone needs to look at the repo main page to notice it. This possibly makes the `main` branch red for an extended period of time. 

Example:
1. PR opened on Monday, all checks passed.
2. On Tuesday there's a toolchain update that makes `clippy` angry about Forest's code.
3. On Wednesday the PR gets reviewed and merged (because it was green). The checks don't pass anymore, we get a red `Build failed` badge and everyone look at Forest with contempt. 
4. Next Monday someone opens a PR and has to fix random linter issues or someone notices it and fixes it sometime after.

Surely we can do better!

**Task summary**
The idea is to make a Slack notification on failed `main` build - this way everyone gets immediately and the issue can be resolved as soon as possible. 

We could use [this](https://github.com/marketplace/actions/slack-notify) or something similar. The only thing we would need is a generated slack webhook token which we would put in repo secrets.

**Acceptance Criteria**
Our `filecoin-notif` channel gets a notification on `main` build fiasco.

**Other information and links**

**Comment by lemmih** [comment]
@LesnyRumcajs This is much less of an issue now that we require PRs to be up-to-date before merging. You okay with closing this issue?

**Comment by LesnyRumcajs** [comment]
I'm okay with that. Anyway, it was not picked up for a year, so it doesn't seem like a real pain.
