### ISSUE TITLE
Reduce Forest 🌲 Binary Size 

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#1453]
Download required files on demand:
- Genesis Files 
- WASM for the actors

Tasks:
- [ ] Store calibnet genesis file in S3.
- [ ] Store mainnet genesis file in S3.
- [ ] ~Store actors v6 bundle file in S3~. Moved to separate issue.
- [ ] Add feature flag for inlining calibnet genesis file in forest binary.
- [ ] Add feature flag for inlining mainnet genesis file in forest binary.

**Comment by lemmih** [comment]
The size of the forest execution has gone down from roughly 100MB to 60MB on my machine. There's still room for improvement.

**Comment by lemmih** [comment]
The size of Forest has been reduced to 35MB. I think this is good enough for now as there's little low hanging fruit left.
