### ISSUE TITLE
Use a configuration file for RockDB options.

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1473]
**Issue summary**

The performance of Forest depends primarily on RocksDB. Tuning the parameters of RocksDB can affect throughput by several orders of magnitude but they are highly system dependent. We should find a good set of defaults for our use-case (point-based lookups, few deletes, bulk writes at predictable times) and save them in an options file such that they can be tuned for each installation.

**Other information and links**

**Comment by LesnyRumcajs** [comment]
[RocksDB tuning guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide) for reference

**Comment by lemmih** [comment]
Especially this section: https://github.com/facebook/rocksdb/wiki/RocksDB-Options-File

**Comment by LesnyRumcajs** [comment]
@lemmih Unfortunately I don't think we can use this. RocksDB Rust wrapper is using the C API which lacks this. See [here](https://github.com/rust-rocksdb/rust-rocksdb/issues/568). Seems we'll need to implement it manually.

**Comment by lemmih** [comment]
Sigh, that's a bummer.
