### ISSUE TITLE
Remove duplicates types in forest.

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1492]
**Issue summary**

 - These types were copied to `fvm_shared` and should be removed from forest:
   - [x] encoding/src/bytes.rs: BytesDe
   - [x] encoding/src/bytes.rs: Byte32De
   - [x] encoding/src/bytes.rs: BytesSer
   - [x] types/src/sector/mod.rs: SectorSize
   - [x] types/src/sector/mod.rs: SectorID
   - [x] types/src/sector/registered_proof.rs: RegisteredPoStProof
   - [x] types/src/sector/registered_proof.rs: RegisteredSealProof
   - [x] types/src/sector/registered_proof.rs: RegisteredAggregateProof
   - [x] types/src/sector/post.rs: SectorInfo
   - [x] types/src/sector/post.rs: PoStProof
   - [x] types/src/sector/post.rs: WinningPoStVerifyInfo
   - [x] types/src/sector/post.rs: WinningPoStVerifyInfo
   - [x] types/src/sector/post.rs: OnChainWindowPoStVerifyInfo

**Other information and links**

**Comment by LesnyRumcajs** [comment]
There are some spaghetti dependencies that need to be taken care of first, need to get rid of `Forest`'s HAMT and AMT in favour of FVM ones.
