### ISSUE TITLE
Use default logging filters even if RUST_LOG is set.

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1504]
**Issue summary**

Forest has a set of default logging filters. These filters are quite sensible but they're only used when the `RUST_LOG` environment variable is not set. Setting `RUST_LOG` to `chain_sync=debug` doesn't just change the logging setting for the `chain_sync` component, it unfortunately also clears all the default filters.

Forest should be changed to always start with the default set of filters and then allow `RUST_LOG` to augment them.

**Other information and links**

The logging filters are built in `forest/src/logger/mod.rs`.

**Comment by elmattic** [comment]
Btw, `gossamer` is using its config file to drive components log configuration:

https://chainsafe.github.io/gossamer/usage/configuration/#configuration

Could be nice to have too.
