### ISSUE TITLE
Add `--color=never|always|auto` flag.

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1512]
**Issue summary**

- [ ] Add `--color=never|always|auto` flag.
- [ ] Resolve `auto` to enabled if stdout is a tty and `NO_COLOR` hasn't been set (see https://no-color.org/)
- [ ] Update logger to follow the color preference.
- [ ] (Feel free to create a separate issue for this) Update progress bars to use newlines instead of carry returns if stdout is not a tty.

**Other information and links**

**Comment by nlok5923** [comment]
@lemmih i would like to work on this issue can you please assign this to me.

**Comment by nlok5923** [comment]
@lemmih i am quite new to this repo so could you please point out some resources for me to learn and make contribution. Also would appreciate if you could link some previous PRs which does similar.
