### ISSUE TITLE
Use Config File to Drive Components Log Configuration

### ISSUE THREAD

**Issue by jdjaustin** [ChainSafe/forest#1520]
**Issue summary**
Originally suggested by @elmattic in https://github.com/ChainSafe/forest/issues/1504#issuecomment-1081788726 to allow Forest to read logging configuration from file as opposed to only CLI parameters (similar to Gossamer implementation). Creating this issue to decide if this is something the team wants to implement; team to determine design/approach if approved.

**Comment by q9f** [comment]
From [Parity Ethereum](https://github.com/openethereum/parity-ethereum):

```
    -l, --logging=[LOGGING]
        Specify the general logging level (error, warn, info, debug or trace). It can also be set for a specific module,
        example: '-l sync=debug,rpc=trace'

    --log-file=[FILENAME]
        Specify a filename into which logging should be appended.
```

Something like this is pretty smart and highly configurable, really helpful for debugging only the component you are working on.

**Comment by elmattic** [comment]
My comment was more like indicative of what have done other node implementations @ChainSafe. What's important here would be more to have the feature described by @lemmih.
It's something that would be useful for us first (devs of forest) so UI is of less importance.
