### ISSUE TITLE
TPM communications

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#1529]
Maintains the regular meeting and communication structure between Protocol Labs, Filecoin Foundation and ChainSafe.

- [x] Filecoin Core Dev Calls

- [x] Engineering syncs between PL, FF and Forest team 

- [x] BD, TPM syncs between PL, FF and Forest team team

**Comment by q9f** [comment]
Not sure this adds any value being public.

**Comment by jdjaustin** [comment]
https://github.com/ChainSafe/forest/wiki/Communications
