### ISSUE TITLE
Running config dump subcommand on a new machine fails

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#1532]
**Describe the bug**

Running `config dump` subcommand on a new machine fails (where `.forest` directory does not exist yet).

**To Reproduce**

`forest$ ./target/debug/forest config dump`

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```
 2022-04-07T10:35:53.812Z WARN  forest::cli > No configurations found, using defaults.
Enter the keystore passphrase: 

The keystore cannot be found from defaults, the environment, or provided arguments
 2022-04-07T10:35:57.145Z WARN  key_management::keystore > Encrypted keystore does not exist, initializing new keystore
thread 'main' panicked at 'Keystore initialized with a JWT private key: KeyInfo', forest/src/subcommand.rs:50:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```
</details> 

**Expected behaviour**

We should be always able to print the default configuration.

**Comment by LesnyRumcajs** [comment]
@elmattic Not sure if the root cause is not the one that should be taken care of instead, i.e. getting rid of key management. At least that's what @q9f suggested at one point, maybe he could elaborate?

**Comment by q9f** [comment]
Ok, there are multiple issues here:

1. `.forest` does violate the `$XDG_DATA_HOME`, we should properly implement this: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
2. if not existing, as I suggested, we should use defaults AND initialize `$XDG_DATA_HOME/forest` and/or `$XDG_CONFIG_HOME/forest` with a default, persistent configuration that the user can later amend or modify as they like
3. we should completely remove account management unless this is required for running a node (I hope it's not); account management should never be part of a blockchain node for security reasons. entering a password during startup is even worse as we potentially keep it unencrypted in memory for some reasons. we should either remove accounts or put them in an external binary, e.g., `forest-key`.
