### ISSUE TITLE
Benchmark ChainSync process against other clients

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#1578]
**Issue summary**

As we work on making Forest sync again on mainnet for the nv16 upgrade, we need a benchmark we can run to track how do the client perform regarding to the other Filecoin implementations (so mainly Lotus and Venus).

This could help us deciding what is needed to improve and what are the current strenghts of Forest.

A good to start would be to measure a few metrics during syncing process.

- Current Epoch / Time of syncing
- Disk Usage / Current Epoch
- Memory Usage / Time of syncing

**Other information and links**

**Comment by lemmih** [comment]
This is being worked on here: https://github.com/ChainSafe/forest-iac/issues/92

**Comment by LesnyRumcajs** [comment]
@lemmih do we still want to do this?

**Comment by lemmih** [comment]
Nah, let's close this.
