### ISSUE TITLE
Implement Basic Storage Power Actor

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/forest#161]
A basic storage power actor framework has already been implemented however the defined task below provides additional details of what is required. 

**Storage Power Actor Definition:**
- https://filecoin-project.github.io/specs/#storagepoweractor-interface

**Lotus implementation:**
- https://github.com/filecoin-project/lotus/blob/master/chain/actors/actor_storagepower.go

**Data structures required:**
- [ ] `StoragePowerActorState`
- [ ] `CreateStorageMinerParams`
- [ ] `PowerTableHAMT`
- [ ] `MinerEventsHAMT`

**Methods required defined via spec:**
- `_slashPledgeCollateral`
- `_minerNominalPowerMeetsConsensusMinimum`
- `_selectMinersToSurprise`
- `_addClaimedPowerForSector` 
- `_deductClaimedPowerForSectorAssert`
- `_updatePowerEntriesFromClaimedPower`
- `_getCurrPledgeForMiner`
- `_getPowerTotalForMiner`
- `_getPledgeSlashForConsensusFault`
- `_setClaimedPowerEntryInternal`
- `_setNominalPowerEntryInternal`
- `_setPowerEntryInternal`

**Lotus methods defined:**
- https://github.com/filecoin-project/lotus/blob/master/chain/actors/actor_storagepower.go#L24

**Comment by austinabell** [comment]
https://github.com/filecoin-project/specs-actors/tree/master/actors/builtin/power
