### ISSUE TITLE
Storage Power Consensus

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/forest#164]
Storage Power Consensus (SPC) is a subsystem responsible for maintaining the state of the Filecoin system amongst nodes. 

**SPC is comprised of two subsystems:**

1. Access to the [Power Table](https://filecoin-project.github.io/specs/#systems__filecoin_blockchain__storage_power_consensus__storage_power_actor__power_table) for every subchain, accounting for individual storage miner power and total power on-chain
2. Access to [Expected Consensus](https://filecoin-project.github.io/specs/#algorithm) for individual storage miners
                  - Access to verifiable randomness Tickets
                  - Runs Secret Leader Election
                  - Running Chain Selection across subchains
                  - Identifying most recently finalized tipset

**Comment by austinabell** [comment]
This issue needs to be updated with the new interop changes, I'm assuming most logic is within actors, but if there is logic outside to complete, this should probably be more specifically defined.

thoughts @dutterbutter ?

**Comment by dutterbutter** [comment]
Yes definitely needs to be updated, and broken down into smaller tasks. I can look into it and update accordingly.

**Comment by dutterbutter** [comment]
Closing as this issue is outdated and will be likely specced out with storage miner
