### ISSUE TITLE
Early exit Forest if no snapshot is provided and the DB is empty

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1669]
**Issue summary**

Right now we can run forest on a clean instance without providing a snapshot. We can, but we all have the tribal knowledge that this will fail miserably. Others do not (yet).

It would be great to manage the expectations of people using Forest/first-time contributors and fail fast with a helpful message, e.g. `Need to bootstrap Forest with a snapshot on the first run` plus perhaps a link to the usual source of mainnet snapshots. This will certainly improve the user/contributor experience.

**Other information and links**

https://github.com/ChainSafe/forest/pull/1656

**Comment by connormullett** [comment]
A concern I have for this is how do we know if the DB is empty? Did they cancel the sync from snapshot halfway through have to restart their PC? We can check if the DB path exists but that doesn't mean Forest is synced
