### ISSUE TITLE
Use `libipld-json` to replace `ipld/src/json.rs`

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1700]
**Issue summary**

The [libipld-json](https://crates.io/crates/libipld-json) crate is nearly identical to our own JSON serializer. Replacing our code will require some refactoring, though. If the required changes are too large, update this issue with a summary.

**Other information and links**

**Comment by tyshko5** [comment]
`libipld` serialization is significantly different from what we are using now, namely:
1. bytes are not serialised using `multibase::encode` and are not wrapped into another ipld value
2. list is not wrapped
3. map is not wrapped
4. link is not wrapped

**Comment by lemmih** [comment]
Could you give examples of what those things mean? What kind of JSON do we accept vs. what kind of JSON does `libipld-json` accept?

**Comment by tyshko5** [comment]
> Could you give examples of what those things mean? What kind of JSON do we accept vs. what kind of JSON does `libipld-json` accept?

That means for example, that we would get   r#"{"/":{"/":"QmdfTbBqBPQ7VNxZEYEj14VmRuZBkqFbiwReogJgS1zR1n"}}"#;
and libipld r#"{"/": [some bytes]}"#;

**Comment by lemmih** [comment]
Are you saying we sometimes have an extra `"/"` key or are you saying the bytes are different?

**Comment by lemmih** [comment]
So, to summarize: We use multihash and `libipld-json` uses plain base64. That means we have an extra `m` in front of all the encoded byte values. For example:

| `forest_ipld` | `libipld-json` |
|-------|---------|
| `{ "bytes": { "/": { "bytes": "mVGhlIHF1aQ" } } }` | `{ "bytes": { "/": { "bytes": "VGhlIHF1aQ" } } }` |


Can you help me understand the three other issues you mentioned? Could you create tables that show the JSON format for both `forest_ipld` and `libipld-json`?

**Comment by tyshko5** [comment]
You are right, that is the only difference

**Comment by lemmih** [comment]
Great. And lotus is also using multihash. We should probably keep our custom JSON serializer, then. At least for now.

Could you open a PR where you add documentation that describes the differences between our serializer and the `libipld-json` serializer. The documentation should also state that Lotus is using multihash-base64 and that we're trying to do the same as them.

**Comment by tyshko5** [comment]
Ok
