### ISSUE TITLE
Untangle workaround for old compiler bug

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1728]
**Issue summary**

This compiler-bug workaround can possible be removed:
https://github.com/ChainSafe/forest/blob/a93d5d06fe2d6e1073c6e75437cba37b8325abb6/blockchain/blocks/src/lib.rs#L4-L5

https://github.com/ChainSafe/forest/blob/a93d5d06fe2d6e1073c6e75437cba37b8325abb6/blockchain/chain_sync/src/lib.rs#L16-L17

https://github.com/ChainSafe/forest/blob/a93d5d06fe2d6e1073c6e75437cba37b8325abb6/vm/message/src/lib.rs#L4-L5

https://github.com/ChainSafe/forest/blob/a93d5d06fe2d6e1073c6e75437cba37b8325abb6/vm/src/lib.rs#L4-L5

If it cannot, use this issue as a tracking issue and add a link in the code.

**Other information and links**

**Comment by tyshko5** [comment]
Don't really understand how https://github.com/ChainSafe/forest/blob/a93d5d06fe2d6e1073c6e75437cba37b8325abb6/vm/message/src/lib.rs#L4-L5 is connected with this workaround

**Comment by lemmih** [comment]
I think someone removed the `extern crate serde; ` line without also removing the comment. Just clearing the comment should be fine.
