### ISSUE TITLE
Resolve RUSTSEC-2020-0159

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#1761]
**Issue summary**

As mentioned in [here](https://github.com/ChainSafe/forest/issues/1247#issuecomment-1202334195), to resolve the final RUSTSEC exception soon, we need update `jsonwebtoken` crate and replace `tide` and `tide-websockets` dependencies with something that doesn't depend on `chrono`.

It's either that or we wait for `tide` dependencies to get updated, as it seems `chrono` is getting revived and fixed.

Acceptance criteria:
- [ ] `RUSTSEC-2020-0159` exception is removed.

**Other information and links**

**Comment by lemmih** [comment]
Done! Yay!
