### ISSUE TITLE
Clean up log messages that are sent before the logger is initialized

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#1769]
**Issue summary**

> I think we could have better cli messages, ie:
> ```
> $ ./target/release/forest --chain=calibnet chain export -r=2000 -s
>  2022-08-04T08:35:19.583Z WARN  forest::cli > No configurations found, using defaults.
> ```
> 
> In this case forest is warning us, but really it should not. I know that I am using the builtin `calibnet` configuration.
> Saying he founds nothing is odd from a user perspective at this point. And `default` could be as well understood as `mainnet` for a forest dev, which is misleading.
> 
> This config message could be much better.

EDIT:

The codebase has now changed and so the issue need to be re-purposed.

Some logs are called before the logger is initialized. We should always log messages once it is initalized.

One log warning is for example happening [here](
https://github.com/chainsafe/forest/blob/bb5647c69b29651689991e032e4eff1481d39686/forest/src/cli/mod.rs#L297). We need to check there are no other ones.

**Other information and links**

**Comment by elmattic** [comment]
What would the mission of the forest client? Interacting with the filecoin API?

The geth node somehow does that. You can attach to the node via `geth attach` then have some js console/repl:

https://geth.ethereum.org/docs/interface/javascript-console

**Comment by lemmih** [comment]
We already have a node (that connects to the filecoin network) and a client (that communicates with the forest node). They're just bundled in the same executable. If we split them up into two separate executables then it would be easier to make the cli options make sense.

**Comment by elmattic** [comment]
Note that this issue is really just a user facing ergonomic "problem" (like the warning message is misleading).

Also now we can `--detach` and run Forest in the background it would be better that all log messages are displayed once detached.

**Comment by lemmih** [comment]
I'm not sure I understand what you're saying. As I see it, the problem with ` forest --chain=calibnet chain export` is that `--chain=calibnet` is a flag for the node but we're actually running the client and thus the flag is completely ignored. We have two completely separate tools (the node and the client) that awkwardly share the same cli options and silently ignores the flags that apply to the other tool.

**Comment by elmattic** [comment]
Ah yes you are right, the command I have choosen is not really good, sorry. Will update the issue.

**Comment by lemmih** [comment]
Closing this issue. It is replaced by smaller, more targeted issues.
