### ISSUE TITLE
Improve Ubuntu build instructions

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#1770]
**Issue summary**

In the readme it is written:
```
# Ubuntu
sudo apt install build-essential clang ocl-icd-opencl-dev libssl-dev
```

This is not enough for building forest on Ubuntu 20.04.4 LTS.
It looks like `m4` and `pkg-config` are missing.

And I think we should always be explicit about which version of Ubuntu we are speaking.

**Other information and links**

**Comment by LesnyRumcajs** [comment]
@elmattic Possible workaround - only use the latest Fedora!

**Comment by tyshko5** [comment]
I checked that on a local x86_64 ubuntu 22.04 LTS version and couldn't spot the issue

**Comment by tyshko5** [comment]
Yes

**Comment by lemmih** [comment]
How did you do it? Did you use a VM?

**Comment by lemmih** [comment]
It looks like we should at least change the dependencies to be `build-essential clang lld ocl-icd-opencl-dev aria2 cmake`.

**Comment by lemmih** [comment]
Possibly leaving out `aria2`.

**Comment by lemmih** [comment]
ping @tyshko5

**Comment by tyshko5** [comment]
Yes, I've created a VM in virtual box

**Comment by lemmih** [comment]
Okay, let's align the build instructions in the Makefile (`install-deps`) with the build instructions in the README. And let's make a note that we're basing the information on ubuntu-20.04. @tyshko5
