### ISSUE TITLE
Followup to #1792: Review allow attributes.

### ISSUE THREAD

**Issue by tyshko5** [ChainSafe/forest#1797]
**Issue summary**

**Task summary**

These functions are not used therefore `allow` cannot be deleted:
- https://github.com/ChainSafe/forest/blob/7891dfbc81c5da771e46320dee59cac40dd97f9f/blockchain/chain_sync/src/peer_manager.rs#L208
- https://github.com/ChainSafe/forest/blob/7891dfbc81c5da771e46320dee59cac40dd97f9f/blockchain/message_pool/src/block_prob.rs#L19
- 

This
-
https://github.com/ChainSafe/forest/blob/7891dfbc81c5da771e46320dee59cac40dd97f9f/forest/src/cli/sync_cmd.rs#L43
- 
cannot be deleted, otherwise we are getting an error
```
warning: unused `std::result::Result` that must be used
  --> forest/src/cli/sync_cmd.rs:79:25
   |
79 |                         stdout.write("\r\x1b[2K\x1b[A".as_bytes());
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_must_use)]` on by default
   = note: this `Result` may be an `Err` variant, which should be handled
```
**Acceptance Criteria**

**Other information and links**

**Comment by lemmih** [comment]
For the `allow(dead_code)` functions, the comments say they're used in testing. Is that true? If so, only compile the code when testing.

For the `allow(unused_must_use)`, how about using the result?

**Comment by tyshko5** [comment]
This one seems not to be used by testing
- https://github.com/ChainSafe/forest/blob/7891dfbc81c5da771e46320dee59cac40dd97f9f/blockchain/chain_sync/src/peer_manager.rs#L208
-
This one is
- https://github.com/ChainSafe/forest/blob/7891dfbc81c5da771e46320dee59cac40dd97f9f/blockchain/message_pool/src/block_prob.rs#L19
-

**Comment by lemmih** [comment]
Great. Delete the unused code and remove the `allow(dead_code)` exception for the other function.
