### ISSUE TITLE
Avoid using `panic` for user-facing errors.

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1799]
**Issue summary**

Panics are for internal errors and should never intentionally be shown to the end-user. The following six panics should be replaced with proper error handling:

- https://github.com/ChainSafe/forest/blob/7e470572033e269d75efbebae1579dcd2bebf35b/forest/src/cli/state_cmd.rs#L54
- https://github.com/ChainSafe/forest/blob/7e470572033e269d75efbebae1579dcd2bebf35b/forest/src/cli/state_cmd.rs#L104
- https://github.com/ChainSafe/forest/blob/7e470572033e269d75efbebae1579dcd2bebf35b/forest/src/cli/state_cmd.rs#L148
- https://github.com/ChainSafe/forest/blob/7e470572033e269d75efbebae1579dcd2bebf35b/forest/src/cli/fetch_params_cmd.rs#L33
- https://github.com/ChainSafe/forest/blob/7e470572033e269d75efbebae1579dcd2bebf35b/forest/src/cli/mod.rs#L209
- https://github.com/ChainSafe/forest/blob/7e470572033e269d75efbebae1579dcd2bebf35b/forest/src/cli/mod.rs#L344

**Other information and links**

**Comment by tyshko5** [comment]
AFAI understand we are ought to change all of these occurrences with `cli_error_and_die`. In this case the process will exit and the tests connected to this will always fail (as exiting process during tests will lead to ending the whole test run for everybody)

**Comment by lemmih** [comment]
Change `to_size_string` to return a `Result` and update the tests.
