### ISSUE TITLE
Fix task cancelation

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#1848]
**Issue summary**

In Forest we use in a couple of places the `Task::spawn` method to spin up new tasks.

Unfortunately for all of them expect the ones in `daemon.rs` we don’t implement their cancellation making it possible that orphaned child tasks outlive parent tasks.
Any value moved to a future/ async block will never be dropped by the task unless the task has cleanly terminated or we are calling explicitly the `cancel` method on the task handle.

This can result in memory leaks over the lifetime of the client and also hindering us to shutdown gracefully the node (rocksdb Rust wrapper do not always manage to drop itself).

Therefore we should:

- [ ] Use the new heaptrack doc to create a report on current memory usage/ leaks (https://github.com/ChainSafe/forest/pull/1819)
- [ ] Conduct any research that could solve the issue, ie:
  - Tasks “structured concurrency"
  - Use arbortable futures
  - Other solution?
- [ ] Validate that forest can now be gracefully shutdown (https://github.com/ChainSafe/forest/issues/1587)
- [ ] Perform a second heaptrack analyse and observe if some of the leaks are gone (https://github.com/ChainSafe/forest/issues/1546)

**Other information and links**

https://docs.rs/async-std/latest/async_std/task/index.html#
https://docs.rs/futures/latest/futures/future/struct.Abortable.html
https://blog.yoshuawuyts.com/async-cancellation-1 (for “structured concurrency”)

**Relevant code where we use spawn without canceling**

- [chain_muxer](https://github.com/ChainSafe/forest/blob/main/blockchain/chain_sync/src/chain_muxer.rs)
- [tipset_syncer](https://github.com/ChainSafe/forest/blob/main/blockchain/chain_sync/src/tipset_syncer.rs)
- https://github.com/ChainSafe/forest/blob/main/blockchain/consensus/fil_cns/src/validation.rs#L125
- https://github.com/ChainSafe/forest/blob/main/node/forest_libp2p/src/service.rs#L260
- [state_manager](https://github.com/ChainSafe/forest/blob/main/blockchain/state_manager/src/lib.rs)
- https://github.com/ChainSafe/forest/blob/main/node/forest_libp2p/src/service.rs#L260

**Comment by lemmih** [comment]
Could you add links to where we use `spawn` without canceling or joining the task?

**Comment by elmattic** [comment]
Note that we should move to tokio tasks and in this case using `JoinSet` for handling proper task cancelation (as mentionned [here](https://github.com/ChainSafe/forest/pull/1943#issuecomment-1259663326)).

I think this issue can be repurposed.
