### ISSUE TITLE
Forest 🌲 Roadmap 2023

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#1874]
_This is a living document, Last updated: July 2023_

### **Forest 🌲 Vision** 
Client diversity - Forest 🌲 is the rust client for the Filecoin network. 

### **Summary** 
- Forest 🌲 client is in consensus with the latest version of the Filecoin network (the current one being NV21)
- Forest 🌲 maintains the latest snapshots and the entire archival history for a) main network b) Calibration test network 

### **Forest 🌲 Milestones 2023** 
- Forest Testnet - a test network solely focused on the needs of Forest development. ✅
- Mining Capability - the ability to run Lotus miner on Forest client. 🟡 
- Enhanced account management 
   - decoupling the wallet from Forest node for enhanced security
   - using external signature for transactions
- Network node statistics - a libP2P crawler to determine Forest’s network share in the Filecoin network.
- Filecoin Archival Node ✅
    - the ability to sync from genesis block
    - archival database layout design and development
    - protocol upgrade transitions
    - use case through a block explorer / APIs
- Node Infrastructure
    - Benchmarking Forest against Lotus 🟡 
    - Running permanent Forest nodes ✅
    - Forest performance regressions testing 🟢
- Faucet
    - Build a calibration network faucet [managed by Forest 🌲 node] 
- Forest RPC endpoints 🟢
   - host open public RPC end points
   - provide an Infura/Alchemy like service for the Filecoin community

_Refer to Forest 🌲 [milestones](https://github.com/ChainSafe/forest/milestones)_

### **Other Work Streams** 

**Builtin Actors Maintenance**
- ongoing maintenance of the built-in actors repo
- development and maintenance of  `fil-actor-state` interface
- owing up the testing infrastructure
- improvement, follow-up versions, and patch releases of the built-in actors
- audits and follow-up bug fixes

**Filecoin Governance (FIPs), network upgrades**
- Support FIP governance planning
- Implement network changes on time 

### **ChainSafe and Forest 🌲** 
- Build Forest 🌲 Website 🟢 
- Start Filecoin miner in Berlin 

### **Legend** 
✅ Completed 
🟡 Currently re-evaluating 
🟢 Currently working on

**Comment by LesnyRumcajs** [comment]
@lemmih Shall we close this and unpin from https://github.com/ChainSafe/forest/issues?

**Comment by lemmih** [comment]
Forest roadmap in Notion: https://www.notion.so/chainsafe/Forest-Roadmap-2024-745779322ad04f20a3a5fa0a7b6899c8
