### ISSUE TITLE
NV17 tracking 

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#1892]
Tracking issues related to Filecoin's network 17 upgrade

Filecoin's [NV17 board ](https://github.com/orgs/filecoin-project/projects/60/views/3)

[Filecoin v17 Network Planning](https://www.notion.so/filecoin/Filecoin-v17-Network-Planning-FIP-Scope-Implementation-Pathways-5a7b5a9a6c8a4d3aa18ab08fb3290891)

FIP Scope: [0029](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0029.md), [0034](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0034.md), [0041](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0041.md), [0044](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0044.md), and [0045](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0045.md).

Possible extended FIP scope: [0036](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0036.md) ~~and [0047](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0047.md).~~

~~Date for NV17 on butterfly: tentative Sept 30th 2022~~ 

~~Date for NV17 on calibration: Oct 20th 2022, epoch 1407374~~ 

Date for NV17 on mainnet: ~~tentative Nov 9th 2022~~   Nov 30th or Dec 6th 2022

**Comment by lemmih** [comment]
Everything is ready for the mainnet upgrade on Nov 30th. If nothing breaks then we can close the FIP issues.

**Comment by lemmih** [comment]
All good.
