### ISSUE TITLE
FIP 34 - Fix pre-commit deposit independent of sector content

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1903]
**Issue summary**

Checklist:
- [x] Are there any changes to the actor data structures that we need to be aware of?
- [x] Are there any changes to the network protocol?
- [x] Are there any changes to node behavior (eg. changes in block validation criteria, random number generation, etc)?
- [x] Are there any new magic numbers?

**Other information and links**

https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0034.md

**Comment by LesnyRumcajs** [comment]
**Data structures change**

[SectorPreCommitOnChainInfo](https://github.com/ChainSafe/forest/blob/c63b91f00f23ba53b9a16826ad3b1d9bd55bf4eb/vm/actor_interface/src/builtin/miner/mod.rs#L337-L350) should be changed to what [builtin-actors](https://github.com/filecoin-project/builtin-actors/blob/42b2add57822b9880c04cc4456c213bb7afb0c9f/actors/miner/src/types.rs#L280-L291) expose. Same applies to `SectorPreCommitInfo`. We do some serde tricks so it may not be possible to import it, most likely we'll just need adapt the changes in our implementation.

**Logical flow**
It should be self-contained in `builtin-actors`.

Related PR: https://github.com/filecoin-project/builtin-actors/pull/484

:warning: 
Those structs are used only in our RPC API which is not covered by tests. It would be great to at least test that it works manually.
