### ISSUE TITLE
FIP 44 - Standard Authentication Method for Actors

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1905]
**Issue summary**

- [x] Are there any changes to the actor data structures that we need to be aware of?
- [x] Are there any changes to the network protocol?
- [x] Are there any changes to node behavior (eg. changes in block validation criteria, random number generation, etc)?
- [x] Are there any new magic numbers?

**Other information and links**

https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0044.md

**Comment by LesnyRumcajs** [comment]
It doesn't seem we would need to change anything, except bumping the `builtin-actors` version.

It may be tempting to use this new method of the `Account` actor and not have our implementation for verifying message signatures. It's something to consider (keeping in mind a potential FVM overhead), but not a blocker.

Related PR: https://github.com/filecoin-project/builtin-actors/pull/502
