### ISSUE TITLE
FIP 45 - De-couple verified registry from markets

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#1906]
**Issue summary**

- [x] Are there any changes to the actor data structures that we need to be aware of?
- [x] Are there any changes to the network protocol?
- [x] Are there any changes to node behavior (eg. changes in block validation criteria, random number generation, etc)?
- [x] Are there any new magic numbers?

**Other information and links**

https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0045.md

**Comment by LesnyRumcajs** [comment]
**Data structure changes**
`SectorOnChainInfo` will have to be modified, adding a field `SimpleQAPower`. We will most likely be able to grab it (or import) from the `builtin-actors` repository.

All other changes seem like they will be self-contained in `builtin-actors` given that we do not have migrations at the moment.

Related Pull Request (in progress): https://github.com/filecoin-project/builtin-actors/tree/decouple-fil+
