### ISSUE TITLE
Update `tiny-cid` dependency

### ISSUE THREAD

**Issue by tyshko5** [ChainSafe/forest#1920]
**Issue summary**

cannot update as `Cid` struct moved from `tiny_cid::cid::Cid`, to struct `tiny_cid::Cid`

**Other information and links**

**Comment by lemmih** [comment]
Our version of `libp2p-bitswap` uses `tiny-cid-0.2` and we have to use the same version. Might be best to wait for the official version of `libp2p-bitswap` to be released.

**Comment by lemmih** [comment]
@tyshko5 This issue is still blocked, isn't it? If it not blocked and you want to work on it, please write a note explaining why the issue is no longer blocked.

**Comment by tyshko5** [comment]
Hailong said that tiny_cid is used only by libp2p-bitswap which will valish after his update
