### ISSUE TITLE
Update `filecoin-proofs-api` dependency

### ISSUE THREAD

**Issue by tyshko5** [ChainSafe/forest#1922]
**Issue summary**

cannot update due to `blst` version conflict

**Other information and links**

**Comment by tyshko5** [comment]
`fvm` uses v11.0 of `filecoin-proofs-api` so we cannot update

**Comment by lemmih** [comment]
@tyshko5 We've upgraded to `fvm-2.1`. Can you re-evaluate this issue?

**Comment by tyshko5** [comment]
This is already done
