### ISSUE TITLE
Update `libp2p` dependency

### ISSUE THREAD

**Issue by tyshko5** [ChainSafe/forest#1924]
**Issue summary**

cannot update due to version conflict

**Other information and links**

**Comment by lemmih** [comment]
@tyshko5 It would be great if you could give a more detailed description of exactly why we cannot upgrade this crate. We need to know when this issue will be unblocked and how much work it'll take to upgrade once it is possible.

**Comment by tyshko5** [comment]
`libp2p` `v0.48`  deprecated `NetworkBehaviourEventProcess` . That means that behaviour should be rewritten along the lines of https://github.com/dariusc93/rust-ipfs/commit/4299d956760118e7e32f3d08d0c9f31344953a11
