### ISSUE TITLE
Tag address for the right network.

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2000]
**Issue summary**

The code in `fvm_shared::address` uses `Mainnet` as the default network tag. It doesn't prevent us from using calibnet but it is far from ideal. We need the tag to match the network set by the `--chain` flag.

I see two options:
- Submit a PR to `fvm_shared` that lets the default network be selectable at run-time.
- Create a wrapper around `fvm_shared::address::Address` that picks the right network tag.

I think the first solution is preferable since there are many other crates (ie the FVM) that uses the `Address` type and it might be important that the tag is always set correctly.

**Other information and links**

**Comment by hanabi1224** [comment]
I see there is [`fn set_network(&mut self, network: Network) -> &mut Self`](https://docs.rs/fvm_shared/0.9.0/fvm_shared/address/struct.Address.html#method.set_network) in `Address` but its API does not support chaining like `Address::new_id(1).set_network(Network::Testnet)` which requires the signature to be `fn set_network(mut self, network: Network) -> Self`

**Comment by lemmih** [comment]
Indeed. That is option 2.

**Comment by hanabi1224** [comment]
I think it's still requires a good amount of code change from our side to pass the cli arg down the stream, how about this idea, having a `AppContext`

```rust
struct AppContext {
    network: RwLock<Network>
}

impl AppContext {
  pub fn instance() -> &static Self {
    once_cell::new()
   ...
  }

  pub fn new_address_with_id(id) -> Address;
}
```

**Comment by lemmih** [comment]
Yes, passing in the network type to every function is not feasible.

It's not necessary to use an `RwLock`, though. We can store the network type in a global atomic variable.

The fundamental problem is whether this will be sufficient. The FVM will not call our wrapped functions and will still create addresses with the wrong tag.

**Comment by hanabi1224** [comment]
I c, so the question is about whether putting this `AtomicU8` or `AtomicBool` network id in our code base or in their code base.  Personally, I feel it's kinda out of scope and a little tricky for a library to introduce such a way to override its defaults but we can try.  As for Opt 2, I searched in the code base and found 106 usages, it's a lot but I think I can take this one and update them all

**Comment by lemmih** [comment]
> I c, so the question is about whether putting this `AtomicU8` or `AtomicBool` network id in our code base or in their code base. Personally, I feel it's kinda out of scope and a little tricky for a library to introduce such a way to override its defaults but we can try. As for Opt 2, I searched in the code base and found 106 usages, it's a lot but I think I can take this one and update them all, and this `AppContext` is extensible to more similar cases for the future

Replacing the 106 usages in our code might not be enough, though. There are external crates (like the FVM) that will still create addresses with the hard-coded network type.

**Comment by hanabi1224** [comment]
Sry I accidentaly clicked on edit to your reply : (

> external crates (like the FVM) that will still create addresses with the hard-coded network type

Got it. If that's the case, it's definitely some design defect for a library that needs to be fixed

**Comment by lemmih** [comment]
> Sry I accidentaly clicked on edit to your reply : (
> 
> > external crates (like the FVM) that will still create addresses with the hard-coded network type
> 
> Got it. If that's the case, it's definitely some design defect for a library that needs to be fixed

It's basically a copy&paste mistake. The `fvm_shared::address` code used to be part of Forest and we set the network type at compile-time (like with Lotus, a compile-time flag was the only way to switch between mainnet and calibnet). Now the FVM people have copied the code and hard-coded the network type to always be `mainnet`.

**Comment by lemmih** [comment]
> Do you have an example so that we can justify the change we propose?

I do not. They are aware that this is a problem, though. Here's in code in question:

```rust
// TODO pull network from config (probably)
// TODO: can we do this using build flags?
pub const NETWORK_DEFAULT: Network = Network::Mainnet;
```

**Comment by hanabi1224** [comment]
Got it, that should be sufficient. I can look into fixing this

**Comment by hanabi1224** [comment]
Hey @lemmih the upstream PR https://github.com/filecoin-project/ref-fvm/pull/923 has been merged.  Should we wait for new releases of fvm* and fil* crates or upgrade to their dev versions?

**Comment by lemmih** [comment]
> Hey @lemmih the upstream PR [filecoin-project/ref-fvm#923](https://github.com/filecoin-project/ref-fvm/pull/923) has been merged. Should we wait for new releases of fvm* and fil* crates or upgrade to their dev versions?

Great. That was faster than I expected. Why did you use `fetch_update` rather than `store`, btw?

Let's wait for the next stable release of the FVM crates. I'll mark this issue as blocked until then.

**Comment by hanabi1224** [comment]
> Let's wait for the next stable release of the FVM crates.

Got it.

> Why did you use fetch_update rather than store, btw?

Yeah that's definitely the better API to use, I will send another PR to fix it

**Comment by lemmih** [comment]
@hanabi1224 I think the fix was released as part of `fvm_shared-2.0`. Could you verify to make sure and then close this issue?

**Comment by lemmih** [comment]
@hanabi1224 We probably need to call `set_current_network` in Forest.

**Comment by lemmih** [comment]
@hanabi1224 Hm, no, I was wrong. It hasn't been released yet. It'll be part of `fvm_shared-3.0` which still isn't out.

**Comment by hanabi1224** [comment]
Yeah just confirmed it's part of (fvm_shared v3.0.0-alpha.11)[https://docs.rs/fvm_shared/3.0.0-alpha.11/fvm_shared/address/fn.set_current_network.html] but not in `2.0`

**Comment by lemmih** [comment]
No longer blocked. @hanabi1224, could you verify that everything works as it should now?

**Comment by hanabi1224** [comment]
Sry for some reason I missed the notification, will take a look

**Comment by lemmih** [comment]
@hanabi1224 Try creating a new address, funding it from the faucet, and printing the wallet balance. If that works without a hitch then we can close this issue.

**Comment by hanabi1224** [comment]
As discussed, this ticket could be closed by https://github.com/ChainSafe/forest/pull/2376
