### ISSUE TITLE
Avoid hashing during snapshot export when --skip_checksum is used

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2013]
**Issue summary**
In PR #1979 we introduced automatic hashing when exporting a snapshot, and an associated `.sha256sum` checksum file is created.
We introduced also a `--skip_checksum` to avoid creation of this file but even if used it stills does the hashing.

**Task summary**
- [ ] Create a `Writer` that doesn't hash file when `--skip_checksum` is used.

**Acceptance Criteria**

- [ ] Export time of a snapshot should be similar to export time before PR 1979 when this flag is used.

**Other information and links**
PR #1979
https://github.com/ChainSafe/forest/blob/main/node/rpc/src/chain_api.rs#L80

**Comment by LesnyRumcajs** [comment]
I'm not sure the additional complexity is worth it as we'd most likely need to use trait objects (so more virtual tables with some small overhead) and a bunch of conditionals. The overhead is relatively small anyway (sha256sum on calibnet snapshot takes ~4s, while the download takes ~112s). 

The thing I would change is perhaps the naming, i.e. `--no-checksum-file` to point out that no additional file will be created. Even for logging purposes, I believe just printing the checksum *always* is essential, especially if you receive a bug report.

@elmattic what do you think?

**Comment by elmattic** [comment]
@LesnyRumcajs What is the overhead for a mainnet snapshot?
Maybe in the future the overhead could be smaller if we implement "stream hashing" (hashing at the same time we create the `.car` file).
Overall I agree with you, and even would consider removing this `--skip_checksum` option then.

**Comment by LesnyRumcajs** [comment]
I assume it's linear, so it'd stay at ~3.5%. 

Right now the hashing is happening at the same time we create the car file, i.e. after every write, our `Writer` updates the digest.

**Comment by elmattic** [comment]
> Right now the hashing is happening at the same time we create the car file, i.e. after every write, our `Writer` updates the digest.

So it's already optimal CPU-wise, right?

**Comment by LesnyRumcajs** [comment]
I can't think of a more efficient implementation that wouldn't make the code significantly more complex. I may be missing something though.

**Comment by lemmih** [comment]
Done.
