### ISSUE TITLE
Lodestar Light Client Research 

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#2018]
**Issue summary**
- Preliminary research on Light Client from Lodestar. 
- Information to follow for the Forest team.

**Other information and links**
- [light client routes](https://github.com/ethereum/beacon-APIs/pull/181)
- [light client endpoints](https://github.com/ChainSafe/lodestar/pull/4168) 
- [adopt REST API](https://github.com/status-im/nimbus-eth2/pull/3775)
- [Light Client Summit](https://streameth.tv/event/light-client-summit)
- [Lodestar Plans](https://github.com/ChainSafe/lodestar/issues/3469)

**Comment by LesnyRumcajs** [comment]
@lemmih shall we close this?

**Comment by lemmih** [comment]
Research not planned.
