### ISSUE TITLE
Add variable/blake2b256 support for Cids

### ISSUE THREAD

**Issue by austinabell** [ChainSafe/forest#203]
**Issue summary**

When building the AMT, to match the lotus serialization the only part that was a discrepancy was the Cids because it required a variable blake2b hash for the serialized Cids and generating this through the current version of multihash is not supported. 

To complete this issue, multihash will probably have to be forked, added the additional functionality, and update the Cid/ AMT crate to match needed changes. 

At this point there should be cbor serialization tests added to the AMT from generated vectors from lotus to ensure this always matches.

I will probably do this issue, so if someone wants to pick this up please let me know

**Other information and links**

**Comment by austinabell** [comment]
Multihash PR for tracking: https://github.com/multiformats/rust-multihash/pull/44

**Comment by vmx** [comment]
Multihash PR was merged and released as 0.9.4.
