### ISSUE TITLE
Remove uses of `OnceCell` from `GenesisInfo` and `GenesisInfoVesting`

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2032]
**Issue summary**

Delaying the computation of the vesting schedules no longer serves a purpose. We can remove all uses of `OnceCell` from the module.

**Other information and links**

https://github.com/ChainSafe/forest/blob/446bec41daa29d55ddfd3befa5e697d492302b89/blockchain/state_manager/src/vm_circ_supply.rs#L44-L45
https://github.com/ChainSafe/forest/blob/446bec41daa29d55ddfd3befa5e697d492302b89/blockchain/state_manager/src/vm_circ_supply.rs#L77-L81

**Comment by hanabi1224** [comment]
@lemmih Looks like it's not simple to remove `OnceCell` from GenesisInfoVesting, I might require another `fn init(&mut self, ...)` that be called before `get_` is called
