### ISSUE TITLE
Calibnet sync check GH Action

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2038]
**Issue summary**

Implement a check that verifies on a push (both PR and merge to `main`) that Forest can sync to `calibnet`. This check should be done on the `buildjet` machines.
- [x] Download the latest calibnet snapshot (use `forest chain fetch`),
- [x] Run `forest`, importing the snapshot,
- [x] Wait for sync. It'll be nice to do a health check as well.

**Other information and links**

The check will most likely need to be disabled when calibnet goes NV17, as we lack proper migrations.

**Comment by lemmih** [comment]
Extra bonus points if you do it in the code coverage action and include the results in the coverage report.

**Comment by LesnyRumcajs** [comment]
No bonus points - the code coverage action with calibnet check would take a long time (at least 40 minutes on release mode, but then we'd get a lot of false negatives because of optimized code).
