### ISSUE TITLE
Remove deprecated chain fetch and chain export from CLI

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2043]
**Issue summary**

As follow-up task of https://github.com/ChainSafe/forest/pull/2039

**Other information and links**

**Comment by lemmih** [comment]
@tyshko5 Let's hold off on this for a little while.

**Comment by lemmih** [comment]
The daily snapshot uploader should be updated before the commands are removed from forest: https://github.com/ChainSafe/forest-iac

**Comment by tyshko5** [comment]
https://github.com/ChainSafe/forest-iac/pull/17
