### ISSUE TITLE
Improve toml config parsing

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2078]
**Describe the bug**
If Forest configuration file has type errors, this will ~~result in a hard crash~~ be silented. Also a non-existing key is a no-op.

Ie, this section:

```
[rocks_db]
create_if_missing = true
parallelism = 12
write_buffer_size = 268435456
max_open_files = 1024
compression_type = "lz4"
compaction_style = false    # <-- Value should be a string not a boolean!
invoke_outer_gods = true    # <-- 😱 
```

**To Reproduce**
1. Dump config in config.toml file
2. Patch `rocks_db` section with the one above
3. Run with: `./target/release/forest --target-peer-count 50 --encrypt-keystore false --import-snapshot minimal_finality_stateroots_2215681_2022-10-03_06-00-30.car --halt-after-import -c config.toml  `
4. Observe crash

**Expected behaviour**

We should have a proper error, indicating to the user where the problem is.

Maybe also warn the user for the non-existing keys (in case we retired some or user did typos).

**Environment:**
 - Branch: main

**Other information and links**
n/a

**Comment by LesnyRumcajs** [comment]
Another case that I've just stumbled upon - if you provide a non-existing file, the result is just exit code 1, no output.
```
❯ target/release/forest --config cthulhu; echo $status
1
```
