### ISSUE TITLE
Researching/Implementing StorageMiner API

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/forest#210]
**Task summary**

We will require the ability to call into an existing Lotus nodes StorageMining API to retrieve specific pieces of data to be used in consensus and validation (e.g. sector size). This will require coordination with Filecoin team to determine a standard JSON representation for all API types. 

**Other information and links**

- [Lotus StorageMiner API](https://github.com/filecoin-project/lotus/blob/master/node/impl/storminer.go#L25)
- [Example Miner Call Info](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/utils.go)

**Comment by austinabell** [comment]
replaced with more up to date issues
