### ISSUE TITLE
Misc clean up in `forest_interpreter`

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2111]
**Issue summary**

 - `src/vm.rs`: Remove the unused `Heights` parameter.
 - `src/vm.rs`: Modify `circ_supply_calc` to take a database argument instead of a `StateTree` argument.
 - `src/default_runtime.rs`: Move `resolve_to_key_addr` to `src/lib.rs`.
 - `src/fvm/externs.rs`: Move to `src/fvm.rs`.

**Other information and links**

**Comment by hanabi1224** [comment]
@lemmih it looks like `circ_spply_calc` uses `state.snaps` to retrieve `ActorState` internally, is there equivilent funtions to directly read from DB?

```rust
fn get_fil_mined<DB: Blockstore + Store + Clone>(
    state_tree: &StateTree<DB>,
) -> Result<TokenAmount, anyhow::Error> {
    let actor = state_tree
        .get_actor(&reward::ADDRESS)?
        .context("Reward actor address could not be resolved")?;
    let state = reward::State::load(state_tree.store(), &actor)?;

    Ok(state.into_total_storage_power_reward())
}
```
