### ISSUE TITLE
Update project README

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2118]
**Issue summary**

The Forest README.md file could be spiced up and made more approachable:
- See <https://www.makeareadme.com/> for general techniques.
- See <https://github.com/matiassingers/awesome-readme> for examples.
- Get rid of the `Our crates` section. It doesn't matter to much people and it takes up too much space.
- Arrange sections with introductions and beginner information first. We want to tell people what Forest is and how it is used before we go into details about dependencies, installation, testing, etc.
- Show a demo of running forest: (Maybe download a calibnet snapshot), create a wallet, fund the wallet from the calibnet faucet, send the FIL to a separate account. Use <https://asciinema.org/>.
- Use more emoticons.

**Other information and links**

**Comment by creativcoder** [comment]
https://readme.so/editor is a good tool to scaffold things quick

**Comment by ansermino** [comment]
Some more recent suggestions, potentially duplicates:

- Add RPC info + links
- Update Forest description (align with roadmap annoucement)
- Reduce duplicated docs (favour docs site over readme)
- Mention snapshot service

**Comment by lemmih** [comment]
Most of the action items have been done. The rest should be included in the documentation before being copied to the README.
