### ISSUE TITLE
Benchmark aggressive DB configuration during tipset validation

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2135]
**Issue summary**

We can benchmark Forest's tipset validation performance by loading a snapshot and re-validating the last 2000 tipsets:
```bash
# Clear out the old database files
rm -rf ~/.local/share/forest/mainnet/
# Load the snapshot into our database and quit
./forest --import-snapshot file.car --halt-after-import
# Re-validate the last 2k tipsets in the database
./forest --import-snapshot file.car --skip-load --halt-after-import --height EPOCH
```

The in above snippet, `EPOCH` should be the height of the snapshot minus 2000.

We want to test if increasing the SST file size from the default of 64 to, say, 1G has negative effects. And we want to test if setting the `compaction_type` to `none` has negative effects. This is the configuration to benchmark:

```toml
[rocks_db]
max_open_files            = -1
compression_type          = "none"
compaction_style          = "none"
optimize_for_point_lookup = 256
```

Note that there's currently no option for changing the SST file size. It will have to be added. See [set_target_file_size_base](https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#method.set_target_file_size_base).

As a bonus, it would be interested to measure the effect of `compression_type`. How much space is saved and does it change the runtime performance?

Start with benchmarking calibnet as this will be much faster. When you're confident in the numbers for calibnet, run the benchmarks on mainnet.

**Other information and links**

**Comment by hanabi1224** [comment]
Maybe we should try the optional `jemalloc` feature, rocksdb's own [benchmark](https://github.com/facebook/rocksdb/wiki/Performance-Benchmark-201807#setup) setup has `jemalloc` on

**Comment by lemmih** [comment]
@sudo-shashank You can use these tables to format your results.

Calibnet:

| Change | Import Time | Total Time | Validation Time |
| :---  | :---: | :---: | :---: |
| baseline | | | |
| jemalloc | | | |
| no compaction | | | |

Mainnet:

| Change | Import Time | Total Time | Validation Time |
| :---  | :---: | :---: | :---: |
| baseline | | | |
| jemalloc | | | |
| no compaction | | | |

**Comment by lemmih** [comment]
@sudo-shashank As we talked about in the stand-up, you can post the results you already have. And please post any difficulties you have with running against mainnet. If you are running into difficulties then our end-users are also running into difficulties and we want to know about it.

**Comment by sudo-shashank** [comment]
Calibnet:

| Change | Import Time | Total Time | Validation Time |
| :---  | :---: | :---: | :---: |
| baseline |162 secs |414 secs|62 secs |
| no compaction |130 secs|421 secs |65 secs |

**Comment by hanabi1224** [comment]
Could it be useful to add a db size column? Recording the output of `du -hs ~/.local/share/forest/calibnet/db`

**Comment by elmattic** [comment]
Hey, would be great to add also some info on the process memory size. Rocksdb settings can have a great impact on this and we should know what are the tradeoff here.

In general I would start trying to script those benchmarks, so we can do some automatization, like running them on some spare computer or during the night, on some other hardware/os, etc.

**Comment by lemmih** [comment]
@elmattic Could you run the benchmarks as well and replicate the issues Shashank is encountering?

**Comment by elmattic** [comment]
@sudo-shashank Could you share the different settings for each tests you did? (so the `[rocks_db]` part) so we are on the same page? Thanks!

**Comment by sudo-shashank** [comment]
@elmattic I ran with default settings and 
```
[rocks_db]
write_buffer_size         = 1073741824
max_open_files            = -1
compression_type          = "none"
compaction_style          = "none"
optimize_for_point_lookup = 256
```
![Screenshot from 2022-11-04 08-19-54](https://user-images.githubusercontent.com/99187193/200516481-26bcc537-629d-4e32-8918-ff2ae34fb0e3.png)

Snapshot used: https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_2304961_2022-11-03_06-00-30.car

**Comment by elmattic** [comment]
Hey, you did use a calibnet snapshot, no? Because the url you are showing me is a mainnet snapshot.

**Comment by elmattic** [comment]
@sudo-shashank I've managed to reproduce your error as well. In fact this is also blocking me on the other issue I am working on (#2083).

Investigating more on it.

**Comment by lemmih** [comment]
@elmattic @sudo-shashank I think it's because we're being too aggressive with the height. I think we need at least `CHAIN_FINALITY` epochs to the top (bottom?) of the snapshot.
