### ISSUE TITLE
Optional support for using `lmdb` as the backend database

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2145]
**Issue summary**

The LMDB database might be better suited for storing the Filecoin blockchain than RocksDB. We should implement an optional blockstore backed by [heed](https://crates.io/crates/heed). Benchmarking the different backends can be done by measuring the time it takes to import a CAR file, the time it takes to finalize a snapshot import, and the time it takes to validate 1000 epochs.

The LMDB database has support doing async flushes which sacrifices some durability for performance. It would be interesting to benchmark with both the default settings and with async flushes enabled.

Importing a snapshot can be done with:
```bash
./forest --import-snapshot file.car --halt-after-import
```

Once a snapshot has been imported, we can validate the last 1000 epochs as such (where `EPOCH` is the snapshot height minus 1000):
```bash
./forest --import-snapshot file.car --skip-load --halt-after-import --height EPOCH
```

The results should be arranged in two tables like this:

Calibnet:
| Change | Import Time | Total Time | Validation Time |
| :---  | :---: | :---: | :---: |
| rocksdb | | | |
| lmdb | | | |
| lmdb (async) | | | |

Mainnet:
| Change | Import Time | Total Time | Validation Time |
| :---  | :---: | :---: | :---: |
| rocksdb | | | |
| lmdb | | | |
| lmdb (async) | | | |

**Other information and links**

**Comment by lemmih** [comment]
@tyshko5 You want this task?

**Comment by LesnyRumcajs** [comment]
Please also include the database size after the import & validation.

**Comment by sudo-shashank** [comment]
Due to poor performance and high disk usage we are not supporting LMDB
ref #2310
