### ISSUE TITLE
Improve error message for Incompatible snapshot

### ISSUE THREAD

**Issue by sudo-shashank** [ChainSafe/forest#2146]
**Issue summary**

1. Improve error message while importing incompatible snapshot file

Steps to reproduce:
- run import snapshot command targeting mainnet with calibnet screenshot or vice-versa.
`forest --import-snapshot forest_snapshot_calibnet_2022-10-20_height_1405521.car --halt-after-import`

Current error message:
`Failed miserably while importing chain from snapshot forest_snapshot_calibnet_2022-10-20_height_1405521.car: Invalid tipset: no msg root with cid bafy2bzacec3v62zit3kvwcgcqj2yp5apducfyvapfqxkjtbhwqubpe52wwrsm`

Better error message:
`Failed miserably while importing chain from snapshot forest_snapshot_calibnet_2022-10-20_height_1405521.car: Incompatible snapshot file`

**Other information and links**
Mainnet genesis block cid: `bafy2bzacecnamqgqmifpluoeldx7zzglxcljo6oja4vrmtj7432rphldpdmm2`
Calibnet genesis block cid: `bafy2bzacecz3trtejxtzix4f4eebs7dekm6snfsmvffiqz2rfx7iwgsgtieq4`

**Comment by lemmih** [comment]
By looking at the genesis block, we can tell which network a snapshot belongs to. If we load a calibnet snapshot when trying to connect to the mainnet, we can print an error message saying exactly what the problem is.
