### ISSUE TITLE
Split builtin-actors into versioned crates

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2147]
**Issue summary**

We depend on the [builtin-actors](https://github.com/filecoin-project/builtin-actors) but only the most recent version used by the Filecoin network is supported at the moment. After discussing with the other Filecoin devs, the Forest team will be reorganizing the structure of the builtin-actor crates and keep them maintained going forward. This issue tracks this work.

- [ ] Create a modified version of `fil_actors_runtime` which isn't tied to a specific network (ie calibnet, mainnet, or devnet). The network specific parts should be explicitly named or moved to a separate crate. The crate itself could be renamed to, say, `fil_actors_runtime_common` to avoid name clashes.
- [ ] Create v8 versions of each actor. For example, the v8 account actor should live in `builtin-actors/actors/account_v8` and the crate name should include v8.
- [ ] Create v9 versions of each actor. For example, the v9 account actor should live in `builtin-actors/actors/account_v9` and the crate name should include v9.
- [ ] Split actor crate in two: One for the states and state methods, one for the smart contract code.
- [ ] Update the CI to automatically test the v8 and v9 actors.

**Other information and links**

**Comment by lemmih** [comment]
Some work on splitting the v8 actors is available in this branch: https://github.com/filecoin-project/builtin-actors/tree/lemmih/upgraded-v8

**Comment by lemmih** [comment]
Grab hold of me tomorrow and get started on this task together, @sudo-shashank.

**Comment by sudo-shashank** [comment]
@lemmih PR for this task: https://github.com/filecoin-project/builtin-actors/pull/827

**Comment by lemmih** [comment]
@sudo-shashank News from the builtin-actors team: They don't want to host the slimmed down actors. We should fork the crates and put them in the Forest repository.

We don't need any of the tests nor do we need the smart-contract code. Could you copy over the actors (in versioned crates) and delete any unused code?

**Comment by lemmih** [comment]
@tyshko5 There's a lot of work that can be done in parallel. Feel free to lend a hand.
