### ISSUE TITLE
Calibnet reset causing network_version error!

### ISSUE THREAD

**Issue by hanbu97** [ChainSafe/forest#2161]
Currently network_version is determined by block height. However, as calibnet is reset, it will always get NetworkVersion::V13.

Related code 
https://github.com/ChainSafe/forest/blob/775e9e86a23ef429e14f2d27ff51d467ef9ab5b5/networks/src/lib.rs#L202

**Comment by lemmih** [comment]
Fixed in main. A new release will be out in a bit.
