### ISSUE TITLE
ChainSafe Solutions Research 

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#2164]
**Issue summary**
Light Client research by ChainSafe solutions team.

**Other information and links**
- [On-Feasibility-of-Fraud-Proof-Bridges](https://solutions.chainsafe.io/Publications/On-Feasibility-of-Fraud-Proof-Bridges)
- [an-attack-on-a-light-client-bridge](https://solutions.chainsafe.io/Publications/On-Feasibility-of-Fraud-Proof-Bridges#an-attack-on-a-light-client-bridge)

**Comment by LesnyRumcajs** [comment]
@lemmih shall we close this?

**Comment by lemmih** [comment]
Research not planned.
