### ISSUE TITLE
Forest 🌲 Lunch and Learns 

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#2176]
**Issue summary**
Organize Lunch and Learns for the Forest 🌲 team on a regular basis

**Current topics**
- Forest 🌲 infrastructure laC @LesnyRumcajs ✅
- Review of the Saturn Retrieval Project 
- Forest 🌲 architecture discussion @jdjaustin 
- Forest 🌲 test strategy discussion @lerajk 
- Invite mentors from Protocol Labs / Filecoin 
- Invite @zenground0 to share high impact ideas from [HERE](https://github.com/filecoin-project/FIPs/discussions?discussions_q=author%3Azenground0+)
- Invite @Kubuxu to share experience on Filecoin protocol development ✅

**Comment by LesnyRumcajs** [comment]
@lemmih shall we close this?
