### ISSUE TITLE
Cursor is lost after ctrl+c when prompt to download snapshot is active

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2204]
**Describe the bug**

In terminal (checked with both `alacritty` and in-built one), after interrupting (with ctrl+c) Forest while it's asking whether to download a snapshot, the cursor is not appearing again.

**To Reproduce**
1. Run fresh forest with e.g. `forest --chain calibnet`
2. Get asked whether to download snapshot
3. ctrl+c
4. the cursor is lost

**Expected behaviour**

After interrupting, the cursor should be back.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Fedora 36
 - Rust version(e.g. `rustc --version`)
 - Branch/commit f503eb5b88c706d0e7d50a0ffb4e0ec40f8e2df8

**Other information and links**

**Comment by jdjaustin** [comment]
Discovered an even worse bug while troubleshooting this, at least on my system (Ubuntu 22.04.1): hitting ctrl+c twice while at the "Enter the keystore passphrase" prompt does restore the cursor, but the terminal is now unresponsive (both in VSCode and a standalone terminal).
