### ISSUE TITLE
Generate daily benchmark results

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2208]
**Issue summary**

There are two key performance metrics that we want to measure and track over time:

1. Time to load a mainnet snapshot.
2. Validation time in tipsets per second.

The absolute performance numbers will depend on hardware. But if we compare against Lotus then the ratio of our performance vs. their performance should be relatively stable across different hardware.

We should create a service (as part of [forest-iac](https://github.com/ChainSafe/forest-iac)) that downloads a snapshot, imports it with both Forest and Lotus, runs each client for, say, 30 minutes, and notes down how many tipsets were validated.

The DO droplets have limited disk space so the database should be cleared between Forest and Lotus runs.

The final product might be a CSV file containing the versions of Forest and Lotus, the time it took to load the snapshots, and the validation speed in tipsets per minute. These files should be uploaded to our DO space such that we have one file per day.

**Other information and links**

**Comment by jdjaustin** [comment]
Current plan: 
- to compare time to load mainnet snapshot: for forest, execute `time ./forest --import-snapshot [file] --halt-after-import` where `[file]` is the latest snapshot file; determine appropriate commands in Lotus binary to determine corresponding metric in Lotus.
- to compare validation time in tipsets per second, may be able to execute something similar to `./target/release/forest --config <tbd> --encrypt-keystore false --import-snapshot <tbd> --halt-after-import --skip-load --height 2368640`; alternatively could have binary report the epoch, wait a certain amount of time, and have binary report the epoch again
- automate these steps in a similar fashion to PR #2231

**Comment by elmattic** [comment]
Maybe not for this PR but we could retrieve amount of gas used per tipset as well. The gas metric should be directly proportional of computational workload in the FVM. Then we could deduce gas/s.

> Detailed gas costs can be acquired from the StateReplay API endpoint

(from https://github.com/filecoin-project/lotus/issues/3326)

**Comment by jdjaustin** [comment]
I'm not sure if the time being reported is incorrect or if the time report format is just confusing/misleading. Typical time to import a snapshot is 3 seconds and the `time` method is reporting this in this format `0m0.003s`.

**Comment by jdjaustin** [comment]
`time` does not seem to be returning the proper results. Typical time to import a snapshot is 3 seconds, and while the results of time vary from run to run, it is never more than a few milliseconds.

**Comment by jdjaustin** [comment]
Using `time forest --chain calibnet --encrypt-keystore false --import-snapshot [file] --halt-after-import` with latest snapshot: 
![Screenshot from 2022-12-08 21-53-18](https://user-images.githubusercontent.com/11778588/206621214-bfdae43f-e9e7-4dfd-a00e-ab2493ed5b9e.png)

**Comment by lemmih** [comment]
> Using `time forest --chain calibnet --encrypt-keystore false --import-snapshot [file] --halt-after-import` with latest snapshot: ![Screenshot from 2022-12-08 21-53-18](https://user-images.githubusercontent.com/11778588/206621214-bfdae43f-e9e7-4dfd-a00e-ab2493ed5b9e.png)

Did you delete your questions about the time being off?

Everything looks fine to me. `Imported snapshot in: 5s` and `real        0m5.681s` agree with each other.

**Comment by lemmih** [comment]
What metrics script are you referring to?

Are you able to run the nodes manually to get benchmark results for either Forest or Lotus? Running on calibnet would be as good as mainnet when testing. If not, this is a good place to start. Running a task manually is the first step to automating it.

**Comment by jdjaustin** [comment]
> What metrics script are you referring to?
> 
> Are you able to run the nodes manually to get benchmark results for either Forest or Lotus? Running on calibnet would be as good as mainnet when testing. If not, this is a good place to start. Running a task manually is the first step to automating it.

Plan to either modify the benchmark script in #2231 or develop another script to cover these metrics. The screenshots above were manual results from Forest running on calibnet. Today my plan is to learn to run Lotus on calibnet.

**Comment by lemmih** [comment]
That benchmark script works very differently from what we're trying to do in this issue. It won't help you run these benchmarks and I doubt it's worth updating the script. Once you've figured out how to run the benchmarks manually, you can find inspiration in @elmattic's script regarding how to automate the process.

**Comment by jdjaustin** [comment]
Manual results from switching to Lotus testnet with `make clean calibnet` and evaluating snapshot import time with `time lotus daemon --import-snapshot [file] --halt-after-import`:
![Screenshot from 2022-12-13 19-36-00](https://user-images.githubusercontent.com/11778588/207483833-124eadca-cb67-4976-b8d9-9449723f8ca5.png)

**Comment by elmattic** [comment]
A question popped up yesterday with @jdjaustin for second point:

2. Validation time in tipsets per second.

Should this be measured just after snapshot loading? So when Forest/Lotus are in msg sync? (`SyncStage::Message`)?
Or when in follow mode once HEAD is reached?
I believe we should do it more during the former, say during 10 minutes, count number of validated epochs. Maybe we could use `APPLY_BLOCKS_TIME` as well to create the stat.

**Comment by lemmih** [comment]
The validation time is constant both before a snapshot has been loaded (at 0 epochs per second) and after HEAD has been reached (at 1 epoch per 30 seconds). We need to measure to epochs per second after a snapshot has been loaded and before HEAD has been reached.

We need to measure both Forest and Lotus so we can't rely on Forest-only metrics.

**Comment by jdjaustin** [comment]
> We need to measure to epochs per second after a snapshot has been loaded and before HEAD has been reached.

Would this be when the `Stage` is in `message sync`?

Also @elmattic suggested including memory usage in the snapshot load metrics. Any issues with including that as well in PR #2367?

**Comment by lemmih** [comment]
> > We need to measure to epochs per second after a snapshot has been loaded and before HEAD has been reached.
> 
> Would this be when the `Stage` is in `message sync`?

I believe so, yes.

> Also @elmattic suggested including memory usage in the snapshot load metrics. Any issues with including that as well in PR #2367?

Sure, tracking peak memory usage would be nice as well.

**Comment by elmattic** [comment]
Adding a few sub-tasks that we need to address:

- [ ] 1. Refactor snapshot path:
  We should make sure that the path of the snapshot is correct from the git-go and that the file exists. Remove also `snapshot_dir` method ([this](https://github.com/ChainSafe/forest/blob/jdjaustin/issue-2208-generate-daily-benchmark-results/scripts/benchmark_db/bench.rb#L233) won't work for `LotusBenchmark` class).
- [ ] 2. Implement missing methods to make online validation work for Forest and [uncomment line](https://github.com/ChainSafe/forest/blob/jdjaustin/issue-2208-generate-daily-benchmark-results/scripts/benchmark_db/bench.rb#L447) after testing both mainnet and calibnet.
- [ ] 3. Implement missing methods for `LotusBenchmark` class:
       [db_size](https://github.com/ChainSafe/forest/blob/jdjaustin/issue-2208-generate-daily-benchmark-results/scripts/benchmark_db/bench.rb#L328)
       [clean_db](https://github.com/ChainSafe/forest/blob/jdjaustin/issue-2208-generate-daily-benchmark-results/scripts/benchmark_db/bench.rb#L332)
- [ ] 4. Implement writing results to a `.csv` file in case of daily benchmark. Also support for writing in the file the commit hash and snapshot url so we can easily reproduce a benchmark a few days later.
- [ ] 5. Support for building clients in a temp directory, handling `git clone`, `git checkout` in the build command, expose tag/hash to the `Benchmark` class. Choose sensible default values.
- [ ] 6. Refactor class hierarchy to have a base benchmark class and move common methods there.
- [ ] 7. Support passing custom config for `LotusBenchmark`. Add support for Lotus db in temp dir.
- [ ] 8. Add a new "peak" memory benchmark step.
   Once a new snapshot has been imported and the node synced up to HEAD, let it run for 2 hours and measure how RSS and VSZ are evolving. Propose a way to represent this metric.
- [ ] 9. Add a snapshot fetch step to the script (for both db and daily benchmarks).
- [ ] 10. Fix `rubocop` errors. This can be done as an ongoing task and not just at the very last moment.
- [ ] 11. Move the script as part of [forest-iac](https://github.com/ChainSafe/forest-iac).
- [ ] 12. Update documentation.

**Comment by elmattic** [comment]
Removed some sub-tasks, we can do them in another PR.

**Comment by elmattic** [comment]
Peak memory benchmark is not really needed since our memory leak was fixed by @hanabi1224.

**Comment by LesnyRumcajs** [comment]
> Peak memory benchmark is not really needed since our memory leak was fixed by @hanabi1224.

It's still a useful metric. You never know when someone will introduce such a leak by mistake, and with a daily benchmark, we can quickly pinpoint where the regression happened.

**Comment by elmattic** [comment]
> > Peak memory benchmark is not really needed since our memory leak was fixed by @hanabi1224.
> 
> It's still a useful metric. You never know when someone will introduce such a leak by mistake, and with a daily benchmark, we can quickly pinpoint where the regression happened.

Yeah I agree, just wanted here to finish this PR faster so we can move the script on iac repo.

That said from experience running forest for a week, it will be hard to have such metric. RSS can fluctuate between 7.5 and 8.5GB.

**Comment by lemmih** [comment]
Unless I'm misreading the code, this issue is not done.

**Comment by elmattic** [comment]
@lemmih What exactly is missing regarding the script itself?

If there's the iac part a new issue has been opened here: https://github.com/ChainSafe/forest-iac/issues/92

**Comment by lemmih** [comment]
@elmattic This issue is for comparing Forest against Lotus. We want to know, not the absolute numbers for loading a snapshot, but the relative numbers compared against Lotus. This Ruby script doesn't do this at all. The script is nice and all but it doesn't even try to solve the problem described in this issue.

**Comment by lemmih** [comment]
Unless I'm misreading the code, the benchmark script can compare Forest in different configurations (say, mimalloc vs. jemalloc). While that may be useful in its own right, that's completely different from what this issue asks for.

**Comment by lemmih** [comment]
Hmm, I think I see where the confusion comes from. Josh solved this issue: https://github.com/ChainSafe/forest/issues/2714

**Comment by lemmih** [comment]
My bad. Was looking at the wrong thing.
