### ISSUE TITLE
Implement CAR file utility

### ISSUE THREAD

**Issue by austinabell** [ChainSafe/forest#222]
**Task summary**

A car file utility will be needed to import the state for genesis for the current testnet. Both Lotus and go-filecoin use the same [utility](https://github.com/ipfs/go-car) which isn't exactly documented. There is [a spec repo](https://github.com/ipfs/archive-format) which is WIP and [is mentioned that the go-car may not satisfy requirements](https://github.com/ipfs/archive-format/issues/13#issuecomment-444995978).

This will be needed because Lotus generates their genesis and then exports the current state in this CAR file format, which is used for their [devnet genesis](https://github.com/filecoin-project/lotus/blob/master/build/genesis/devnet.car). This will require the ability to store the dag state into our state tree to actually use to load the state from the car utility, but this utility can be done before then.

This is not needed for initial syncing, but will be required once we are performing the state transition and updating the state tree

**Specification reference**

- https://github.com/ipfs/archive-format (wip spec repo as referenced before)

**Other information and links**

**Comment by vmx** [comment]
The spec is at https://github.com/ipld/specs/blob/master/block-layer/content-addressable-archives.md

**Comment by austinabell** [comment]
> The spec is at https://github.com/ipld/specs/blob/master/block-layer/content-addressable-archives.md

Oh awesome! Didn't know this was there, thanks for the link :)
