### ISSUE TITLE
Improve Grafana dashboard

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2228]
**Issue summary**

Currently, Forest Grafana dashboard looks like this
![rocks_run](https://user-images.githubusercontent.com/9642092/202690054-220096b1-8b85-4502-9397-8f95fa782d2c.png)

There's room for improvement here, for example:
* Most of the figures seem to be aggregating, whereas it would be more beneficial to have it represented as a rate, e.g. `message p2p events`,
* a bunch of other metrics were introduced the last time the dashboard was updated,
* splitting all of this into several dashboards would improve readability,

The goal is to propose and implement better dashboard(s) so it's easier to monitor Forest's state and performance. In the future, we may have such a dashboard exposed to the public.

**Other information and links**

**Comment by lemmih** [comment]
Dashboard moved to Infra team. Closing this issue.
