### ISSUE TITLE
Investigate replacement of `pbr` crate

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2251]
**Issue summary**

`pbr` crate has not been released for 2+ years, it has some issues like [`RUSTSEC-2020-0071`](https://github.com/rustsec/advisory-db/blob/main/crates/time/RUSTSEC-2020-0071.md) with its published versions. We should investigate possible replacement

**Other information and links**

**Comment by creativcoder** [comment]
related: https://github.com/a8m/pb/issues/114

https://github.com/console-rs/indicatif can be an alternative

**Comment by tyshko5** [comment]
Actually `pbr` is maintained it's just the new version has to be released https://github.com/a8m/pb/issues/113

**Comment by lemmih** [comment]
> Actually `pbr` is maintained it's just the new version has to be released [a8m/pb#113](https://github.com/a8m/pb/issues/113)

That issue is five months old and the maintainer still hasn't responded. Looks to me like it is unmaintained.
