### ISSUE TITLE
Test vectors for Blocksync requests and responses

### ISSUE THREAD

**Issue by austinabell** [ChainSafe/forest#226]
**Issue summary**

Would be ideal to generate from Lotus, but we need some vectors of RPC requests and RPC responses to make sure serialization and deserialization happens correctly. 

An extension of this would be to handle and test the errors encountered during this in the tests.

Basic requests are tested (in a branch which I will link PR when it is created) against a Lotus node, but would be ideal for more extensive and vectors to be tested to ensure these requests aren't broken in the future.

**Comment by amerameen** [comment]
@austinabell do the conformance tests cover these cases? or will they? If so, let's close this issue

**Comment by austinabell** [comment]
They don't, but this is tested enough functionally right now and the format _should_ be stable now (hope I don't eat my words again on this) so not worth the hassle of generating vectors.
