### ISSUE TITLE
Properly handle SIGTERM and SIGQUIT

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2261]
**Issue summary**

At the moment, Forest has only the SIGINT handler implemented. Other signals should also be handled - SIGTERM and SIGQUIT. These, unlike SIGKILL, should support graceful shutdown.

**Other information and links**

https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html
https://github.com/Detegr/rust-ctrlc#handling-sigterm-and-sighup

Issue found in https://github.com/ChainSafe/forest/issues/2260

**Comment by elmattic** [comment]
Also we might want to have a dedicated `stop` subcommand like for Lotus:

https://lotus.filecoin.io/lotus/manage/lotus-cli/#lotus-daemon-stop
