### ISSUE TITLE
Handle SIGQUIT

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2263]
**Issue summary**

A follow-up of https://github.com/ChainSafe/forest/issues/2261. It's not as pressing as the other ones as it seems mostly linked with debugging and not production workflows.

It would be fantastic to take into account a suggestion from [GNU Termination signals](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html)
> Certain kinds of cleanups are best omitted in handling SIGQUIT. For example, if the program creates temporary files, it should handle the other termination requests by deleting the temporary files. But it is better for SIGQUIT not to delete them, so that the user can examine them in conjunction with the core dump.

**Other information and links**

**Comment by lemmih** [comment]
Do we need to handle SIGQQUIT at all? According to that suggestion, isn't it best to quit immediately when we receive SIGQUIT? If not, let's handle it the same way we handle SIGTERM. I'll assign this issue to you.

**Comment by lemmih** [comment]
Will re-open if it becomes a problem in the future.
