### ISSUE TITLE
Replace the unmaintained `difference` with `similar`

### ISSUE THREAD

**Issue by tyshko5** [ChainSafe/forest#2312]
**Issue summary**

As found out in https://github.com/ChainSafe/forest/issues/2252 difference is not maintained therefore an issue for audit, therefore we have to replace it as well as change  our code

**Task summary**

Replace `difference` with `similar` and change the accompanying code

Candidate: https://crates.io/crates/similar

**Acceptance Criteria**

- [ ] replace `difference` with `similar`
- [ ] fix the accompanying code

**Other information and links**

**Comment by lemmih** [comment]
Could you elaborate a bit on this issue?

**Comment by tyshko5** [comment]
As found out in https://github.com/ChainSafe/forest/issues/2252 `difference` is not maintained, there we have to replace it
