### ISSUE TITLE
Fix the `forest-cli wallet sign|verify` commands

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2335]
**Issue summary**

We should be able to sign and verify messages using the wallet keys. However, something seems to have broken.

Steps to reproduce:
1. Boot calibnet and sync to HEAD.
2. Get an address from your wallet: `forest-cli --token {token} wallet list`
3. Sign a message: `forest-cli --token {token} wallet sign -a {address} -m {message}`
4. Verify a signature: `forest-cli --token {token} wallet verify -a {address} -m {message} -s {signature}`

Current, incorrect output:
```bash
$ ./target/release/forest-cli --token {token} wallet sign -a f1uatkwrkzfn5yuw67sxoosh37rujleu6xvb2dhwq -m "test message"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHexCharacter { c: 't', index: 0 }', forest/cli/src/cli/wallet_cmd.rs:239:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```bash
$ ./target/release/forest-cli --token {token} wallet verify -a f1uatkwrkzfn5yuw67sxoosh37rujleu6xvb2dhwq -m "test message" -s "dummy signature"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OddLength', forest/cli/src/cli/wallet_cmd.rs:256:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Other information and links**

**Comment by tyshko5** [comment]
The issue here is that signature and message are not hex strings, which they have to be by the logic that hasn't changes (in this part) for at least more than a year, so I assume it to be right and this behaviour expected.

**Comment by lemmih** [comment]
Ah, indeed. Then you just need to improve the error message.
