### ISSUE TITLE
Miscellaneous tasks

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2356]
**Issue summary**

- [ ] #2679
- [X] Use the `tempfile` crate in `chain_export`. See `NamedTempFile::new_in` and `NamedTempFile::persist`. https://github.com/ChainSafe/forest/blob/364e7cb8e281db5f5ed69c5dbbf00eb89e051080/node/rpc/src/chain_api.rs#L80
- [x] Remove the `FullVerifier`. We used to have a mock verifier as well but it was rightfully removed. Now the `FullVerifier` doesn't make sense anymore. Removing will require touching quite a bit of code. https://github.com/ChainSafe/forest/blob/b82879cc6773ebf6ca747d122c35226453d87a41/types/src/verifier/mod.rs#L18
- [x] Remove all calls to `forest_statediff` in the daemon. State-diffing is handled by the standalone statediff executable. The statediff crate is used in multiple locations and they should all be removed. https://github.com/ChainSafe/forest/blob/b82879cc6773ebf6ca747d122c35226453d87a41/blockchain/state_manager/src/lib.rs#L1310
- [x] Get rid of `check_for_low_fd`. It is no longer necessary.
- [x] Move `open_db` to `forest_db`. https://github.com/ChainSafe/forest/blob/daf362e1472243edd59d5ffb17b23ff944001d04/forest/daemon/src/daemon.rs#L507-L527

This list contains tasks so small that they don't merit their own issue. The list is still growing.

**Other information and links**

**Comment by tyshko5** [comment]
https://github.com/ChainSafe/forest/pull/2368

**Comment by creativcoder** [comment]
I'm covering: 
> Move open_db to forest_db.

in https://github.com/ChainSafe/forest/pull/2342

**Comment by tyshko5** [comment]
https://github.com/ChainSafe/forest/pull/2370

**Comment by tyshko5** [comment]
https://github.com/ChainSafe/forest/pull/2380

**Comment by tyshko5** [comment]
https://github.com/ChainSafe/forest/pull/2389

**Comment by LesnyRumcajs** [comment]
@sudo-shashank are all tasks done, e.g.,
> Allow the forest crates to be compiled with both rocksdb and paritydb enabled. If both are enabled, either default to using rocksdb or add a flag for switching between the backends.

Or we decided not to do them?

**Comment by lemmih** [comment]
Hoisted out the last issue.
