### ISSUE TITLE
Migrate from `structopt` to `clap`

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2365]
**Issue summary**

Quote from [`structopt` doc](https://github.com/TeXitoi/structopt)
> As clap v3 is now out, and the structopt features are integrated into (almost as-is), structopt is now in maintenance mode: no new feature will be added.
Bugs will be fixed, and documentation improvements will be accepted.
See the [structopt -> clap migration guide](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#migrating)

**Other information and links**

**Comment by tyshko5** [comment]
I think it's not true that clap v3 has all the features of  structopt features. Namely it doesn't support parametrised Enums, which we are extensively using.

**Comment by LesnyRumcajs** [comment]
@tyshko5 In the [documentation](https://docs.rs/clap/latest/clap/_derive/_tutorial/index.html), I can see that parametrised enumerations are supported.
```rust
#[derive(Subcommand)]
enum Commands {
    /// does testing things
    Test {
        /// lists test values
        #[arg(short, long)]
        list: bool,
    },
}

It seems precisely what `SnapshotCommand` does.

```rust
pub enum SnapshotCommands {
    /// Export a snapshot of the chain to `<output_path>`
    Export {
        /// Tipset to start the export from, default is the chain head
        #[structopt(short, long)]
        tipset: Option<i64>,
        // other params
        // ..
        // ..
    },
```

Am I missing something?
