### ISSUE TITLE
Logging level flag

### ISSUE THREAD

**Issue by austinabell** [ChainSafe/forest#237]
**Issue summary**

Logging level should be able to be configured through a CLI flag, something like `--log-level` or `--verbosity`. Should be done after https://github.com/ChainSafe/forest/pull/232. Log level is currently static. 

(Will link in code where the logging level is set in code when that PR comes in)

**Other information and links**

**Comment by vmx** [comment]
Some loggers support changing the log level via the `RUST_LOG` env variable (e.g. flexi_logger of fil_logger).

**Comment by austinabell** [comment]
> Some loggers support changing the log level via the `RUST_LOG` env variable (e.g. flexi_logger of fil_logger).

Neither of those work with our async logger. The env variable was just being statically set using that builder but the env can be parsed using the underlying env_logger that is available to our current logger. I'll just do this now
