### ISSUE TITLE
[libp2p] Implement bitswap query timeout mechanism

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2398]
**Issue summary**

Currently when outgoing bitswap queries get no response, we don't cancel the queries thus the query ids are kept forever in the internal `HashMap`s, we should implement timeout mechanism and cleanup stale query ids

**Other information and links**

https://github.com/ChainSafe/forest/pull/2395#issuecomment-1375412728

**Comment by elmattic** [comment]
Nice, is this an issue with rust bitswap crate, or rather a misuse of the API on our side?

**Comment by hanabi1224** [comment]
> Nice, is this an issue with rust bitswap crate, or rather a misuse of the API on our side?

I would categorize this issue to the latter, although ideally, libp2p protocols should have a built-in timeout mechanism
