### ISSUE TITLE
Bug: forest daemon crashes during bitswap get query

### ISSUE THREAD

**Issue by creativcoder** [ChainSafe/forest#2405]
**Describe the bug**

Forest daemon crashes with snapshot: filecoin_snapshot_calibnet_2022-12-09_height_108720.car
using libp2p-bitswap fork at: https://github.com/hanabi1224/libp2p-bitswap?branch=forest-libp2p@0.50#6f14bc98846abb4a7e1ee8739d199a55bcfcb441

**To Reproduce**
Steps to reproduce the behavior (WIP):
2. Run '....'
3. See error

**Log output**

<details>
  <summary>Log Output</summary>
  
```
2023-01-10T11:22:59.031729Z  WARN forest_libp2p::service: Fail to send ChainExchange response    
thread 'tokio-runtime-worker' panicked at 'assertion failed: state.block.is_some()', /root/.cargo/git/checkouts/libp2p-bitswap-60205aaf66f912c5/6f14bc9/src/query.rs:216:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    1484452 IOT instruction (core dumped)  target/release/forest --chain calibnet --target-peer-count 50  false
```
</details> 

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04 LTS x86_64, kernel: 5.15.0-52-generic
 - Rust version(e.g. `rustc 1.68.0-nightly (b70baa4f9 2022-12-14))
 - Branch/commit: bd4c43e40bf527f3cc839d5c095b65899e4031f4

**Other information and links**

**Comment by hanabi1224** [comment]
I will take a look
