### ISSUE TITLE
Spike: Investigate unusual code snippet

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2406]
**Issue summary**

The `tipset_tracker.rs` file contains some peculiar looking code. I believe it does nothing (other than print a warning in some cases) but I'm not 100% sure. If the code truly does nothing, it should be deleted.

```rust
for cid in cids.iter() {
    // TODO: maybe cache the miner address to avoid having to do a `blockstore` lookup here
    if let Ok(Some(block)) = self.db.get_obj::<BlockHeader>(cid) {
        if header.miner_address() == block.miner_address() {
            warn!(
                "Have multiple blocks from miner {} at height {} in our tipset cache {}-{}",
                header.miner_address(),
                header.epoch(),
                header.cid(),
                cid
            );
        }
    }
}
```

**Other information and links**

**Comment by LesnyRumcajs** [comment]
I found the corresponding Lotus snippet
https://github.com/filecoin-project/lotus/blob/master/chain/store/store.go#L927-L937

Given that this method is called around 5 times per epoch (per Lotus comments which should apply to Forest as well) and the size of `cids` should be below 10, I would say it's fine to leave this check. The warning may come in handy in case of future fiascoes. What do you think @lemmih?

**Comment by lemmih** [comment]
Can we promote it to an error?

**Comment by lemmih** [comment]
Oh golly, they are removing entries after `finality` epochs. We don't do that. We just keep everything forever. Not sure how much space is leaked here but it's definitely a space leak.

**Comment by LesnyRumcajs** [comment]
@lemmih Indeed, it got added later on, roughly around the time of creating this piece of code so most likely the original Forest implementors didn't notice it. I can definitely port it to Forest https://github.com/filecoin-project/lotus/commit/13ff98416f394f54b0da7bfa63a45fc3bcda6095
