### ISSUE TITLE
chore: default `ChainStore::heaviest_tipset` to the genesis tipset

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2411]
**Issue summary**

Right now, `ChainStore::heaviest_tipset` has the option of being undefined. This causes a lot of `unwrap`s in other parts of the code.

We should default to the genesis tipset.

- [ ] Initiate the `ChainStore` with the genesis tipset as the heaviest tipset.
- [ ] Update the type of `ChainStore::heaviest_tipset` and update all calls to this function.

**Other information and links**

**Comment by tyshko5** [comment]
I don't think this is possible for now. The reason `ChainStore::heaviest_tipset` has the option of being undefined is because `heaviest` field of `ChainStore` struct is a `Mutex` of an `Option`. The reason why `heaviest` is basically an `Option` is not due to the real possibility of being `None`, but due to how `ChainStore` is initialised. This is done in part by `new` function and in part by `read_genesis_header`, that needs a `ChainStore` as an argument. So for `heaviest` to be genesis it first has to be `None`. We cannot do this as part of `new` function as `read_genesis_header ` is a `forest_genesis` function, which depends on our crate, therefore a circular dependency. We cannot refactor `forest_genesis` as it is part of widely used `utils`

**Comment by lemmih** [comment]
@tyshko5 How about defaulting to the genesis tipset in `ChainStore::new`?

**Comment by lemmih** [comment]
@tyshko5 Why is the genesis tipset invalid?

**Comment by tyshko5** [comment]
> @tyshko5 Why is the genesis tipset invalid?

For it to be valid, one has to run `read_genesis_header `, which needs an instance of `ChainStore`.

**Comment by lemmih** [comment]
Okay, so `read_genesis_header` calls `process_car` which sets the genesis block and heaviest tipset. How about refactoring `read_genesis_header` such that it just returns the genesis without updating `ChainStore`? Then we can call that function before the `ChainStore` is created.

**Comment by tyshko5** [comment]
To get genesis from file we need `ChainStore` because `process_car ` needs it. `process_car  needs it because `load_car` is part of `fvm_ipld_car`. There for refactor we need a possibility to refactor that crate

**Comment by lemmih** [comment]
You don't need to change `load_car`. That function had nothing to do with `ChainStore`.

**Comment by tyshko5** [comment]
@lemmih Is it true that here ( https://github.com/ChainSafe/forest/issues/2411#issuecomment-1385143749 )you meant that just the `heaviest` field of `ChainStore` struct has to be a genesis tipster, but we don't what to do anything with the database?

**Comment by lemmih** [comment]
> @lemmih Is it true that here ( [#2411 (comment)](https://github.com/ChainSafe/forest/issues/2411#issuecomment-1385143749) )you meant that just the `heaviest` field of `ChainStore` struct has to be a genesis tipster, but we don't what to do anything with the database?

I don't understand your question.

Let's talk some basics. A **blockchain** is a linked-list of blocks where each child has a higher **weight** than the parent. (How the weight is defined is not important here.) In Filecoin parlance, each link in the blockchain is called a **tipset** which then contains a set of blocks. The **genesis block/tipset** is the root of the blockchain. It's the final parent of all the other tipsets.

Forest can work with many different blockchains which all have different roots / genesis blocks. We keep track of the genesis block by writing it to our database.

Forest also needs to keep track of the tipset with the largest weight, aka the heaviest This will be the newest tipset that future blocks will use as a parent. The heaviest tipset is written to our database using `set_heaviest_tipset`.

When refactoring this code, it's important to understand what we want to do rather than just what the code did before. Do you have a good feel for what we want this code to do? If not, do you have a way to find out?
