### ISSUE TITLE
Lint: pedantic clippy warnings

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2420]
**Issue summary**

To further increase code quality, it would be interesting to look into pedantic [clippy group](https://rust-lang.github.io/rust-clippy/master/).

For each lint:
* add your GH handle to the lint so that two people are not working on the same lint,
* figure out if it's helpful and makes sense in our case,
* add it to the `lint` target in Makefile https://github.com/ChainSafe/forest/blob/d8eae69e556038af86e32a388e7e118b3bd3307d/Makefile#L73-L74
* fix the warnings if any
* tick the corresponding checkbox,

After they are all resolved, enable the entire pedantic group with perhaps some exceptions.

:warning: 
This is a low-priority issue; feel free to tackle a lint or two now and then if there's nothing more important to do.

Lint list (may differ in time & clippy version):
- [ ] `bool_to_int_with_if`
- [ ] `borrow_as_ptr`
- [ ] `case_sensitive_file_extension_comparisons `
- [ ] `cast_lossless`
- [ ] `cast_possible_truncation`
- [ ] `cast_possible_wrap`
- [ ] `cast_precision_loss`
- [ ] `cast_ptr_alignment`
- [ ] `cast_sign_loss`
- [ ] `checked_conversions`
- [ ] `cloned_instead_of_copied`
- [ ] `copy_iterator`
- [ ] `default_trait_access`
- [ ] `doc_link_with_quotes`
- [ ] `doc_markdown`
- [ ] `empty_enum`
- [ ] `enum_glob_use`
- [ ] `expl_impl_clone_on_copy`
- [ ] `explicit_deref_methods`
- [ ] `explicit_into_iter_loop`
- [ ] `explicit_iter_loop`
- [ ] `filter_map_next`
- [ ] `flat_map_option`
- [ ] `float_cmp`
- [ ] `fn_params_excessive_bools`
- [ ] `from_iter_instead_of_collect`
- [ ] ~~`if_not_else`~~
- [ ] `implicit_clone`
- [ ] `implicit_hasher`
- [ ] `inconsistent_struct_constructor`
- [ ] `index_refutable_slice`
- [ ] `inefficient_to_string`
- [ ] `inline_always`
- [ ] `invalid_upcast_comparisons`
- [ ] `items_after_statements`
- [ ] `iter_not_returning_iterator`
- [ ] `large_digit_groups`
- [ ] `large_stack_arrays`
- [ ] `large_types_passed_by_value`
- [ ] `linkedlist`
- [ ] `macro_use_imports`
- [ ] `manual_assert`
- [ ] `manual_instant_elapsed`
- [ ] `manual_let_else`
- [ ] `manual_ok_or`
- [ ] `manual_string_new`
- [ ] `many_single_char_names`
- [ ] `map_unwrap_or`
- [ ] `match_bool`
- [ ] `match_on_vec_items`
- [ ] `match_same_arms`
- [ ] `match_wild_err_arm`
- [ ] `match_wildcard_for_single_variants`
- [ ] `maybe_infinite_iter`
- [ ] `mismatching_type_param_order`
- [ ] `missing_errors_doc`
- [ ] `missing_panics_doc`
- [ ] `module_name_repetitions`
- [ ] `must_use_candidate`
- [ ] `mut_mut`
- [ ] `naive_bytecount`
- [ ] `needless_bitwise_bool`
- [ ] `needless_continue`
- [ ] `needless_for_each`
- [ ] `needless_pass_by_value`
- [ ] `no_effect_underscore_binding`
- [ ] `option_option`
- [ ] `ptr_as_ptr`
- [ ] `range_minus_one`
- [ ] `range_plus_one`
- [ ] `redundant_closure_for_method_calls`
- [x] `redundant_else`
- [ ] `ref_binding_to_reference`
- [ ] `ref_option_ref`
- [ ] `return_self_not_must_use`
- [ ] `same_functions_in_if_condition`
- [ ] `semicolon_if_nothing_returned`
- [ ] `similar_names`
- [ ] `single_match_else`
- [ ] `stable_sort_primitive`
- [ ] `string_add_assign`
- [ ] `struct_excessive_bools`
- [ ] `too_many_lines`
- [ ] `transmute_ptr_to_ptr`
- [ ] `trivially_copy_pass_by_ref`
- [ ] `unicode_not_nfc`
- [ ] `unnecessary_join`
- [ ] `unnecessary_wraps`
- [ ] `unnested_or_patterns`
- [ ] `unreadable_literal`
- [ ] `unsafe_derive_deserialize`
- [x] `unused_async`
- [ ] `unused_self`
- [ ] `used_underscore_binding`
- [ ] `verbose_bit_mask`
- [ ] `wildcard_imports`
- [ ] `zero_sized_map_values`

**Other information and links**

**Comment by tyshko5** [comment]
https://github.com/ChainSafe/forest/pull/2428

**Comment by lemmih** [comment]
To re-iterate two important points:

1. Don't work on this if you have other work to do.
2. Carefully consider whether the lint is beneficial. Include your arguments for why the lint should be enabled in your PR. Expect a lot of push-back so make sure your arguments are strong.

**Comment by hanabi1224** [comment]
How about [`unwrap_used`](https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_used) ? So that we enforce using `.expect` with a reason.  

There has a `allow-unwrap-in-tests` setting in `clippy.toml` so that we don't need to fix all tests

**Comment by lemmih** [comment]
> How about [`unwrap_used`](https://rust-lang.github.io/rust-clippy/master/index.html#unwrap_used) ? So that we enforce using `.expect` with a reason.
> 
> There has a `allow-unwrap-in-tests` setting in `clippy.toml` so that we don't need to fix all tests

@jdjaustin Maybe you could have a go at this one. Coming up with sensible error messages might be tough, though.

**Comment by LesnyRumcajs** [comment]
Stale, we have more priorities than pedantic clippy warnings now. :)
