### ISSUE TITLE
Correct Decrementing/Incrementing in `forest-cli sync wait`

### ISSUE THREAD

**Issue by jdjaustin** [ChainSafe/forest#2429]
**Issue summary**

Currently, it appears that `forest-cli sync wait` displays an absolute epoch in the `Todo:` field (beginning with the target epoch) and decrements the epoch until reaching the current snapshot epoch, whereas Lotus displays a differential count of validations remaining. Forest should also display the differential count and possibly add amount of messages validated and/or validations per second (see Lotus screenshot). Lotus also appears to be incrementing the `Current Epoch:` field.

**Other information and links**

Forest screenshot:
![Screenshot from 2023-01-13 09-14-23](https://user-images.githubusercontent.com/11778588/212356298-8f8486be-d035-4843-ad8d-bb839dcf4424.png)
Lotus screenshot:
![Screenshot from 2023-01-13 09-20-37](https://user-images.githubusercontent.com/11778588/212356516-cad04c86-949a-4df7-ab08-5ba127f369ac.png)

**Comment by lemmih** [comment]
Working on this is a bit difficult without calibnet. It _is_ possible to test with mainnet, though. Perhaps on a droplet.
