### ISSUE TITLE
Test jemalloc allocator

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2434]
**Issue summary**

We would like to test alternatives to the default system allocator used in Rust programs. jemalloc is one of those.

We are mainly interested in:
- Troubleshooting memory fragmentation (jemalloc has a reputation of creating much less fragmentation).
- Debugging features (ie heap profiling)

A first step would be to create a small code sample using jemalloc before trying on a bigger program like Forest.

**Other information and links**

https://github.com/tikv/jemallocator
https://github.com/jemalloc/jemalloc/wiki/Use-Case%3A-Heap-Profiling

**Comment by hanabi1224** [comment]
A side note: Similarly, I've tried [`dhat`](https://crates.io/crates/dhat) crate for memory profiling some time ago, forest daemon stucked forever on calibnet so I did not get a report
