### ISSUE TITLE
HashMap memory leak in `libp2p-bitswap`

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2440]
**Describe the bug**

As @elmattic  has found out, and with the metrics added by https://github.com/ChainSafe/forest/pull/2399 we can see HashMaps in `libp2p-bitswap` is leaking memory.

Running forest daemon on mainnet for ~1 hours, we can see below metrics
```
bitswap_container_capacities{type="BITSWAP_DB_QUERIES"} 3669687
bitswap_container_capacities{type="BITSWAP_REQUESTS"} 111078
```
where `requests` is of type `FnvHashMap<BitswapId, QueryId>` and `db_queries` is of type `FnvHashMap<QueryId, Query>,`(`Query` is complicated, containing multiple `FnvHashSet`s and `Vec`, the fix-sized struct it contains is already ~200 bytes)

200B * 3669687 ~= 700MB

and it's growing linearly, so it leaks memory at >700MB/h

**To Reproduce**
1. Run forest daemon on mainnet for a while
2. Check `http://localhost:6116/metrics`

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details> 

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**
 - OS: 
 - Rust version(e.g. `rustc --version`)
 - Branch/commit

**Other information and links**

**Comment by lemmih** [comment]
Is this something we should report upstream to libp2p-bitswap? Or would it make sense to fix it in our fork?

**Comment by hanabi1224** [comment]
I'm trying a make a fix in my fork first, will also report to upstream but the responses have been very slow
