### ISSUE TITLE
Publish bitswap crate to crates.io

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2461]
**Issue summary**

Tracking issue for polishing the `bitswap` crate implemented in https://github.com/ChainSafe/forest/pull/2445 and publishing to `crates.io`

TODO:
- [x] Readme
- [x] Code docs
- [x] Public API refinement, e.g. hide `Arc` in `BitswapRequestManager`
- [ ] move `BITSWAP_BLOCK_REQUEST_INTERVAL` to `BitswapRequestManager` config
- [ ] add `save_unrequested_blocks: bool` to `BitswapRequestManager` config
- [ ] add `sync_block` to `BitswapRequestManager`
- [x] Figure out how to remove `on_peer_(dis)connected` from public API
- [x] multiple async lib support. (tokio, async-std) 
- [ ] Re-evaluate TODOs. e.g. message queue
- [x] Examples
- [x] Tests (coverage > 80%)
- [x] `go-bitswap` compatibility tests
- [x] wasm support
- [ ] broadcast cancellations after receiving a block

**Other information and links**

**Comment by LesnyRumcajs** [comment]
@hanabi1224 Should we close this?

**Comment by hanabi1224** [comment]
@LesnyRumcajs I'm inclined not to publish and maintain a standalone crate before `rust-libp2p` stabilizes its API(s). What do you think?

**Comment by LesnyRumcajs** [comment]
Alright.
