### ISSUE TITLE
Project action

### ISSUE THREAD

**Issue by tyshko5** [ChainSafe/forest#2503]
**Issue summary**
Automate adding issues to the project using https://github.com/actions/add-to-project

**Other information and links**

**Comment by lerajk** [comment]
Key items to populate on the [git sprint board](https://github.com/orgs/ChainSafe/projects/11/views/3) are:

- tasks [column 1 as Title] created by the assignee [column 2 as Assignees] 
- populate the correct date an issue is assigned to the sprint cycle [column 3 as Sprint Cycle (2 weeks)] 

@tyshko5

**Comment by tyshkor** [comment]
Should we add all issues to the board? @lerajk

**Comment by lerajk** [comment]
We add issues that are part of the **current** Sprint Cycle on an on-going basis, make sense? Every 2 weeks. @tyshko5
