### ISSUE TITLE
Failing to convert CBOR transaction when Address is empty

### ISSUE THREAD

**Issue by rllola** [ChainSafe/forest#251]
We are having this following test case failing :
```
 {
        "description": "TODO invalid test case ",
        "encoded_tx": "iEBAAEIAAEIAAEIAAABA",
        "valid": false,
        "testnet": false,
        "message": {
            "to": "",
            "from": "",
            "nonce": 0,
            "value": "0",
            "gas_price": "0",
            "gas_limit": "0",
            "method": 0
        },
        "encoded_tx_hex": "884040004200004200004200000040"
    }
```

I suspect that forest doesn't check that the length is not 0 and try to get the first byte here :
https://github.com/ChainSafe/forest/blob/d1194bdd942fcd9856376f1cb486739d9631d59b/vm/address/src/lib.rs#L222

**Comment by austinabell** [comment]
This was fixed in https://github.com/ChainSafe/forest/commit/8c924495a492968f888157a27795b2dc0f428519
Can you confirm that updating to any commit after this fixes your issue?

Most recent commit is `a43df3026434770e11103a6aa794292f03190868` if that helps

**Comment by rllola** [comment]
Our test is now passing.

Thank you
