### ISSUE TITLE
Add snapshot export step to benchmarking

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2517]
**Issue summary**

It'd be helpful to add a snapshot export to the benchmark. Currently, we mostly measure entries' write speed. The main difference between `paritydb` and `rocksdb` performance is walking the entries' performance which is missed by the benchmarks. This would allow us to take a more informed decision when considering switches between database backends and allocators. We are interested in total export time, peak memory and average memory.

:warning: it may be that the mainnet export won't work for some configurations. This should be included in the report.

**Other information and links**

**Comment by lemmih** [comment]
This is now part of `forest-tool benchmark export`.
