### ISSUE TITLE
Memory usage tracking for paritydb

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2523]
**Issue summary**

This issue is here to track memory usage and make sure we don't regress too much regarding paritydb backend memory usage.

Technically it's not a regression since paritydb is not the default choice right now.

Benchmarks where done using following settings:

command: `./scripts/benchmark_db/bench.rb 2579280_2023_02_06T12_00_00Z.car --pattern 'baseline,parity*' --heights=60`

platform: M2, macOS

commit: fa08e35

Bench | Import Time | Import RSS | DB Size
-|-|-|-
baseline | 8m 6s | 3.05GiB | 94.73GB
paritydb | 13m 19s | 4.36GiB | 125.86GB
paritydb-jemalloc | 13m 13s | 4.27GiB | 125.86GB

Bench | Validate Time | Validate RSS
-|-|-
baseline | 6m 5s | 3.73GiB
paritydb | 3m 42s | 5.51GiB
paritydb-jemalloc | 3m 45s | 4.75GiB

---

commit: 31bbd2d

Bench | Import Time | Import RSS | Import VSZ | DB Size
-|-|-|-|-
baseline | 9m 8s | 5.43GiB | 398.32GiB | 94.74GB
paritydb | 11m 29s | 8.90GiB | 405.10GiB | 124.72GB
paritydb-jemalloc | 11m 16s | 9.54GiB | 402.63GiB | 124.72GB
paritydb-mimalloc | 10m 7s | 10.20GiB | 402.19GiB | 124.72GB

Bench | Validate Time | Validate RSS | Validate VSZ
-|-|-|-
baseline | 5m 7s | 3.76GiB | 426.07GiB
paritydb | 3m 31s | 6.19GiB | 428.05GiB
paritydb-jemalloc | 3m 32s | 6.31GiB | 428.14GiB
paritydb-mimalloc | 3m 31s | 5.43GiB | 435.92GiB

Tests will come for Linux as well.

**Other information and links**

**Comment by hanabi1224** [comment]
@elmattic I've merged a memory usage fix to `parity-db`, could you help test this PR branch with the patch? Thanks!
https://github.com/ChainSafe/forest/pull/2524

**Comment by elmattic** [comment]
> @elmattic I've merged a memory usage fix to `parity-db`, could you help test this PR branch that has the patch? Thanks!
> #2524

Of course, will do!

**Comment by elmattic** [comment]
No gains.

**Comment by hanabi1224** [comment]
> No gains, alas.

@elmattic Did you test on `aarch64-apple`? I can see ~2GB lower mem usage during import when I test on fedora 37 with x64 cpu

**Comment by LesnyRumcajs** [comment]
@elmattic what do we do with this issue? can it be closed?

**Comment by elmattic** [comment]
I think so, closing it.
