### ISSUE TITLE
Update instructions on setting linux swappiness parameter

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2563]
**Issue summary**

forest daemon is expected to consume more than 40% of physical memory on 16GB mem machine for tasks like `snapshot export` or `database pruning`(experimental under https://github.com/ChainSafe/forest/pull/2486). The default value(60) of `vm.swappiness` is not likely suitable for forest.  We should suggest a lower value on host machine or via docker options when docker is used in the forest get-started instructions.  By setting swappiness to 1, it could be possible to run snapshot export on a 8GB mem machine (pending verification)

> Swappiness is a [Linux kernel](https://en.wikipedia.org/wiki/Linux_kernel) parameter that controls the relative weight given to [swapping out](https://en.wikipedia.org/wiki/Virtual_memory#Address_space_swapping) of [runtime memory](https://en.wikipedia.org/wiki/Memory_footprint), as opposed to dropping [pages](https://en.wikipedia.org/wiki/Page_(computer_memory)) from the system [page cache](https://en.wikipedia.org/wiki/Page_cache), whenever a memory allocation request cannot be met from free memory. Swappiness can be set to a value from 0 to 200.[[18]](https://en.wikipedia.org/wiki/Memory_paging#cite_note-24) A low value causes the kernel to prefer to evict pages from the page cache while a higher value causes the kernel to prefer to swap out "cold" memory pages. The [default value](https://en.wikipedia.org/wiki/Default_(computer_science)) is 60; setting it higher can cause high latency if cold pages need to be swapped back in (when interacting with a program that had been idle for example), while setting it lower (even 0) may cause high latency when files that had been evicted from the cache need to be read again, but will make interactive programs more responsive as they will be less likely to need to swap back cold pages. Swapping can also slow down [HDDs](https://en.wikipedia.org/wiki/Hard_disk_drive) further because it involves a lot of random writes, while [SSDs](https://en.wikipedia.org/wiki/Solid-state_drive) do not have this problem. Certainly the default values work well in most workloads, but desktops and interactive systems for any expected task may want to lower the setting while batch processing and less interactive systems may want to increase it.[[19]](https://en.wikipedia.org/wiki/Memory_paging#cite_note-kerneltrap-25)

> The value of 60 is a compromise that works well for modern desktop systems. A smaller value is a recommended option for a server system, instead. As the Red Hat Performance Tuning manual points out [8], a smaller swappiness value is recommended for database workloads. For example, for Oracle databases, Red Hat recommends a swappiness value of 10. In contrast, for MariaDB databases, it is recommended to set swappiness to a value of 1 [9].
Changing the value directly influences the performance of the Linux system. These values are defined:
0: swap is disable
1: minimum amount of swapping without disabling it entirely
10: recommended value to improve performance when sufficient memory exists in a system
100: aggressive swapping

> To view your current setting for vm.swappiness, run:
`cat /proc/sys/vm/swappiness`
To set vm.swappiness to 1, run:
`sudo sysctl -w vm.swappiness=1`

**Other information and links**

https://en.wikipedia.org/wiki/Memory_paging#Swappiness
https://linuxhint.com/understanding_vm_swappiness/
https://docs.docker.com/config/containers/resource_constraints/#--memory-swappiness-details
https://docs.cloudera.com/cloudera-manager/7.2.2/managing-clusters/topics/cm-setting-vmswappiness-linux-kernel-parameter.html

**Comment by lemmih** [comment]
We need more experience to document optimal settings. After the infrastructure team has run Forest services (mining, public RPC) for a while, we'll see what suggestions they have.
