### ISSUE TITLE
Update VM exit codes to match new spec

### ISSUE THREAD

**Issue by austinabell** [ChainSafe/forest#257]
**Task summary**

Exit codes have changed, should be easy to update, I will likely do very soon so ping me if you want to do

**Specification reference**

- https://github.com/filecoin-project/specs-actors/tree/master/actors/runtime/exitcode

**Other information and links**

**Comment by ec2** [comment]
I can do it

**Comment by austinabell** [comment]
cool, make sure that you have the correct integer value mapping, I assume it only need to be from `ExitCode` -> `u64` or whatever but look into this to see what exactly is needed
