### ISSUE TITLE
Upload new calibnet snapshot after nv18 goes live

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2572]
**Issue summary**

Network version 18 goes live on calibnet at epoch 322354 (roughly 7 and a half hours from now). Forest does not support migrations so we will need a bootstrap snapshot that was generated by Lotus _after_ epoch 322354. This snapshot should be uploaded to our Digital Ocean space.

- [ ] Generate a calibnet snapshot using Lotus after epoch 322354.
- [ ] Upload it to the DO Space: https://cloud.digitalocean.com/spaces/forest-snapshots?i=88c522&path=calibnet%2F
  - Use the same filename format as the other snapshots.
  - Add a file with the SHA-256 hash.

**Other information and links**

**Comment by LesnyRumcajs** [comment]
@lemmih I believe it is done.

**Comment by lemmih** [comment]
Done.
