### ISSUE TITLE
Switch to using ParityDB by default

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2576]
**Issue summary**

ParityDB performs better and uses less memory than RocksDB. Let's use it by default.

- [ ] Update build files in Forest.
- [ ] Make sure our docker files don't install unnecessary dependencies.
- [ ] Update the CHANGELOG.

**Other information and links**

**Comment by lemmih** [comment]
Blocked by #2278

**Comment by LesnyRumcajs** [comment]
> Blocked by #2278

Doesn't seem to be directly related to ParityDb; I'd remove it as a blocker.

**Comment by elmattic** [comment]
Maybe we could remove (`rocks_db` member) in `Config` struct as well.

**Comment by LesnyRumcajs** [comment]
We don't want to remove RocksDb, only deprecate it in a way. As far as I remember, it needs to be there for serialisation reasons. Or am I missing something?

**Comment by elmattic** [comment]
Yeah, it's here if you have an old config file, with some RocksDb config.
