### ISSUE TITLE
Consider preloading param files in docker images

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2594]
**Issue summary**

It would increase the image size by ~280MB but reduces time-to-start of forest daemon

**Other information and links**

**Comment by LesnyRumcajs** [comment]
I don't have any strong opinion here. Perhaps it could be another image that we push with a tag suffix `preloaded`.

**Comment by hanabi1224** [comment]
I don't think it's super useful with the current data dir layout either.  It would only be beneficial when users don't mount the `filecoin-proof-parameters` dir

**Comment by LesnyRumcajs** [comment]
Done via https://github.com/ChainSafe/forest/pull/3902
