### ISSUE TITLE
Investigate the `sending on a closed channel` messages

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2603]
**Issue summary**

Running Forest yields a lot of warnings like this:
```
WARN forest_libp2p::chain_exchange::behaviour: sending on a closed channel    
```

We should investigate why these warnings are sent and decide how to better deal with them:

- Are they bugs? Can the code be fixed such that we don't sent to closed channels?
- Do they indicate a serious problem? Should they be promoted to errors?
- Do they indicate normal behavior? Should they be demoted to trace or debug messages?

**Other information and links**

**Comment by hanabi1224** [comment]
@lemmih This is not a bug.  In https://github.com/ChainSafe/forest/pull/2313 we changed the `chain_exchange_request` behaviour to send the same request to 2 peers in parallel, so that the response that arrives later is expected to be sent to a closed channel.
