### ISSUE TITLE
Switch to a custom allocator by default

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2607]
**Issue summary**

Once we have the benchmark results comparing `mimalloc`, `jemalloc` and the default allocator, we should decide which one to use by default. Most likely, based on the feedback from @elmattic and @hanabi1224 it would be one of the custom ones.

**Other information and links**

**Comment by hanabi1224** [comment]
Here's the snapshot import benchmark result I got on DO droplet

|branch|allocator|db size|peak rss|time|
|--|--|--|--|--|
|hm/track-peak-rss|default|100GB|12.02GB|4485s|
|hm/track-peak-rss|mimalloc|100GB|10GB|4909s|
|hm/track-peak-rss|jemalloc|100GB|8.92GB|3873s|

**Comment by hanabi1224** [comment]
So let's ship `jemalloc`?  @elmattic @LesnyRumcajs @lemmih

**Comment by lemmih** [comment]
Sounds good to me.

**Comment by LesnyRumcajs** [comment]
Yeah, sounds reasonable.

**Comment by elmattic** [comment]
@hanabi1224 what about validation time?

**Comment by elmattic** [comment]
Agree, but memory allocator should have an impact on the fvm, so validation time too, no?

**Comment by hanabi1224** [comment]
@elmattic OK, I can collect `BLOCK_VALIDATION_TIME` metrics with different allocators

**Comment by elmattic** [comment]
I will run the ruby benchmark script on my side on a Fedora 37.

**Comment by hanabi1224** [comment]
> I will run the ruby benchmark script on my side on a Fedora 37.

@elmattic Sounds good, thx!  At the same time, I will run forest with different allocators and fetch metrics with the below command

```
wget -O metrics http://localhost:6116/metrics && cat metrics | grep apply_blocks_time_ | tail -n 2

# output
apply_blocks_time_sum 163.53027957700002
apply_blocks_time_count 6
```

**Comment by hanabi1224** [comment]
@elmattic block validation metrics updated, no obvious gain or loss is observed.
