### ISSUE TITLE
Switch to official `prometheus-client` crate

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2610]
**Issue summary**

[`prometheus-client`](https://crates.io/crates/prometheus-client) has been used by `libp2p-metrics` and it's maintained by the official, we should consider migrating from the [`prometheus`](https://crates.io/crates/prometheus) crate.

**Other information and links**

https://github.com/tikv/rust-prometheus/issues/392#issuecomment-968072946

**Comment by eserilev** [comment]
hi, i'd like to pick this one up

**Comment by LesnyRumcajs** [comment]
@eserilev Sure, feel free to check this out.

The goal would be to completely eliminate the `prometheus` dependency (at least directly). An important check that it works would be running Forest for a moment and confirming that all the metrics that there were before are still present.

To get those, start `forest`, answer all the prompts and let it run for a few minutes. Then, in another terminal, grab the metrics.
```
# start forest, answer all the prompts and let it run for a few minutes
forest --chain calibnet
# grab the metrics
wget localhost:6116/metrics
```

**Comment by hxalid** [comment]
👋  is this issue being worked on or you still need someone to pick this up?

**Comment by lemmih** [comment]
> 👋 is this issue being worked on or you still need someone to pick this up?

You can pick it up.
