### ISSUE TITLE
Move `actor-interface` to `fil-actor-states`

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2628]
**Issue summary**

The `forest_actor_interface` no longer depends on any Forest specific logic and should be moved into the same repository as the actor crates.

- [x] Rename `forest_actor_interface` to `fil_actor_interface`.
- [x] Move crate to `fil-actor-states`.
- [x] Update Forest to use the new `fil_actor_interface` crate.

**Other information and links**

https://github.com/ChainSafe/fil-actor-states

**Comment by sudo-shashank** [comment]
@lemmih raised [PR](https://github.com/ChainSafe/fil-actor-states/pull/21) to add `fil_actor_interface` in [fil-actor-states](https://github.com/ChainSafe/fil-actor-states), once it's merged I'll update forest to use `fil_actor_interface` crate.
