### ISSUE TITLE
Re-evaluate whether libp2p kad service needs be made optional

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2630]
**Issue summary**

Currently
- Test coverage of libp2p kad being turned off is absent

While
- Optional kad service adds extra complexity to the code logic
- Optional kad service adds extra complexity to the testing
- Lotus does not make kad optional: https://lotus.filecoin.io/lotus/configure/defaults/ 

Questions
- What's the goal of making kad optional ?
- Any alternative solutions?

Conclusions
- [ ] Keep it optional
- [ ] Make it non-optional

**Other information and links**

https://lotus.filecoin.io/lotus/configure/defaults/

**Comment by LesnyRumcajs** [comment]
@hanabi1224 What do we do with this issue?

**Comment by hanabi1224** [comment]
@LesnyRumcajs Let's close this. Thanks!
