### ISSUE TITLE
Add missing actors to `fil-actor-states`

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2634]
**Issue summary**

`builtin-actors` added a bunch of new actors that we should import to `fil-actor-states` under v10.
https://github.com/filecoin-project/builtin-actors/tree/master/actors

These include:
- `datacap` (introduced earlier but we also don't have it)
- `eam`
- `ethaccount`
- `evm`
- `placeholder`

To avoid dead code, the statediff tool should include the missing actors, and the versions across Forest should be bumped to v10 where appropriate.
https://github.com/ChainSafe/forest/blob/main/utils/statediff/src/lib.rs#L121

**Other information and links**

**Comment by sudo-shashank** [comment]
not adding `placeholder` actor as it doesn't contain anything at the moment

**Comment by sudo-shashank** [comment]
all missing actors are added to `fil-actor-states`
