### ISSUE TITLE
Fix spellchecking for every member crate

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2656]
**Issue summary**

Our spellchecker has stopped working correctly and only spellchecks a few source files. This can be seen by running `cargo spellcheck list-files`. It should list every single source file in our repository but it doesn't. We need to figure out what went wrong and fix it.

**Other information and links**

**Comment by tinoh9** [comment]
Hi bro, have you resolved this issue? I also had a look to the repo but still did not find any invalid config or conflict. By the way, I found this alternative (https://github.com/crate-ci/typos) which is also wrote in Rust if this get you any attention.

**Comment by lemmih** [comment]
Still not fixed. The `typos` repository looks interesting but it is orthogonal to spellchecking in the documentation.

**Comment by LesnyRumcajs** [comment]
Hey @tinoh9, it seems the culprit in our case is `edition.workspace` which is not handled well by the spellcheck or its dependencies. The workaround is to put the edition explicitly. I hope it helps.

https://github.com/ChainSafe/forest/pull/2702

**Comment by tinoh9** [comment]
It is great that this issue has been solved. Really appreciate that I learn new debugging concept from you.
