### ISSUE TITLE
Upstream Arc implementation for Blockstore

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2667]
**Issue summary**

The `fvm_ipld_blockstore` crate implements the `Blockstore` trait for `Rc` but not `Arc`:
https://github.com/filecoin-project/ref-fvm/blob/622754f199dd4bb8cb140881a718a6c0ae4c47fd/ipld/blockstore/src/lib.rs#L133

An `Arc` implementation would make the code in Forest significantly simpler. For example, we wouldn't need as many `Clone` , `Send` and `Sync` trait constraints.

- [x] Submit a PR to `fvm_ipld_blockstore` with an Arc implementation.
- [x] Push for a new release of `fvm_ipld_blockstore`.
- [x] Create an issue for updating our code once a new release is out.

**Other information and links**

**Comment by creativcoder** [comment]
Raised a PR to ref-fvm: https://github.com/filecoin-project/ref-fvm/pull/1715

**Comment by lemmih** [comment]
Done!
