### ISSUE TITLE
 Align Forest send command behavior with the one from Lotus

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2668]
**Issue summary**

Lotus send [command](https://lotus.filecoin.io/lotus/manage/lotus-cli/#lotus-send) allows to specify the token amount in either `FIL` or `attoFIL` denominations.
That's not the case for Forest send command where it expects `attoFIL`.

- [x] Add support of similar behaviour.
- [x] Add tests covering the different denominations.
- [x] Update the documentation accordingly.
- [x] Make sure `sendFIL` still works in the JavaScript console

**Other information and links**

https://github.com/filecoin-project/lotus/blob/master/cli/send.go#L96
https://github.com/filecoin-project/lotus/blob/master/chain/types/fil.go#L86

**Comment by LesnyRumcajs** [comment]
I'd also add a strong emphasis on updating the documentation. The user sending 1e18 FIL by just following the docs may get confused. https://github.com/ChainSafe/forest/blob/main/documentation/src/docker.md

**Comment by elmattic** [comment]
> I'd also add a strong emphasis on updating the documentation. The user sending 1e18 FIL by just following the docs may get confused. https://github.com/ChainSafe/forest/blob/main/documentation/src/docker.md

Very good point.
