### ISSUE TITLE
Spike: Ethereum like APIs support

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2670]
**Issue summary**

With the release of NV18, Ethereum like APIs are now supported in the Lotus v1 API, or in v0 API when setting `EnableEthRPC` to `true`.

We would like to support similar endpoints in Forest.

Since there are around 40 methods (Ethereum-compatible JSON-RPC calls) that have been introduced, a first step would be to create a research spike of what is exactly needed in Forest to implement them.

Note also that the newly `evm` [commands](https://lotus.filecoin.io/lotus/configure/ethereum-rpc/#utilities) in Lotus are using some of those calls for their underlying implementation.
We might not need to implement them all in case we only start with support of similar cli utilities (but probably for supporting something like [Truffle Suite](https://trufflesuite.com/) more methods would be needed).

**Other information and links**

https://lotus.filecoin.io/lotus/configure/ethereum-rpc/
https://github.com/filecoin-project/lotus/blob/release/v1.20.0/node/impl/full/eth.go

**Comment by LesnyRumcajs** [comment]
It's already tracked via other RPC issues.
