### ISSUE TITLE
ParityDB performance advice

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2691]
**Issue summary**

We could try out this performance advice from paritydb maintainer. 
https://github.com/paritytech/parity-db/issues/189#issuecomment-1476583277

> On a side note: I've checked how parity-db is used in the forest projects and noted a few things:
1. On macos default file descriptor limit causes the database to fail at some point. You can raise the limit on startup with fdlimit crate.
2. If you decrease commit size [here](https://github.com/ChainSafe/forest/blob/main/utils/genesis/src/lib.rs#L190) to something like 64Mb you'd get better performance and lower peak memory usage.
3. You can further increase compression by setting lower compression threshold in the column settings. Default is 4096 meaning that any values of lower size won't be compressed.

**Other information and links**

**Comment by elmattic** [comment]
If you can create some benchmarks in the ruby script so we can test compression/commit size individualy. This would allow us to run same tests on different hardware/OS.
We need also to use same snapshot.

**Comment by lemmih** [comment]
Benchmark results:

Run on droplets with 16GiB of RAM and 300GiB of SSD. Each value is the average of 7 runs.

|   | Time (s)  | Rss (GiB)  |
|---|---|---|
| 1GiB  | 1169 (σ=20.6)  | 8.7  |
| 512MiB  | 1186 (σ=41.1)  | 5.5  |
| 256MiB  |1581 (σ=76.8)  | 4.2 |
| 128MiB  | 1547 (σ=25.2) | 3.5  |
| 64MiB  | 1715 (σ=113.3) | 2.9  |
| 32MiB  | 1402 (σ=68.9) | 2.9  |
| 16MiB  | 1468 (σ=173.4) |  2.7 |
| 8MiB  | 1609 (σ=149.8) | 2.5  |

`paritydb` blocks if their internal commit buffer reaches 64MiB. That might be why there's a spike at that buffer size.

**Comment by lemmih** [comment]
The measured time is how long it takes to load an uncompressed snapshot into a pristine database.

**Comment by LesnyRumcajs** [comment]
@lemmih Shall we apply the 32MiB as default then?

**Comment by lemmih** [comment]
> @lemmih Shall we apply the 32MiB as default then?

A bit of digging showed that increasing the channel size from `100` to something like `10_000` or `20_000` significantly improves performance when using smaller commit buffers. I'll post more benchmarks later. Looks like we can cut our peak memory usage from ~9GiB to ~3GiB without any loss of performance.

**Comment by LesnyRumcajs** [comment]
> Looks like we can cut our peak memory usage from ~9GiB to ~3GiB without any loss of performance.

I want this. Forest on Raspberry Pi is within our reach!

**Comment by lemmih** [comment]
Most of our data now lives in CAR files. I think we've gotten as much performance out of ParityDB as possible.
