### ISSUE TITLE
Prune direct FVM usage from Forest

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2713]
**Issue summary**

Our codebase currently uses `fvm` (fvm2), `fvm3` and `forest_shim`. This creates potential version issues and is confusing.

- [x] Re-export all FVM3 structs/constants in the Forest shim and use them in Forest. In the places where we use FVM2, we should switch to FVM3 or use a shim.
- [ ] Impose a strict rule of not using FVM/FVM3 directly with `.clippy`. All in all, the `fvm` and `fvm3` should be removed from the workspace. 

**Other information and links**

**Comment by jdjaustin** [comment]
Blocked by #3195

**Comment by lemmih** [comment]
Banning imports isn't necessary. Closing as completed.
