### ISSUE TITLE
Add a disable GC option to config

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2721]
**Issue summary**

In some cases like testing quickly a new feature or just doing some performance benchmark on mainnet, we would like to disable entirely GC in Forest.
Garbage Collection can add a significant overhead to the application, and you only really need it when running a production node.

**Other information and links**

https://github.com/ChainSafe/forest/blob/main/forest/shared/src/cli/config.rs#L176

**Comment by hanabi1224** [comment]
@elmattic How about a command line option `--no-gc`?

**Comment by elmattic** [comment]
👍  I'm fine with that. Actually I think it doesn't need to be in config file since it's something more for us.
