### ISSUE TITLE
Implement Hadolint CI For DockerFiles

### ISSUE THREAD

**Issue by samuelarogbonlo** [ChainSafe/forest#2722]
**Issue summary**
This task is to implement Hadolint CI to better the state of our docker files and keep them at system standards. 

**Task Requirement**
- All CI checks must pass
- Dockerfiles must have better comments 
- PR checks must pass before merge

**Comment by LesnyRumcajs** [comment]
It's already done in https://github.com/ChainSafe/forest/issues/2613, no?
