### ISSUE TITLE
Upgrade libp2p from 0.51.1

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2762]
**Issue summary**
The recent upgrade https://github.com/ChainSafe/forest/pull/2732 most likely introduced a regression https://github.com/ChainSafe/forest/issues/2755

Reverting this upgrade seems to mitigate the issue (all my mainnet sync trials passed for Forest pinned to `0.51.1`, whereas none passed with the updated libp2p). That was around ten trials. 

The revert https://github.com/ChainSafe/forest/pull/2759 is a temporary workaround, the library should be updated, and the `deprecated` suppressions should be removed. These can be found by gripping this ticket link in the codebase.

:warning: when updating libp2p, make sure it syncs to mainnet.

If it turns out that the issue is back again without the libp2p update, this one should be closed and the original bug ticket should get re-opened.

**Other information and links**

**Comment by LesnyRumcajs** [comment]
https://github.com/ChainSafe/forest/pull/3219

**Comment by thomaseizinger** [comment]
Let us (@mxinden & myself) know if we can help you with the update! :)

**Comment by LesnyRumcajs** [comment]
@thomaseizinger Thanks! I really appreciate it, I will reach out once I contrive a minimal reproducible example of the issue.

**Comment by hanabi1224** [comment]
Update: the issue is likely to be related to https://github.com/libp2p/rust-libp2p/pull/4250  @LesnyRumcajs has forest running well by raising the connection limit

**Comment by LesnyRumcajs** [comment]
There were some other changes that may have helped, e.g., not banning peers when they abruptly close the connection.

**Comment by LesnyRumcajs** [comment]
https://github.com/ChainSafe/forest/pull/3267
