### ISSUE TITLE
Introduce `stable` tag for docker images

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2767]
**Issue summary**
We are currently using the moving tag `latest`, which may be confusing. See an interesting article dedicated to this problem [here](https://vsupalov.com/docker-latest-tag/).

It'd be beneficial to change the behaviour a bit:
- `latest` shall denote the latest stable release
- `edge` shall denote the latest development build (latest `main` build)

- [ ] introduce `edge` tag to the Docker workflows
- [ ] update the documentation
- [ ] update the `forest-iac` infra so that it uses the `edge` tag for tests

**Other information and links**

**Comment by hanabi1224** [comment]
How about using `latest` for the latest stable release and `dev` for rolling builds?

**Comment by LesnyRumcajs** [comment]
I'd go with `edge` and `latest` as described in
https://devops.pingidentity.com/docker-images/releaseTags/#edge
https://devops.pingidentity.com/docker-images/releaseTags/#latest

Also this approach seems to be supported by docker meta action.
https://github.com/docker/metadata-action#typeedge

Sounds good?
