### ISSUE TITLE
Filecoin nodes public dashboard

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2789]
**Issue summary**

We would like to have a crawler and in effect a dashboard, publicly hosted, with the current Filecoin network usage including:
- number of nodes,
- % of different agents in the network
- ...

**Other information and links**
This can be done with https://github.com/dennis-tra/nebula (it will collect all the necessary data to a db). We need to create proper dashboards and host them publicly or expose some endpoints and let some other FE handle the dashboards.

This is a part of 2023 roadmap:
> Network node statistics - a lipP2P crawler to determine Forest’s network share in the Filecoin network.

from https://github.com/ChainSafe/forest/issues/1874

We estimate to have it done for the Forest website, and so we aim for Q4 2023 or Q1 2024.
ETA: 2024-01-31

**Comment by LesnyRumcajs** [comment]
most likely not needed, we should just re-use https://github.com/dennis-tra/nebula

**Comment by lemmih** [comment]
The Infra team will run nebula.
