### ISSUE TITLE
Prevent future usage of `time` crate

### ISSUE THREAD

**Issue by jdjaustin** [ChainSafe/forest#2820]
**Issue summary**

We recently replaced all instances of the `time` crate (note: this crate differs from `core::time`, `std::time`, and `tokio::time`) with `chrono`. We would also like to prevent usage of the `time` crate in the future with a message to use `chrono` instead. One possibility is to modify `.clippy.toml`; however this approach may only be possible with specific types/methods and not the entire crate. Another possibility is to modify one of the dependencies check scripts (e.g., `find_duplicate_deps.rb`).

**Other information and links**
Issue created as part of discussion in PR #2812.

**Comment by q9f** [comment]
just posting this for fun: #1426

context: #1247

**Comment by jdjaustin** [comment]
It doesn't look like this can be done using `.clippy.toml`--there are `disallowed_method` and `disallowed_type` lints, but I haven't found anything equivalent to `disallowed_crate`. However, I think I've figured out a way to do this by modifying one of our Ruby scripts to check all `Cargo.toml` files for any variation of `time.workspace` or `time =`. A similar approach can also be used to address the task in #2713  to impose a ban on usage of the FVM/FVM3 crates outside of the shim (with an exception for the `/utils/forest_shim/Cargo.toml` file).
