### ISSUE TITLE
Draft: educational materials for filecoin

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#2870]
Maybe one day we can get a track like _0-to-filecoin_ with _select_ materials like:
- What is a blockchain?
- What is IPFS?
- What is filecoin (and how does it bring the two together)

_Originally posted by @aatifsyed in https://github.com/ChainSafe/forest/pull/2846#discussion_r1193541031_

**Comment by jdjaustin** [comment]
Check this out: https://curriculum.pl-launchpad.io/curriculum/

**Comment by LesnyRumcajs** [comment]
@aatifsyed What do we do with this? Is this actionable?
