### ISSUE TITLE
Modify `forest` and `forest-cli` to prefer compressed files

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2873]
Compressed snapshots are roughly half the size of uncompressed snapshots, and un-compressing them is fast. By default, we should prefer downloading/importing compressed snapshots.

- [ ] Use `https://snapshots.mainnet.filops.net/minimal/latest.zst` by default when downloading from the official snapshot provider.
- [ ] Use `https://forest.chainsafe.io/mainnet/snapshot-latest.car.zst` by default when downloading from our own servers.

**Comment by lemmih** [comment]
It appears that filops no longer hosts uncompressed snapshots. We should update Forest to reflect this.

**Comment by aatifsyed** [comment]
Does this require anything not already done in #2888 ?
