### ISSUE TITLE
Build profiles are too aggressive

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#2883]
Yes, this is a bit harsh. On the other hand we should have a way to catch panics. Right not as far as I understand, we catch panics only in cases we are testing for a `JoinError`:

https://docs.rs/tokio/1.23.0/tokio/task/struct.JoinError.html

_Originally posted by @elmattic in https://github.com/ChainSafe/forest/pull/2336#discussion_r1060617959_

**Comment by elmattic** [comment]
Preferably we should check the `JoinError` after awaiting each `JoinHandle` and abort cleanly in case of panics, but the refactor to get there is not trivial.

**Comment by aatifsyed** [comment]
This is my guess as to what's happened, please correct me if I'm wrong
- We were hitting errors where spawned tokio tasks were panicking, presumably throwing up backtraces that no-one would see
- We decided that aborting the process (print a backtrace, but no unwinding) was a "loud failure", so at least we'd get a bug report

And it would be more idiomatic to bubble up panics in spawned tasks, which is the refactor you're suggesting?

**Comment by elmattic** [comment]
> We were hitting errors where spawned tokio tasks were panicking, presumably throwing up backtraces that no-one would see

No that did not happen, but I choose defensive code and turn this "loud failure" mode, just in case.

**Comment by elmattic** [comment]
> And it would be more idiomatic to bubble up panics in spawned tasks, which is the refactor you're suggesting?

Yes, but that's probably a quite involving task.

**Comment by lemmih** [comment]
We no longer use `panic = "abort"` since the FVM requires unwinding panics for correctness.
