### ISSUE TITLE
[CI] Enable sccache in docker build and publish ci job

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#2884]
**Issue summary**

Since we have switched `sccache` backend to DO space, we can enable `sccache` in `build` stage with below changes

- [ ] Implement a build arg flag (e.g. SCCACHE_ENABLED=true) for enabling `sccache`
- [ ] Set `RUSTC_WRAPPER=sccache` when the flag above is on
- [ ] Download and install proper prebuilt `sccache` binaries for `amd64-linux` and `arm64-linux` respectively
- [ ] Pass `sccache` `s3` env args via build arg

To convert build arg to env var
```Dockerfile
ARG SCCACHE_ENDPOINT
ENV SCCACHE_ENDPOINT=$SCCACHE_ENDPOINT
```

To disable/enable sccache
```Dockerfile
ARG SCCACHE_ENABLED
# https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
ENV RUSTC_WRAPPER=${SCCACHE_ENABLED:+sccache}
```

**Other information and links**

**Comment by LesnyRumcajs** [comment]
@hanabi1224 Is it the same as https://github.com/ChainSafe/forest/issues/2519? If so, let's close one of them.

**Comment by lemmih** [comment]
@hanabi1224 This is done, right?

**Comment by LesnyRumcajs** [comment]
@hanabi1224 bump

**Comment by hanabi1224** [comment]
@lemmih @LesnyRumcajs No I don't think we have enabled `sccache` in docker build. I can prioritize this task

**Comment by LesnyRumcajs** [comment]
Do we need it? I mean, is there a compelling reason to have this? What time gains are we talking about?

**Comment by hanabi1224** [comment]
@LesnyRumcajs  I think the major benefit is that, we could save some $ by switching from buildjet to GH hosted runners

**Comment by hanabi1224** [comment]
@LesnyRumcajs I believe this has been implemented in https://github.com/ChainSafe/forest/pull/3510 but superseded by the `buildjet` to `fuzzy` switch.

**Comment by LesnyRumcajs** [comment]
We're not running this on `fuzzy` anymore, given it introduced some nasty race conditions.

**Comment by lemmih** [comment]
If this task had been easy, it would already have been done. Closing as our time is worth more than what we spend on buildjet.
