### ISSUE TITLE
PR for snapshot links

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#2897]
**Issue summary**

To include Forest snapshot links, raise a PR to the [Filecoin Docs](https://github.com/filecoin-project/filecoin-docs). 

**Task summary**

- [ ] Include a snapshot link to the websites: [mainnet](https://docs.filecoin.io/networks/mainnet/details/#resources), [calibration](https://docs.filecoin.io/networks/calibration/details/), [lightweight snapshots](https://lotus.filecoin.io/lotus/manage/chain-management/#lightweight-snapshot)
- [ ] Include a snapshot link to the GitHub MD:  [mainnet](https://github.com/filecoin-project/filecoin-docs/blob/main/content/en/networks/mainnet/details/index.md#resources), [calibrationnet](https://github.com/filecoin-project/filecoin-docs/blob/main/content/en/networks/calibration/details/index.md)

**Comment by lemmih** [comment]
Is this done, @lerajk?

**Comment by LesnyRumcajs** [comment]
Pretty sure it's done looking at the docs.
