### ISSUE TITLE
Optimize and parallelize the chain validator

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2905]
**Issue summary**

Computing block state trees from scratch is inherently a sequential operation and cannot be parallelized. However, validating state trees that have already been computed can be done in parallel. This kind of validation is precisely what the `validate_chain` function does. As of writing this issue, the `validate_chain` function does not validate in parallel and has several other performance problems. In the past, the performance of the validator has not been a priority, but in the future, we would like to re-validate the entirety of the calibnet chain and large parts of the mainnet chain.

- [x] Modify `validate_chain` to use `N` threads for validation.
- [ ] Modify `validate_chain` to avoid all writes to the database. Validation only requires read access to the database.
- [ ] Make sure that no bottlenecks prevent using all available cores.
- [ ] Investigate whether `compute_tipset_state` or `apply_blocks` can be modified for better performance.

Note: Use the full snapshot for calibnet when testing. It contains all the state trees for the first 450000 epochs.

**Other information and links**

A full-snapshot for calibnet can be downloaded here:
https://forest-snapshots.fra1.cdn.digitaloceanspaces.com/debug/filecoin_full_calibnet_2023-04-07_450000.car

https://github.com/ChainSafe/forest/blob/9e6450c4496e0fdc0144a8ff7884d8f4b68af5b0/blockchain/state_manager/src/lib.rs#L1206

https://github.com/ChainSafe/forest/blob/9e6450c4496e0fdc0144a8ff7884d8f4b68af5b0/blockchain/state_manager/src/lib.rs#L736-L739

https://github.com/ChainSafe/forest/blob/9e6450c4496e0fdc0144a8ff7884d8f4b68af5b0/blockchain/state_manager/src/lib.rs#L360-L364

**Comment by lemmih** [comment]
Here's the command I use to re-validate 20k tipsets:
```
time cargo run --bin forest --release -- \
  --no-gc \
  --encrypt-keystore false \
  --chain calibnet \
  --import-snapshot filecoin_full_calibnet_2023-04-07_450000.car \
  --halt-after-import \
  --height=-20000 \
  --track-peak-rss \
  --skip-load true
```
It depends on the snapshot having been previously imported.

On my machine, it uses 1 core and takes 5m40s to re-validate all 20k tipsets. It would be nice if it used 16 cores and 20 seconds instead.

**Comment by lemmih** [comment]
@aatifsyed Should we close this issue and split the remaining tasks into separate issues?

**Comment by aatifsyed** [comment]
No, I think this is fine to remain open as a tracking issue

**Comment by lemmih** [comment]
I'll close this as done. If we have ideas for how to make it even faster, let's open those as separate issues.
