### ISSUE TITLE
Aatif's personal hitlist

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#2907]
**Issue summary**
- [x] #2957
- [ ] We don't use custom http clients
  See #2977 
- [x] #2984
- [ ] Our code is not spaghetti
- [ ] We've got a functional-core, imperative shell that we can test easily
- [ ] #2945 
- [ ] #2826 
- [ ] Our shellscripts are nicer
- [ ] Monolingual-ish codebase
- [ ] #2985

**Other information and links**

**Comment by LesnyRumcajs** [comment]
@aatifsyed This was not updated since June. Should we close this?

**Comment by LesnyRumcajs** [comment]
Stale, feel free to re-open if needed.
