### ISSUE TITLE
Fix API coverage computation

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#2926]
**Issue summary**

Adding a new Forest specific RPC endpoint will increase the overall method count found in `API_IMPLEMENTATION.md`.

The API coverage in this case should not increase. Only methods belonging to the Filecoin JSON-RPC API should be taken into account to avoid biasing this statistic.

I.e. after adding a new Forest endpoint:

before:
```
- Forest method count: 46
- Lotus method count: 173
- API coverage: 26.59%
```

after:
```
- Forest method count: 47
- Lotus method count: 173
- API coverage: 27.17%
```

**Other information and links**

https://github.com/ChainSafe/forest/blob/main/node/rpc-api/build.rs

**Comment by lemmih** [comment]
I think `API_IMPLEMENTATION.md` was removed. Can I close this, @elmattic?

**Comment by LesnyRumcajs** [comment]
Should it have been removed? I mean, if we want to Forest to work with the Lotus Miner, then such a tool seems like something rather useful. That being said, we had it incorrect anyway, as far as I remember the Lotus JSON describing its API was severely outdated.

**Comment by lemmih** [comment]
In the future, I'd rather have a manual count (together with actual testing) of our compatibility with the Lotus RPC.

**Comment by LesnyRumcajs** [comment]
There is no `API_IMPLEMENTATION.md` anymore.
