### ISSUE TITLE
Create Forest calibnet faucet

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2931]
**Issue summary**

There are a few calibration network FIL faucets, all of them running on Lotus. We could enrich the ecosystem by running our own. We have all the means (in the node) to do this.

Things to keep in mind:
1. While the calibration network tokens are not worth anything, we should ensure the faucet can't be drained. This means limits should be in place and some countermeasures (captchas or something like this?).
2. We need first to get some calibnet funds to run it.
3. There's a blocker bug that needs to get resolved first https://github.com/ChainSafe/forest/issues/2726

**Other information and links**
https://faucet.calibration.fildev.network/
https://faucet.triangleplatform.com/filecoin/calibration

**Comment by lerajk** [comment]
@lemmih Yes, I can get us calibration net FIL.

**Comment by lemmih** [comment]
This will be done as part of the Forest Explorer: https://github.com/ChainSafe/forest-explorer/

**Comment by lemmih** [comment]
Replaced by https://github.com/ChainSafe/forest-explorer/issues/32
