### ISSUE TITLE
Add Filecoin-specific validation to the snapshot validate command

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#2936]
**Issue summary**

For the `forest-cli snapshot validate` to be more helpful, we need to add some more checks to it. Coming from https://github.com/ChainSafe/forest-iac/issues/85#issuecomment-1578092941, the tool **cannot** detect when a snapshot is broken in a certain way that is detected when importing the snapshot to Forest. 
```
Error: Failed miserably while importing chain from snapshot /home/runner/.local/share/forest/snapshots/calibnet/forest_snapshot_calibnet_2023-05-15_height_561578.car: Serialization error for Cbor protocol: Mismatch { expect_major: 4, byte: 165 }
```
This means we already have all the logic necessary to check for these errors.

The end goal here is to make the `forest-cli snapshot validate` fail on a snapshot such as [this one](https://forest-snapshots.fra1.cdn.digitaloceanspaces.com/debug/forest_snapshot_calibnet_2023-06-05_height_621698.car.zst)

We shouldn't produce such snapshots in the first place, but knowing when a failure occurs will go a long way towards fixing this.

**Tasks**
- [x] Enhance the existing tool with more checks. This could be hidden behind a flag if they become significantly slower than the current ones.
- [x] Tests - tests should cover these checks (if not unit tests, consider making the faulty snapshot somehow smaller if possible).

**Other information and links**

**Comment by lemmih** [comment]
Yes, let's consider it done.
