### ISSUE TITLE
Forest logging

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#2946]
**Issue summary**
- [ ] We log to stderr, not stdout
- [ ] Logs don't race with UI (progress bars). See also #2928 
- [ ] Log collection story?

**Other information and links**

**Comment by aatifsyed** [comment]
#2864

**Comment by aatifsyed** [comment]
https://github.com/ChainSafe/forest/issues/2946

**Comment by aatifsyed** [comment]
https://github.com/ChainSafe/forest/pull/3430#discussion_r1316015850

**Comment by lemmih** [comment]
I believe the three action items have been resolved:
 - Logs are sent to the appropriate destination (stdout for the node, stderr for tools),
 - the UI elements no longer interfere with logging,
 - standard tools handle log collection.
