### ISSUE TITLE
Avoid network access when testing `param-fetch`

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#2956]
**Issue summary**

Two tests in Forest verify the download location for proof-parameter files. Unfortunately, they work by actually downloading the proof files, which can be slow. An alternative would be to implement a `--dry-run` flag that prints out where the files would end up if they were downloaded.

Acceptance criteria:
- [x] The tests still verify that the download folder is correctly computed.
- [x] The tests do not require internet access.

**Other information and links**

Slow param-fetch tests:
- `test_download_location_of_proof_parameter_files_default`
- `test_download_location_of_proof_parameter_files_env`

**Comment by ruseinov** [comment]
`--dry-run` could just print out the folder structure and files to be downloaded, for example.
