### ISSUE TITLE
Forest is a single crate, not a workspace of many crates

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#2957]
I'd like to make forest a single crate

## Benefits
- Easier to use codebase
- less hassle to manage dependencies
  - ~E.g just looking at the top of our Cargo.toml, we have three [three versions of aead](https://github.com/ChainSafe/forest/blob/5019758351a5c7223c359b3d010907f7d1188963/Cargo.lock#L20-L47) - I suspect we've got a few duplicate dependencies like this.~
- more optimization opportunities (within crate)
- makes further refactoring easier
  - better dead code detection. E.g as of https://github.com/ChainSafe/forest/pull/2973/commits/d2b598f249b49b3b2ca407caf79c531c7bc5f69b, there are 95 items which are used. That's fewer fields, methods, and cruft that we can actually remove.
  - Moving logic, sharing utils, code between modules is much easier
- shorter compile times (we don't need to do all that linking again)
- Can use more standard tools like `cargo-udeps` instead of ruby scripts

## Risks
- you'll have to remember to do `cargo check --all` in the interim
- Maybe longer compile times - some crates choose to break into sub-crates to parallelize compiles. If this happens, we should probably just write less code :) 

# How we do this incrementally
- Convert our workspace from a virtual manifest to a root package with a workspace section
- Work from the bottom of the dependency graph of our crates, interning each crate into the root package
  - This is mostly renames, which should be git-history friendly
- Handle the renames in the other crates
- Move tests
- Repeat

see https://github.com/ChainSafe/forest/compare/main...aatifsyed/one-crate-to-rule-them-all

**Comment by lemmih** [comment]
Great to have this as an issue. Such a reorganization would be a boon. I'm not convinced by all of the listed benefits, though. For example, some of our dependencies use the older `aead` when targeting wasm32-unknown-unknown. We have many duplicate dependencies (as witnessed by `cargo tree --duplicates`), but none of those will be fixed simply by using a single crate. I would also be surprised if there's a measurable effect on performance or a meaningful change in linking times. Nonetheless, the organizational benefits are more than worthwhile.

For context, Forest was made up of 49 crates last year and sits at 31 crates at present. Some crates should be pushed upstream, some should be spun out of the repository, and most should be merged into a single forest crate.

**Comment by LesnyRumcajs** [comment]
The only practical benefit of doing this, for me, is getting rid of circular dependencies when moving things around. We wouldn't have this issue with a single crate, and we could structure the modules however we deem appropriate. This may not necessarily be a good thing, though. 

Hypothetically it would also help with a feature flag creep, but we don't have that many flags and don't indent to use them extensively.

As for the downsides that matter, it would (and any large refactor, for that matter) make git blaming difficult unless those aren't exclusively renames/moves that are automatically followed. I managed to find countless regressions by just looking at recently changed lines.

All in all, it seems like a cosmetic change. I'm not necessarily in favour of this, but I'm okay with going ahead with it.

**Comment by aatifsyed** [comment]
As of https://github.com/ChainSafe/forest/pull/2973/commits/d2b598f249b49b3b2ca407caf79c531c7bc5f69b, most of the files are recognised as moved
