### ISSUE TITLE
Prune direct `fvm_shared` usage from Forest

### ISSUE THREAD

**Issue by jdjaustin** [ChainSafe/forest#2962]
**Issue summary**

Similar to issue #2713, we also need to remove all direct usage of `fvm_shared` and `fvm_shared3`.
- [x] Re-export all `fvm_shared` structs/constants in the Forest shim and use them in Forest. In the places where we use v2 of `fvm_shared`, we should switch to `fvm_shared3` or use a shim.
- [ ] Impose a strict rule of not using `fvm_shared` and `fvm_shared3` directly via `find_banned_deps.rb`. All in all, `fvm_shared` and `fvm_shared3` should be removed from the workspace (only exceptions are `forest_shim` and `forest_interpreter`).

**Other information and links**

**Comment by jdjaustin** [comment]
Blocked by #3195

**Comment by lemmih** [comment]
It's fine to not ban the imports. Closing as completed.
