### ISSUE TITLE
deprecate `lazy_static` use

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#2972]
nit: Perhaps it's time to replace `lazy_static!` with `once_cell::sync::Lazy`. It should be even easier once [this](https://github.com/ChainSafe/forest/pull/2970) is merged, then all it takes is `std::sync::Lazy`. 
Probably not a big thing, but with `OnceCell` now officially part of std - we could get rid of `lazy_static` dependency entirely, except for `no_std` context AFAIK. With time.

_Originally posted by @ruseinov in https://github.com/ChainSafe/forest/pull/2964#discussion_r1226948147_

**Comment by lemmih** [comment]
`OnceCell` isn't as convenient as `lazy_static`. I'm leaning towards closing this issue. What do you think, @ruseinov?

**Comment by aatifsyed** [comment]
I prefer `OnceCell` FWIW

**Comment by hanabi1224** [comment]
I like `OnceCell` because it's making into `std` and has been partially stablized

**Comment by lemmih** [comment]
`OnceCell` is not a drop-in replacement for `lazy_static`. It will require a significant number of changes. Are we all on the same page about what is involved?
