### ISSUE TITLE
Submodules need fixing up

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#2975]
**Issue summary**

We've got two submodules:
https://github.com/ChainSafe/forest/blob/5532ab90cd69f3dce313501d29d99c5ae99a0de6/.gitmodules#L1-L6

The first is tracked correctly: https://github.com/ChainSafe/forest/tree/5532ab90cd69f3dce313501d29d99c5ae99a0de6/tests/serialization_tests

The second is broken:
https://github.com/ChainSafe/forest/tree/5532ab90cd69f3dce313501d29d99c5ae99a0de6/ipld/tests

Also our makefile updates, not initializes the submodules. Theoretically a different set of vectors could be running in CI, which kind of defeats the point of using submodules
https://github.com/ChainSafe/forest/blob/5532ab90cd69f3dce313501d29d99c5ae99a0de6/Makefile#L129-L133

**Other information and links**

**Comment by LesnyRumcajs** [comment]
There are no submodules in Forest anymore.
