### ISSUE TITLE
Deprecate http_client in favour of reqwest.

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#2977]
I'd like to see our client deprecated and replaced with `reqwest`.
- We don't need to (re)-implement standard logic for redirects and well-known headers - see https://github.com/ChainSafe/forest/blob/5532ab90cd69f3dce313501d29d99c5ae99a0de6/utils/forest_utils/src/net/download.rs#L181, https://github.com/ChainSafe/forest/blob/5532ab90cd69f3dce313501d29d99c5ae99a0de6/utils/forest_utils/src/proofs_api/paramfetch.rs#L195, and https://github.com/ChainSafe/forest/blob/5532ab90cd69f3dce313501d29d99c5ae99a0de6/utils/forest_utils/src/net/download.rs#L170
- trivial to support e.g http2

_Originally posted by @aatifsyed in https://github.com/ChainSafe/forest/issues/2968#issuecomment-1588415980_

**Comment by hanabi1224** [comment]
For context, it was part of the effort of trimming large dependencies and speeding up the build to use `hyper` instead of `reqwest`, `reqwest` won't allow opting out large dependency `h2` until its next major release. See https://github.com/seanmonstar/reqwest/pull/1648

**Comment by lemmih** [comment]
Fixed in https://github.com/ChainSafe/forest/pull/3098
