### ISSUE TITLE
Don't use compilation features

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#2984]
We have features for:
- consensus algos
- allocators
- db selection

And we have to do a bunch of cross-feature testing https://github.com/ChainSafe/forest/blob/f9bb27c2900a8c5731019798053ceb6de162a6d8/Makefile#L92-L107 

[Features should also be additive](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) - ours are not. This is why we have to do all that cross-feature checking. We should be able to lint with `--all-features` and have it just work

Conditional compilation is often used for:
- Optional functionality in resource constrained environments (think `no_std`, or users who are particularly sensitive to binary sizes)
- Opt-in integration with other crates (`tokio`, `serde`, `arbitrary`)
- Platform-specific implementations (`unix` vs `windows`, pointer width)

We don't fit into any of these:
- Any user running forest clearly doesn't care about bundle size
- We're a CLI, not a library, don't need to optionally integrate with serde
- Any user probably doesn't have an allocator preference - we should just profile the best one and use that
- Any user probably doesn't have a db preference -  we should just profile the best one and use that
  - If they do, then we should just use traits, not have optional modules - that's the wrong abstraction
- We should just use traits for the cns stuff too

**Comment by lemmih** [comment]
List of compilation features:

- `rocksdb`
- `paritydb`
- `jemalloc`
- `mimalloc`
- `rustalloc`
- `insecure_post`
- `forest_fil_cns`
- `forest_deleg_cns`
- `instrumented_kernel`
- `lz4`
- `test_vectors`

**Comment by aatifsyed** [comment]
https://github.com/ChainSafe/forest/blob/6b3db608936f22db9df80ca2f8bd2d3131510568/src/db/rocks.rs#L38-L73

Ouch

**Comment by lemmih** [comment]
Remaining features:

- `instrumented_kernel`
- `insecure_post`
- `doctest-private`
- `benchmark-private`
- `rustalloc`
- `jemalloc`
- `mimalloc`

Let's get rid of `instrumented_kernel` and `insecure_post` and keep the rest.

**Comment by lemmih** [comment]
Done.
