### ISSUE TITLE
Runtime Syscalls

### ISSUE THREAD

**Issue by austinabell** [ChainSafe/forest#300]
**Task summary**

Syscalls for runtime to use in actors execution. Most are proof related. 

Most likely will interface https://github.com/filecoin-project/rust-filecoin-proofs-api for proof related things, but can probably use our encoding crate for the blake hash and our crypto crate for the verify signature.

Can ignore the TODO on the Syscalls type, as even if/when that switches, it will be simple to migrate over.

currently resides in `vm/runtime/src/lib.rs` but this is not a final location

**Specification reference**

- Spec is out of date, needs to match the interface used in specs-actors (I tried to match the interface as close to the go version when stubbing, but some types are likely to have to change slightly to match the interface with the rust proofs)

(listing syscalls for ref)
#301 
#302
#303
#304
#305
#306

**Other information and links**

**Comment by dutterbutter** [comment]
Closing as it seems it is completed.
