### ISSUE TITLE
Snapshot files are not valid zstd archives

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3006]
**Describe the bug**

**To Reproduce** Steps to reproduce the behavior:

1. Download a Forest snapshot: `forest-cli --chain calibnet snapshot fetch`
2. Verify its integrity: `zstd --test forest_snapshot_calibnet_2023-06-19_height_660943.car.zst` (this fails)
3. Forest thinks everything is okay: `forest-cli --chain calibnet snapshot validate forest_snapshot_calibnet_2023-06-19_height_660943.car.zst`

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```bash
  $ zstd --test forest_snapshot_calibnet_2023-06-19_height_660943.car.zst 
eight_660943.car.zst : 2190 MB...     eight_660943.car.zst : Read error (39) : premature end

$ forest-cli --chain calibnet snapshot validate forest_snapshot_calibnet_2023-06-19_height_660943.car.zst 
✔ This will result in using approximately 1386 MB of data. Proceed? · yes
2023-06-19T06:56:25.927370Z  INFO forest_filecoin::genesis: Initialized genesis: BlockHeader: Cid(bafy2bzacecyaggy24wol5ruvs6qm73gjibs2l2iyhcqmvi7r7a4ph7zx3yqd4)    
2023-06-19T06:56:25.929039Z  INFO forest_filecoin::utils::net::download: Loading forest_snapshot_calibnet_2023-06-19_height_660943.car.zst, is_zstd_compressed: true    
280.72 MB/s 0s 2023-06-19T06:56:34.867571Z  INFO forest_filecoin::utils::db: Buffered write completed: total entries: 2577964, total size: 2.58GB, took: 8s    
Snapshot is valid

  ```
</details>

**Expected behaviour**

The `zst` snapshot files should not prematurely end.

**Screenshots**

**Environment (please complete the following information):**

- OS: Linux
- Rust version(e.g. `rustc --version`): default toolchain
- Branch/commit: latest `main`

**Other information and links**

**Comment by ruseinov** [comment]
@lemmih As far as I understand this issue entails:

1. Making sure that the downloaded snapshots are correct. 
2. Snapshot validation should fail given a corrupt snapshot.
