### ISSUE TITLE
[Fix] Regenerate snapshots.

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3019]
Now that [this](https://github.com/ChainSafe/forest/issues/3006) is done we'll need to regenerate potentially corrupt snapshots.

The best way to do it is to wait for [that](https://github.com/ChainSafe/forest/issues/2999).

Another way is to use the corrupt ones and repackage them, but it could result in inconsistent data, which eliminates the purpose of regenerating those in the first place.

**Comment by LesnyRumcajs** [comment]
Should this be closed @ruseinov @lemmih ?

**Comment by lemmih** [comment]
Yes. The affected snapshots have been deleted.
