### ISSUE TITLE
Export snapshots with uncompressed size in header.

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3023]
Now that #3005 has been fixed we need to make sure the snapshots actually contain the metadata needed to extract the size. 
That might require a different library or a contribution to the one we currently use.

**Comment by ruseinov** [comment]
> I've not verified but [this `content_size_flag` parameter](https://docs.rs/async-compression/latest/async_compression/zstd/struct.CParameter.html#method.content_size_flag) looks relevant

It’s supposedly true by default, but our snapshots don’t include the frame size for some reason.

**Comment by lemmih** [comment]
I don't think this is possible when compressing a stream of unknown size.

**Comment by lemmih** [comment]
Closing.
