### ISSUE TITLE
CI is dreamy

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#3059]
Issues with our current CI
- could be more parallel
- not very auditable. For #3021 I had to manually see what was taking so long by looking at the log files. I should be able to just see which specific steps are taking ages. E.g tests vs compilation
- spammy. We should quiet logs where appropriate
- build e.g `release` multiple times. We should build it once and pass the artifact along
- I don't find out everything that's wrong with my mr at once, I need to e.g fix licensing _then_ fix spelling, which is a massive time sink. I want to know everything wrong at once.

Here's a sketch of what I want our CI to look like - it should reflect the real dependency graph for jobs.

```mermaid
flowchart LR
    commit
    build-dev
    clippy
    hunspell
    check-license
    build-release
    test-dev
    test-release
    build-docker
    push-docker

    commit --> build-dev --> test-dev
    build-dev --> clippy
    build-dev --> hunspell
    commit --> check-license
    commit --> build-release --> test-release
    build-release --> build-docker --> push-docker
  ```

Note that `build-docker` should just use the artifacts from `build-release`, and we can probably disable it except on main, so we don't hit rate limits

Other considerations:
- #2984 
- How does cross-compilation work in the above regime?
- #2826

**Comment by LesnyRumcajs** [comment]
@aatifsyed Docker build should **not** use the artefacts from GH builds. The image we offer is supposed to work on `arm64` as well.

**Comment by LesnyRumcajs** [comment]
If anything, it could be the other way around.

**Comment by aatifsyed** [comment]
I wonder if the following is possible:

```mermaid
flowchart LR
    %% where omitted, target is x86-64-linux-unknown-linux-gnu
    commit
    clippy
    build-dev
    build-release
    build-release-aarch64-apple-darwin
    build-release-x86_64-apple-darwin
    spellcheck
    test-dev
    test-release
    license
    docker
    udeps

    commit --> license
    commit --> spellcheck
    commit --> udeps
    commit --> clippy --> build-dev --> test-dev
    build-release --> test-release
    commit --> build-release --> docker
    commit --> build-release-aarch64-apple-darwin --> docker
    commit --> build-release-x86_64-apple-darwin --> docker
```

where omitted, target is x86-64-linux-unknown-linux-gnu

Also, does using `sccache` mean that the `target` directory will NOT need to be passed forward between e.g `build-dev` and `test-dev`?

**Comment by aatifsyed** [comment]
We could use https://github.com/cross-rs/cross for the cross compilation, though we'd still need a macos runner for legal reasons

**Comment by lemmih** [comment]
Since this issue was opened, the CI has been revamped. Many of the concerns have been addressed, but not all of them. If they're still relevant, open a new issue (or rewrite and reopen this one).
