### ISSUE TITLE
[Enhancement] Errors.

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3066]
Currently we are using convenient helpers, like `anyhow`, often resorting to strings to distinguish between different errors. This is suboptimal in the long-term, even though it saves us quite a bit of pain during development.

The idea is to well-defined statically-typed errors for every flavour that we need to distinguish. It's way easier to test, serialize and reason about. 

It's quite a big task to undertake, would be nice to hear what everybody has to say about this first.

**Comment by lemmih** [comment]
Do we ever inspect the `anyhow` errors?

**Comment by ruseinov** [comment]
moved to https://github.com/ChainSafe/forest/discussions/3069
