### ISSUE TITLE
Segregate blockstore reads and writes

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#3079]
**Issue summary**

```rust
trait ReadableStore {
    fn get(&self, ...);
}

trait BlockStore: ReadableBlockStore {
    fn put(&mut self, ...);
}
```

This would unlock lots of happiness for being an archival node :)

https://github.com/ChainSafe/forest/issues/3074

Also I think we're missing tricks by having all the methods above take `&self`

**Comment by lemmih** [comment]
The `Blockstore` trait is defined outside of Forest. We can gain little by defining our own smaller traits.
