### ISSUE TITLE
Remove local Either implementation from the repo. Decide which 3rd-party implementation to use.

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3083]
As mentioned in https://github.com/ChainSafe/forest/issues/3022#issuecomment-1609471820_, we'd like to move away from the local `Either` implementation in favour of that in `tokio` or other alternatives where we won't need `Either` at all.

Some of those could be replaced by `Box`'d types as appropriate. 
            
I've looked into it briefly, this is what would be required:
- [x] Migrating from local `Either` to `futures_util::future::Either`; done in https://github.com/ChainSafe/forest/pull/3088
- [x] Removing local `Either`; done in https://github.com/ChainSafe/forest/pull/3088
- [ ] Taking care of `AsyncWriterWithChecksum`, either finding a viable tokio alternative that's already out there, or perhaps rewriting this to implement tokio traits. After a quick search I couldn't find anything suitable as a drop-in replacement. Otherwise there's too much `compat` going on, because we are already using `tokio::Either` within the project, so it feels strange to use `futures::Either` as well. 
- [ ] Using compat layer to interact with `CarHeader` defined in `fvm_ipld_car` lib. 
- [ ] Doing this at the same time: https://github.com/ChainSafe/forest/issues/3084. Note that this is tricky, because once we switch to tokio version of ZstdEncoder - this produces a bunch of compatibility issues with both `futures_util::future::Either` and `AsyncWriterWithChecksum`.

I think this needs further discussion followed by decision-making.

**Comment by lemmih** [comment]
The local `Either` was removed, and `AsyncWriterWithChecksum` looks fine. Closing this issue.
