### ISSUE TITLE
Known state-root mismatches

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3100]
**Issue summary**

Forest diverges from Lotus at these epochs:

#### Mainnet

- ~2383686~
- ~2987371~
- ~2987388~
- ~2988985~
- ~2992676~
- ~2996508~
- ~2997616~

#### Calibnet

- ~16802~

**Other information and links**

Snapshots:
- https://forest-snapshots.fra1.cdn.digitaloceanspaces.com/historical/historical-exports_snapshot_2381760_2384650_1672316964.car.zst
- https://forest-snapshots.fra1.cdn.digitaloceanspaces.com/debug/forest_snapshot_mainnet_2023-06-28_height_2988801.car.zst
- https://forest-snapshots.fra1.cdn.digitaloceanspaces.com/debug/lotus_full_calibnet-17000.car.zst

**Comment by elmattic** [comment]
Hmm `2383686` is only 6 epochs after the `Shark` upgrade.

**Comment by lemmih** [comment]
Re-validated all of calibnet (in only 20 minutes, thank you Aatif). After successfully validating 676159 epochs, a mismatch appears at epoch 16802 (only 2 epochs after the Shark network upgrade).

**Comment by LesnyRumcajs** [comment]
The mismatch at 2997616 should be fixed with corrected tipset getter method. https://github.com/ChainSafe/forest/pull/3122
