### ISSUE TITLE
Forest should be performant by design

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#3102]
**Issue summary**

I think we're slow by design at the moment:
- lots of `DB: Blockstore + Send + Sync + 'static` bounds that evidence our history of being a Go port, or the FVM components generally being Go ports
- lots of going through indirect objects due to the above. E.g operating on chainstore instead of DB when loading car files
- `Arc`s and `dyn`s that shouldn't be necessary
- We don't use best practices for performance, eg. streaming, and our buffered write is a mess/should be removed

We can fix that!
~E.g here's car reading being 10x faster than reference:~
![image](https://github.com/ChainSafe/forest/assets/38045910/2b2ebdfc-2ff0-4308-b7a2-657868cbb6b3)
```
loading_car/using_car_reader//home/aatif/chainsafe/snapshots/567120_2023_05_17T16_13_00Z.car
                        time:   [13.607 s 14.064 s 14.485 s]
loading_car/using_tokio_codec//home/aatif/chainsafe/snapshots/567120_2023_05_17T16_13_00Z.car
                        time:   [887.75 ms 918.27 ms 952.66 ms]
```
https://github.com/ChainSafe/forest/commit/fa1126a9596eed07fe0aef951b7225daf4626a8e

Wrong: we could probably achieve a 25% speedup: https://github.com/ChainSafe/forest/issues/3102#issuecomment-1616826711

What does this look like?
- [x] #2676 
- [ ] Forest should be _composable_
- [ ] Stream cars where appropriate, fixup our bufferedwrite hacks. See also https://github.com/ChainSafe/forest/tree/aatifsyed/stream-cars
- [ ] Have criterion benchmarks run in CI, and properly keep track of perf
- ...

**Other information and links**

**Comment by ruseinov** [comment]
FYI: streaming cars is partly implemented here: https://github.com/ChainSafe/forest/pull/3090
That also goes for buffered writes elimination. Perhaps worth taking a look. 

The other buffered write is happening in the Gc, for which there is a [ticket](https://github.com/ChainSafe/forest/issues/3072)  that’s in the pipeline. That also takes care of the other part of streaming car and the other buffered write.

The rest is definitely something that needs to be taken care of. I’m hoping we could clean some of that up as part of GC work to see where we can get.

**Comment by lemmih** [comment]
The bulk of the performance difference goes away if we compare apples to apples: By default, the `CarReader` does validation (ie it checks that the hash of the value matches the CID), and `FramedRead` is buffered, whereas `CarReader` is not.

That said, `CarReader` is still wildly inefficient and needlessly copies the input several times. Replacing it would be a big performance win.

**Comment by ruseinov** [comment]
Fixing up `CarReader` would be a fun task for sure!

**Comment by aatifsyed** [comment]
> if we compare apples to apples

Missed this, thanks David!

![image](https://github.com/ChainSafe/forest/assets/38045910/821200ae-ca37-472e-973a-4290c33d8c8a)

Here's a comparison with no checking - we could load about 25% quicker (1.1329 / 1.4717)
I think we should be able to realise that speedup, and then do the checking ourselves, so we decouple our IO and compute-bound work

**Comment by lemmih** [comment]
> Here's a comparison with no checking - we could load about 25% quicker (1.1329 / 1.4717)

Huge performance win. On my laptop, the win is even more significant.

> I think we should be able to realise that speedup, and then do the checking ourselves, so we decouple our IO and compute-bound work

Indeed. The code would be more efficient and easier to understand at the same time.

**Comment by LesnyRumcajs** [comment]
I want to note a downside of striving away from Lotus design. I'm not saying we shouldn't do it; I'm all for it - I'd just like for us to understand the risks. 

In general, we are not Filecoin experts compared to most engineers at the FVM and Lotus. This forces us to often do "programming by analogy", that is to say, looking up the Go reference and implementing it in Rust. The massive work that @hanabi1224 did for the NV17 state migration would be significantly more complicated if the implementations were very different from each other. In an ideal world, we would not look at the Lotus code at all and spend time intensely studying the FIPs. I'm not sure we have the capacity for this, though.

Secondly, finding any mismatches is easier when you can change the `snake_case` method call in Forest and find it as `PascalCase` in Lotus.

When changing the design, we should at least leave a _handle_ for the part of Lotus that does similar things (if there is such a counterpart).

**Comment by lemmih** [comment]
Some action items are done, and the rest aren't directly actionable. Closing.
