### ISSUE TITLE
Implement `forest-cli snapshot compute-state`

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3124]
**Issue summary**

For debugging, it would help if we had something similar to `lotus state compute-state`. Since this computation doesn't rely on connecting to the p2p network, let's implement it directly operating on snapshot files.

Actions:
- [x] Set up the VM using a snapshot file.
- [x] Implement the equivalent of the `--vm-height` and `--json` flags.
- [x] Verify that the JSON output is roughly comparable with Lotus'.

**Other information and links**

https://github.com/filecoin-project/lotus/blob/4240990c6c4158651b954ca770535b1d7ba5874b/cli/state.go#L1027

**Comment by ruseinov** [comment]
Related to: https://github.com/ChainSafe/forest/issues/3111

**Comment by lemmih** [comment]
Duplicate: https://github.com/ChainSafe/forest/issues/1838

**Comment by aatifsyed** [comment]
@lemmih  is this closed after #3430 ?

**Comment by lemmih** [comment]
Yes.
