### ISSUE TITLE
`forest-cli archive export --epoch=X`

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3159]
A Forest node can generate up-to-date snapshot files. However, we often want to take large snapshots and trim them to a specific epoch. This can be done entirely without network access.

The `forest-cli archive export` command takes a snapshot file as input and yields a smaller snapshot file as output. For example, the input snapshot might cover epochs 1 to 5000, and the output snapshot could cover epochs 1000 to 2000.

Subtasks:

- [x] Take CAR file as input,
- [x] Index CAR file using car-backed Blockstore,
- [x] Get `recent-roots` and `epoch` from cli flags,
- [x] Use [`export`](https://github.com/ChainSafe/forest/blob/4f0d75f472574fd3de56184164c7841aa826b8ec/src/chain/store/chain_store.rs#L528) function to generate snapshot data,
- [x] Compress with zst.

Error handling:
- [x] `recent-roots` too low (less than `chain_finality`),
- [x] `recent-roots` too high (greater than available roots),
- [x] `epoch` not in CAR input file,
- [x] input file may be malformed or corrupted.

# Export function

https://github.com/ChainSafe/forest/blob/4f0d75f472574fd3de56184164c7841aa826b8ec/src/chain/store/chain_store.rs#L528-L535

**Comment by ruseinov** [comment]
@lemmih Do we also want the checksum here?

**Comment by lemmih** [comment]
> @lemmih Do we also want the checksum here?

We can leave out the checksum for now.

**Comment by ruseinov** [comment]
One more question: do we really want to call a param `recent-roots`? I would probably do something like
`epoch-from`, `epoch-to` and make sure that `epoch-from is at least `chain_finality` (defaulting to it too).

We could come up with even better naming perhaps
`--epoch` and `--depth`.

**Comment by lemmih** [comment]
> One more question: do we really want to call a param `recent-roots`? I would probably do something like `epoch-from`, `epoch-to` and make sure that `epoch-from is at least `chain_finality` (defaulting to it too).
> 
> We could come up with even better naming perhaps `--epoch` and `--depth`.

`--epoch` and `--depth` looks good.
