### ISSUE TITLE
`forest-cli snapshot export` bugs up the terminal

### ISSUE THREAD

**Issue by jdjaustin** [ChainSafe/forest#3171]
**Describe the bug**

**To Reproduce** Steps to reproduce the behavior:

1. Run forest
2. Run `forest-cli snapshot export` in another terminal window
3. Upon successful export, the export path is displayed in the format `Snapshot located at <PATH>`. In MacOS, the terminal displays a garbage `%` at the end of this path and properly displays the terminal prompt in a new line. In Ubuntu (in a droplet's GUI with a fresh install of both rustup and Forest), the export path collides with the new terminal prompt (which is not displayed on a new line). In both OSes, resizing the terminal window after export results in garbage duplication of characters. While not certain that this is related to the progress bar, resizing the terminal window during snapshot export also results in both duplication of the progress bar and random garbage (duplicated characters) displayed in the terminal.

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details>

**Expected behaviour**

Snapshot export completes successfully, reports status with export path, and restores terminal prompt in a new line with no buggy behavior.

**Screenshots**

**Environment (please complete the following information):**

- OS:
- Rust version(e.g. `rustc --version`)
- Branch/commit

**Other information and links**

<img width="701" alt="Screen Shot 2023-07-11 at 6 37 30 PM" src="https://github.com/ChainSafe/forest/assets/11778588/7919e65a-6131-4d89-b042-e438db9dae24">
<img width="473" alt="Screen Shot 2023-07-11 at 6 37 04 PM" src="https://github.com/ChainSafe/forest/assets/11778588/0c4209e0-96a0-4264-ac78-0386d8ef6302">

**Comment by lemmih** [comment]
Relevant code:

https://github.com/ChainSafe/forest/blob/caac08f7f83c229193fed72c3ba9386fb9982256/src/cli/subcommands/snapshot_cmd.rs#L127-L130

The naming is somewhat confusing but `finish_println` does _not_ print a newline at the end of the string. It prints a newline _before_ the string. We either add a newline at the end or switch to `indicatif`. @jdjaustin, how about you add the newline?

**Comment by jdjaustin** [comment]
Adding the newline resolved the issue with the garbled output after snapshot export, but the issue with resizing the window while displaying a progress bar remained, and using `indicatif` did not fix that either. However, this issue also occurs during snapshot import in both Forest and Lotus, and it appears to be a fairly commonly reported problem among other terminal apps, so I think we can close this issue with the newline fix.

**Comment by lemmih** [comment]
> Adding the newline resolved the issue with the garbled output after snapshot export, but the issue with resizing the window while displaying a progress bar remained, and using `indicatif` did not fix that either. However, this issue also occurs during snapshot import in both Forest and Lotus, and it appears to be a fairly commonly reported problem among other terminal apps, so I think we can close this issue with the newline fix.

Right, that's just how terminals are.
