### ISSUE TITLE
Cruft in `export`

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3173]
**Issue summary**

The `export` function takes `recent_roots: ChainEpoch` argument. This argument has the wrong type. It's not a `ChainEpoch`, it's an epoch delta (the difference between two epochs). This needs to be changed to `i64`.

The `export` function keeps track of the number of keys in the Forest database. This does not work as expected when `export` is used without the Forest database. This tracking code does not belong in `export` and should be moved into forest-daemon-specific code.

- [x] Fix type error in `export`. fixed in https://github.com/ChainSafe/forest/pull/3169
- [ ] Fix tracking code in `export`. seems irrelevant as of https://github.com/ChainSafe/forest/pull/3175

**Other information and links**

**Comment by ruseinov** [comment]
Closing this as the rest of this issue seems irrelevant after implementing chain streams and ditching the progress tracking altogether.
