### ISSUE TITLE
Investigate dynamic defaults for clap

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3182]
**Issue summary**

Here's one place it could be useful, I'm sure there are more: https://github.com/ChainSafe/forest/blob/697358090b755fa1343e2e3f16bc0cfa16d3ef4f/src/cli/subcommands/archive_cmd.rs#L82.

**Other information and links**

**Comment by aatifsyed** [comment]
Do you want to display the default? May be tricky, dynamic completion for clap is a long standing project.
I would just `unwrap_or(get_default_depth(ctx))`

**Comment by lemmih** [comment]
I looked into this and found no apparent ways to move forward. Closing.
