### ISSUE TITLE
Implement optimized vector of CIDs

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3232]
**Issue summary**

We have optimized versions of `HashSet<Cid>` and `HashMap<Cid, _>`. They use the [Struct of Arrays](https://en.wikipedia.org/wiki/AoS_and_SoA) technique to remove fields the CIDs have in common. We should do the same for vectors of cids.

- [x] Implement `CidVec`.
- [x] Use `CidVec` in `TipsetKeys`.
- [x] Ask in channel about what to do with `TipsetKeys::cids`.
- [x] Write quickcheck properties to make sure `CidVec` is identical to `Vec<Cid>`.

**Other information and links**

**Comment by jdjaustin** [comment]
Closed by #3275
