### ISSUE TITLE
Make the `genesis_cid` field in `ChainConfig` an `Option<Cid>`

### ISSUE THREAD

**Issue by jdjaustin** [ChainSafe/forest#3247]
How about we go ahead and make the `genesis_cid` field in the `ChainConfig` an `Option<Cid>`? The more strongly typed the codebase is, the better.

_Originally posted by @LesnyRumcajs in https://github.com/ChainSafe/forest/pull/3243#discussion_r1269119289_

**Comment by lemmih** [comment]
I got there before you, @jdjaustin.
