### ISSUE TITLE
use `CidHashMap` in the ForestCAR.zst encoder

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3287]
**Issue summary**

The `.forest.car.zst` encoder uses a `HashMap<Cid, u64>`. This map should be replaced with `CidHashMap`, which uses less memory. Memory usage when compressing a snapshot should be measured before and after the change.

Acceptance criteria:
- [ ] Add missing methods (if any) to `CidHashMap`
- [ ] Replace `HashMap<Cid, V>` with `CidHashMap<V>` in `car/plain.rs`
- [ ] Measure change in peak memory use when validating an uncompressed calibnet and mainnet snapshot. See `/usr/bin/time -v forest-cli snapshot compress {snapshot}.car.zst`

**Other information and links**

https://github.com/ChainSafe/forest/blob/6dbd776c2e9f17323e2327a2523760e7f2130518/src/db/car/forest.rs#L214

**Comment by jdjaustin** [comment]
Closing per comment in PR #3304
