### ISSUE TITLE
Walking the graph is slow

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3314]
**Issue summary**

Exporting a snapshot is enough to be a problem. On my machine, I can export at ~25MiB/s. I believe the primary bottleneck is the graph traversal code.

Exporting a snapshot involves two parts:
- A depth-first search of the graph producing a list of blocks.
- Incrementally encoding the blocks into many z-frames.

The second part can be benchmarked by running `forest-cli snapshot compress`. On my machine, it runs at ~74 MiB/s. Benchmarking the traversal code is a bit more difficult, but it clocks in at ~65 MiB/s for me.

Let's try and make everything faster and more parallel.

Acceptance criteria:
- [x] DFS graph walking should produce at least 100 MiB/s of data.
- [ ] The ForestCAR.zst encoder should produce at least 100 MiB/s of data (if given sufficient input).
- [x] Unordered parallel graph traversal implementation. 

**Other information and links**

Useful commands:
- Download mainnet snapshot: `forest-cli snapshot fetch`
- Export snapshot `forest-cli archive export {INPUT.forest.car.zst} --output-path out.forest.car.zst`
- Compressing a snapshot `forest-cli snapshot compress {INPUT.forest.car.zst} --output out.forest.car.zst`
- Benchmark snapshot compression `cargo forest-tool benchmark forest-encoding {INPUT.forest.car.zst}`

**Comment by lemmih** [comment]
See also `forest-tool benchmark`.

**Comment by ruseinov** [comment]
We have the relevant benchmarks here: https://github.com/ChainSafe/forest/pull/3318 . Could be fixed as part of that PR.

**Comment by lemmih** [comment]
Mostly done. No more low-hanging fruit.
