### ISSUE TITLE
Better support for random file access

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3321]
**Issue summary**

Consider using [positioned-io](https://crates.io/crates/positioned-io) in the CAR-back block stores. Benefits:

- FADV_RANDOM on Linux and good performance on Windows.
- Reading doesn't require ownership of the `File` handle. This means multiple threads can read from the same handle.

**Other information and links**

**Comment by ruseinov** [comment]
Would be interested in taking this on later to get familiar with car-backed store.
