### ISSUE TITLE
Assorted minor tasks

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3322]
**Issue summary**

- [x] `forest-cli archive export` doesn't warn before overwriting the `output-path`. We should prompt if the output path already exist and there should be a `--force` flag to suppress the prompt.
- [ ] `forest-cli archive export` uses `--output-path` but `forest-cli snapshot export` uses just `-o` and `forest-cli snapshot compress` uses `--output`. We should be consistent and always use the same flag name.
- [x] Rename `forest-cli db clean` to `db destroy`.

**Other information and links**

**Comment by jdjaustin** [comment]
Third task completed in PR #3355
