### ISSUE TITLE
`src/mod.rs` is weird and should probably be removed

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#3324]
https://github.com/ChainSafe/forest/blob/77d6b2b128d73900b0162e3f573ff8d63e6324b3/src/mod.rs#L4

Which isn't true - it's only referenced in the build script. It should move out of src.

**Comment by hanabi1224** [comment]
@aatifsyed It is used in `test_load_actor_bundles` and I did plan to move some shared CAR concat util functions into it : )

**Comment by aatifsyed** [comment]
https://github.com/ChainSafe/forest/blob/77d6b2b128d73900b0162e3f573ff8d63e6324b3/src/lib.rs#L53-L55

!

**Comment by hanabi1224** [comment]
https://github.com/ChainSafe/forest/pull/3325
