### ISSUE TITLE
Several contributions to positioned-io library.

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3341]
There are several things that belong to the `positioned-io` crate as opposed to forest:

* https://github.com/ChainSafe/forest/blob/b54c2e39273517782a9e0f8d8744aa23400831d7/src/utils/io/random_access.rs#L5
* https://github.com/ChainSafe/forest/blob/3f960de479c9ce33eda94febd5190c38898811e5/src/db/car/mod.rs#L24-L40

Let's make sure this gets contributed upstream. 

Sadly, it seems that the repository is no longer maintained. If they don't react to our contributions - we could fork it and continue the development there.

**Comment by lemmih** [comment]
Forking is rather extreme. These small improvements can easily live in Forest.

**Comment by ruseinov** [comment]
> Forking is rather extreme. These small improvements can easily live in Forest.

The problem with this is that we can't have truly generic implementations for `Box` stuff, so we'd have to duplicate those each time we need to introduce more of those. Let's see if we can push the contributions upstream.

**Comment by ruseinov** [comment]
This is done in: https://github.com/vasi/positioned-io/pull/21 and https://github.com/vasi/positioned-io/pull/20

**Comment by ruseinov** [comment]
The contributions have been accepted and released. I'll make sure to integrate those and raise a PR early next week.
