### ISSUE TITLE
Seed CloudFlare with calibnet snapshots

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3346]
**Issue summary**

For testing and demonstration purposes, it would be nice to have a full-archival copy of the calibnet graph. This means having `lite` snapshots (i.e., snapshots with 2k state-roots, 2k messages,  and all block headers since genesis) and `diff` snapshots (snapshots that only contain new key-value pairs).

Lite snapshots should:

- be generated every 30k epochs,
- contain state-roots+messages for the 2k most recent epochs,
- be tagged with a date derived from `(genesis_timestamp + epoch * EPOCH_DURATION_SECONDS)`,
- ignore null tipsets (e.g., if tipset 30000 is null, the snapshot should still be named `height_30000` rather than height_29999`).

The genesis timestamp of calibnet is `1667326380`, which is 2022-11-01. Add `30k*EPOCH_DURATION_SECONDS` and you get 2022-11-12. So, the lite snapshot should be named like this: 

- `forest_snapshot_calibnet_2022-11-01_height_0.forest.car.zst`,
- `forest_snapshot_calibnet_2022-11-12_height_30000.forest.car.zst`,
- `forest_snapshot_calibnet_2022-11-22_height_60000.forest.car.zst`,
- etc.

There should be 10 diff snapshots between every lite snapshot, each covering 3k epochs. Each diff snapshot has a start epoch and an end epoch, and may not contain keys reachable in the 2k epoch preceding the start epoch. Naming conversion is like this:

- `forest_diff_calibnet_2022-11-02_height_0+3000.forest.car.zst`,
- `forest_diff_calibnet_2022-11-03_height_3000+3000.forest.car.zst`,
- etc.

The snapshots should be uploaded to `forest-archive/calibnet/lite/` and `forest-archive/calibnet/diff/`. Keys for CloudFlare R2 access is in 1password.

A full calibnet snapshot can be found here: https://forest-snapshots.fra1.cdn.digitaloceanspaces.com/debug/forest_snapshot_calibnet_2023-08-06_height_800000.full.forest.car.zst

Generating lite snapshots can be done with: `forest-cli archive export --epoch {end_epoch} --depth 2000`

Generating diff snapshots can be done with: `forest-cli archive export --epoch {end_epoch} --depth 3000 --diff {end_epoch-3000} -o forest_diff_calibnet_height_{end_epoch-3000}+3000.forest.car.zst`

**Other information and links**

**Comment by LesnyRumcajs** [comment]
Uploaded.
