### ISSUE TITLE
[Bug] Random failure in `ipld_roundtrip` test

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#3383]
**Describe the bug**

Failure log on CI: https://github.com/ChainSafe/forest/actions/runs/5877726416/job/15938386821?pr=3382#step:9:1835

**To Reproduce** Steps to reproduce the behavior:

- `cargo test --lib -- --nocapture --test ipld_roundtrip`

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details>

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**

- OS:
- Rust version(e.g. `rustc --version`)
- Branch/commit

**Other information and links**

**Comment by lemmih** [comment]
I can't replicate this, and the logs have expired.
