### ISSUE TITLE
Tackle roundtrip ser/de issues related to arbitrary Float and Int

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3395]
Follow-up: create an issue to tackle roundtrip ser/de issues mentioned here: https://github.com/ChainSafe/forest/blob/ec7e65bace51b4de7a3d43f466d983ac5a3f28c8/src/utils/encoding/cid_de_cbor.rs#L218-L228

_Originally posted by @ruseinov in https://github.com/ChainSafe/forest/issues/3379#issuecomment-1682457050_
            
https://github.com/ChainSafe/forest/blob/ec7e65bace51b4de7a3d43f466d983ac5a3f28c8/src/utils/encoding/cid_de_cbor.rs#L218-L228

**Comment by lemmih** [comment]
@ruseinov Is this done?

**Comment by ruseinov** [comment]
> @ruseinov Is this done?

It's done, but it hasn't been released yet, unfortunately. I'll poke the guys. 
Here's the issue: https://github.com/ipld/serde_ipld_dagcbor/issues/16
