### ISSUE TITLE
Consider redesigning FVM tracing

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#3405]
We have a perfectly good tracing framework: [`tracing`](https://docs.rs/tracing/latest/tracing/)

https://github.com/ChainSafe/forest/pull/3161 added `enable_tracing` parameters to a few functions, which in the limit will pollute the codebase.

Can we redesign these away?

**Comment by ruseinov** [comment]
Perhaps just a global config parameter or an env variable
