### ISSUE TITLE
Calculate mining reward 

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/forest#343]
**Task summary**

Part of the process of computing the tipset state involves deducting/adding a mining reward to the respected actor.

The calculation of this mining reward can be viewed [here.](https://github.com/filecoin-project/lotus/blob/master/chain/vm/vm.go#L731)

**Specification reference**

- There is a section in the spec referring to block rewards, however it seems incomplete so it may be more useful to reference existing implementations instead. 
- [Block Rewards](https://filecoin-project.github.io/specs/#block-rewards)

**Other information and links**

**Comment by austinabell** [comment]
This issue is probably not doable, the rewards should all be handled by the reward actor and logic should reside there, the master reference is out of date for where the clients are going
