### ISSUE TITLE
`importing_bad_snapshot_should_fail` test is timing out intermittently

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#3449]
**Issue summary**

`importing_bad_snapshot_should_fail` test timed out a few times recently.

It also happened to me while running tests locally (macOS).

**Acceptance Criteria**

This test should not be flaky at all.

**Other information and links**

See actions:
 - https://github.com/ChainSafe/forest/actions/runs/6039372267/job/16387863565
 - https://github.com/ChainSafe/forest/actions/runs/6051148330/job/16421975063

**Comment by lemmih** [comment]
Test disabled in https://github.com/ChainSafe/forest/pull/3451

**Comment by LesnyRumcajs** [comment]
Let's fix it or remove it altogether.
