### ISSUE TITLE
Upgrade `fvm_ipld_bitfield` crate

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#3478]
**Issue summary**

Since `fvm_ipld_bitfield::BitField` is used in public APIs of `fil_actor_*` crates, it needs to be upgraded in `fil_actor_*`, however, one of the CI jobs of https://github.com/ChainSafe/fil-actor-states will be broken by the upgrade, which builds `forest` with the PR branch.

Proposal:
- [ ] re-export `fvm_ipld_bitfield`(and maybe `fvm_ipld_hamt`) from `fil_actors_shared`
- [ ] make `fvm_ipld_bitfield`(and maybe `fvm_ipld_hamt`) an indirect dependency of `forest` by using the re-export(s)
- [ ] upgrade `fvm_ipld_bitfield`(and maybe `fvm_ipld_hamt`) in https://github.com/ChainSafe/fil-actor-states

**Other information and links**

**Comment by ruseinov** [comment]
Sounds reasonable to me.
