### ISSUE TITLE
Research: flume vs kanal

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3484]
**Issue summary**

We've implemented `UnorederedChainStream` using kanal and it was showing better performance with `kanal` when benchmarked. Let's move away from `flume` to `kanal` making sure every feature we transition is properly benchmarked first.

**Other information and links**

**Comment by LesnyRumcajs** [comment]
I'd be careful with using `kanal`. While I understand that it fares well performance-wise, it's less widely used (and, in effect, is not as well-tested) as the alternative. It has fewer contributors (and thus, risk ended up being abandonware) and, to my understanding, does some unsafe things under the hood to achieve such results.

**Comment by ruseinov** [comment]
> I'd be careful with using `kanal`. While I understand that it fares well performance-wise, it's less widely used (and, in effect, is not as well-tested) as the alternative. It has fewer contributors (and thus, risk ended up being abandonware) and, to my understanding, does some unsafe things under the hood to achieve such results.

All of that is true. The good news is it's easy to convert from/to kanal, because the interface is very similar. 
Unsafe is a choice, if it increases performance significantly and is well-tested - no harm done, though looking into this
in detail wouldn't hurt. 
Since we are aiming at performance - it might be worth the time.

**Comment by hanabi1224** [comment]
`kanal` crate does not seem to have a stable release yet, and there's an outstanding data race bug to be fixed. Should we wait until its stable release?

**Comment by ruseinov** [comment]
> `kanal` crate does not seem to have a stable release yet, and there's an outstanding data race bug to be fixed. Should we wait until its stable release?

Yep, no rush with that one.

**Comment by LesnyRumcajs** [comment]
It turned out `kanal` is unstable and not production-ready. See https://github.com/ChainSafe/forest/pull/3538
