### ISSUE TITLE
Snapshot fetch: support resumes and streaming

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#3511]
**Issue summary**
Thanks to the **herculean** work with TypeScript performed in the [latest snapshot worker](https://github.com/ChainSafe/forest-iac/pull/266), we are now ready to support resumes for fetching the snapshots from CloudFlare.

We also [moved away](https://github.com/ChainSafe/forest/pull/2814) from `aria2c` so we need to implement this in terms of `reqwest` (or some other solution that doesn't require external binaries). One library, being abandonware at the moment, we can draw inspiration from is [reqwest_resume](https://github.com/alecmocatta/reqwest_resume). It should do what we want, but it is no longer maintained, and we don't want to maintain a fork. So only draw inspiration from it.

If feasible, it would be great to have a streaming solution for this so the result could be piped to other commands. If it proves challenging, let's create a separate issue.

Tasks:
- [ ] Implement resumes. Either use the library provided if it works or contrive our own solution if necessary.
- [ ] Unit tests for resumes.
- [x] Implement streaming for fetching or create an issue if it requires more work than anticipated.
- [x] Unit tests for streaming if implemented.

Acceptance criteria:
- [ ] Resuming works and a set of unit tests is covering the feature,
- [x] Streaming is implemented (and unit-test covered) or an issue is created.

**Other information and links**

**Comment by LesnyRumcajs** [comment]
I might not have time for this soon; bailing for now. If anyone is interested, go ahead and grab it.

**Comment by lemmih** [comment]
Resume for streams implemented. Resuming partially downloaded files has yet to be implemented, but it is a lower priority.

**Comment by lemmih** [comment]
Let's skip resume for downloading files. Users can always use an external tool if need be.
