### ISSUE TITLE
forest-cli check fails with missing key

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#3518]
**Issue summary**

Forest-cli CI check fails with an error:
```
forest-tool archive export --epoch 945940 --depth 900 --output-path base_snapshot.forest.car.zst exported_snapshot.car.zst
Error: missing key: bafy2bzaceax2twnpmykxwjgmkkmlo7quj2asj7jfrv7dwzqrhmrtkwtmtir4q
```

It seems like there are more disabled checks in this particular test, bugs need to be fixed to re-enable them.

**Other information and links**

**Comment by LesnyRumcajs** [comment]
As mentioned by @lemmih, this may be related to improper handling of null epochs.

**Comment by lemmih** [comment]
CI was updated to avoid this issue.
