### ISSUE TITLE
Find a way of choosing StateTree between fvm@3 and fvm@4

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#3523]
**Issue summary**

`StateTree` from `fvm@3` and `fvm@4` both support  `StateTreeVersion::V5` but are not compatible, when using `StateTree` from `fvm@4`, forest panics during nv18-nv20 state migration

> thread 'state migration thread: 1' panicked at 'Failed iterating over actor state: StateTree::for_each not supported on old state trees

We need to find a way of deciding which `StateTree` version to use in `StateTree::new` and `StateTree::new_from_root`.

**Other information and links**

**Comment by hanabi1224** [comment]
It's actually a bug in the shim code, fixed by https://github.com/ChainSafe/forest/pull/3520/commits/f61691111c7e1df4a8c6e2704c441a9a178cfba1

**Comment by lemmih** [comment]
> It's actually a bug in the shim code, fixed by [f616911](https://github.com/ChainSafe/forest/commit/f61691111c7e1df4a8c6e2704c441a9a178cfba1)

Alright. Closing this issue.
