### ISSUE TITLE
Properly set `elapsed` field in type convertion logic between `GasChargeV3` and `GasChargeV4`

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#3524]
**Issue summary**

The `GasDuration` field has been exported publicly in https://github.com/filecoin-project/ref-fvm/pull/1897
We need to take a new fvm release to implement it (otherwise we might have to use some hacky unsafe code to manipulate the private type)

**Other information and links**

**Comment by lemmih** [comment]
We don't care about `elapsed`. We can ignore it or set it to zero.

**Comment by Stebalien** [comment]
Released.

**Comment by LesnyRumcajs** [comment]
Thank you @Stebalien !
