### ISSUE TITLE
bultin-actors v12 in fil-actor-states

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3527]

**Comment by LesnyRumcajs** [comment]
@sudo-shashank let's add support for https://github.com/filecoin-project/builtin-actors/releases/tag/v12.0.0-dev.3 for now. Later on we can re-iterate on the final release, but we need to test what is available now.

**Comment by LesnyRumcajs** [comment]
Some actors may be more important than others in terms of the state migration, For now, let's make sure we have available both System and Miner actors as soon as possible.

**Comment by sudo-shashank** [comment]
on it

**Comment by LesnyRumcajs** [comment]
Done https://github.com/ChainSafe/fil-actor-states/pull/170
