### ISSUE TITLE
DrandBeacon doesn't handle genesis robustly

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#3572]
https://github.com/ChainSafe/forest/blob/462fe5e279fb93ea6091719c369707026c9a36b3/src/beacon/drand.rs#L94-L100

https://github.com/ChainSafe/forest/blob/462fe5e279fb93ea6091719c369707026c9a36b3/src/beacon/drand.rs#L261-L264

**Comment by LesnyRumcajs** [comment]
What do we do with this? The second snippet doesn't exist in Forest. The first one is a copy from Lotus and given it's a TODO since the inception of Lotus, I don't think it's worth doing anything with it. If we do, what problem do we want to actually solve?
