### ISSUE TITLE
RPC command request [web3mine]

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#3581]
**Issue summary**

The following RPC commands are being deemed useful for [Web3mine](https://web3mine.io/). We will try to include them in Forest.

- [x] [ChainGetTipSetByHeight](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md#chaingettipsetbyheight) as its name implies it is used to get the tipset at a specific height.
- [x] [ChainGetParentMessages](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md#chaingetparentmessages) returns a set of unique messages for the parent tipset. (this uniques feature is important as you know some blocks contain the same message - so this will filter that out). One of our use cases is that we monitor some specific height ( mostly the head ) we look one epoch in past as this is the nicest way to have all the unique messages and the receipts as well right away
 - [x] [StateGetRandomnessFromBeacon](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md#stategetrandomnessfrombeacon) - as the name implies it returns the randomness for the specific height. One of our usecase is to compute the ticket that is later on used for sealing
- [x] [StateMinerInfo](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md#stateminerinfo) - general miner info. it would be beneficial to see if and when the slashing of a sector occurred. Also now that resnap is coming ( snapping an already snapped cc sector) it will make sense to know when this really happened.
- [x] [StateReadState](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md#statereadstate) - Extract state info from actors, it can be used for bucnh of things for example we are using it to find out how much is stored in the miner
- [x] [StateMinerActiveSectors](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md#statemineractivesectors) - list of active sectors for any miner. It contains bunch of useful data. Among the other when it was created, when it will expire, how much money was locked into it
- [x] [StateSectorGetInfo](https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md#statesectorgetinfo) here lotus returns the info that was included during precomit, from my perspective, it would be beneficial to include prove commit part as well ( basically the c2 output )

**Comment by lemmih** [comment]
@lerajk We have all the high priority RPC methods, and we're 100% in compliance with Lotus. We'll set up a public node as soon as possible next. Closing this tracking issue.
