### ISSUE TITLE
RPC endpoint request [Glif]

### ISSUE THREAD

**Issue by lerajk** [ChainSafe/forest#3585]
**Issue summary**

The following RPC commands are being deemed useful for [Glif](https://www.glif.io/). We will try to include them in Forest. We can exclude the ETH endpoints.

**Other information and links**

- [Filecoin endpoints](https://api.node.glif.io/filecoin-rpc/)
- [Ethereum endpoints](https://api.node.glif.io/eth-rpc/)

**Comment by lemmih** [comment]
Context: These are _all_ the endpoints that can be accessed through the Lotus Gateway. They were not picked by Glif.

**Comment by lerajk** [comment]
These are the ones we need to include; the most active endpoints are listed below: 

- ChainHead
- StateMinerPower
- ChainGetMessage
- StateMarketStorageDeal
- StateMinerInfo
- EthCall
- WalletBalance
- EthGetBalance
- EthBlockNumber
- EthGetTransactionHashByCid
- EthChainId
- StateAccountKey
- ChainNotify
- EthFeeHistory
- EthGetBlockByNumber
- ChainGetBlockMessages
- ChainGetTipSet
- EthGetTransactionCount
- EthGetTransactionReceipt 
- StateLookupID
- ChainGetMessageInTipset
- EthGetTransactionCount
- EthGetTransactionReceipt 
- StateLookupID
- ChainGetMessageInTipset
- StateGetActor
- ChainGetTipSetByHeight
- EthGasPrice
- MsigGetAvailableBalance 
- ChainGetParentMessage 
- EthGetLogs
- StateReadState

**Comment by q9f** [comment]
Makes sense to group them by namespace instead of implementing them one by one, i.e., prioritize implementing:

1. Filecoin.Chain*
2. Filecoin.State*
3. eth_*
4. Filecoin.Wallet*

And so on...

**Comment by lemmih** [comment]
Replaced by #4164 and #4165. Method tracker: https://github.com/orgs/ChainSafe/projects/29.
