### ISSUE TITLE
Network Version 21 upgrade (mainnet)

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#3592]
**Issue summary**
NV21 Watermelon upgrade for mainnet is scheduled for 2023-11-28. Once the actors' bundle is released and a specific epoch is scheduled, add the bundle to assets and the upgrade to the mainnet schedule

**Other information and links**
Calibnet upgrade: https://github.com/ChainSafe/forest/issues/3422
Schedule tracking: https://github.com/filecoin-project/community/discussions/74#discussioncomment-7274188

**Comment by lemmih** [comment]
Mainnet epoch and date: 3431940 , 2023-11-29T13:30:00Z.
