### ISSUE TITLE
archive urls shouldn't require trailing slash

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#3631]
| Link | Works |
| - | - |
| https://forest-archive.chainsafe.dev/latest/calibnet/ | ✅ |
| https://forest-archive.chainsafe.dev/latest/calibnet | ❌ |
| https://forest-archive.chainsafe.dev/list/ | ✅ |
| https://forest-archive.chainsafe.dev/list | ❌ |
| https://forest-archive.chainsafe.dev/list/index.html | ❌|

These should all point to the same respective resources

**Comment by LesnyRumcajs** [comment]
> We should also link to them from somewhere

https://github.com/ChainSafe/forest/issues/3604

**Comment by aatifsyed** [comment]
This is also the case for forest-archive.chainsafe.dev/latest/calibnet

**Comment by LesnyRumcajs** [comment]
Except for `https://forest-archive.chainsafe.dev/list/index.html`, which is weird, all other links work now.
