### ISSUE TITLE
Create and Add BeaconEntry structure to BlockHeaders

### ISSUE THREAD

**Issue by ec2** [ChainSafe/forest#366]
**Task summary**

With Drand, there is a new field in the BlockHeaders. We call this a BeaconEntry. 
This issues does not cover any verification, just updating the definition of BlockHeader. 

**Specification reference**

- https://github.com/filecoin-project/lotus/blob/testnet/3/chain/types/blockheader.go#L29

**Other information and links**

**Comment by dutterbutter** [comment]
Based on `testnet/3` BlockHeader we are also missing the fields `ElectionProof *ElectionProof`

**Comment by austinabell** [comment]
> Based on `testnet/3 BlockHeader`, we are also missing the fields `ElectionProof: *ElectionProof`

Yeah, seems they switch the election proof format back to previous format, so with this change (assume once the serialization vectors are updated) that EPostproof needs to be updated to serialized bytes instead of the serialization of the VM proof type
