### ISSUE TITLE
lints are flaky

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#3665]
https://github.com/ChainSafe/forest/actions/runs/6734221792/job/18304630910
https://github.com/ChainSafe/forest/actions/runs/6546848863/job/17778151044
https://github.com/ChainSafe/forest/actions/runs/6587472405/job/17897823529

Call to `cargo check` fails, no diags :/

**Comment by LesnyRumcajs** [comment]
@aatifsyed do we plan to do it? This particular lint was suppressed 6 months ago and the links mentioned are broken. If we still plan to do it, let's describe the issue better. Otherwise, let's remove the code and close this.
