### ISSUE TITLE
Consider adding `multicore-sdr` support for Filecoin proofs

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#3757]
**Issue summary**

The feature `multicore-sdr` can be added to the Filecoin proofs which is done in Lotus by default (via [filecoin-ffi](https://github.com/filecoin-project/filecoin-ffi/blob/441fa8e61189dc32c2960c1f8d8ba56269f20366/rust/Cargo.toml#L62)). It is unclear to me if those optimizations are useful only when doing operations like PC1 (which Forest doesn't do) or they could be helpful during validations as well.

Note that `multicore-sdr` requires adding `hwloc` as a dependency to Forest (and `hwloc-devel` or similar to Forest builds).

Run Forest with and without those optimizations (perhaps compute a few hundred tipsets) and see if it's worth adding it as a dependency.

**Other information and links**

**Comment by lemmih** [comment]
My tests show no difference in performance.

**Comment by LesnyRumcajs** [comment]
Let's close it, then?
