### ISSUE TITLE
chainsafe.io sub-domain for documentation

### ISSUE THREAD

**Issue by q9f** [ChainSafe/forest#3758]
**Task summary**

Avoid using `https://chainsafe.github.io/forest`

**Specification reference**

- consider `docs.forest.chainsafe.io` for the API documentation
- consider `book.forest.chainsafe.io` for the Forest book

- **Other information and links**

nice to have for the website

**Comment by lemmih** [comment]
`docs.forest.chainsafe.io` hosts the Forest book. API docs are available on `docs.rs`.
