### ISSUE TITLE
Offline RPC provider

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#3812]
**Issue summary**

The Forest daemon connects to the Filecoin network _AND_ sets up an RPC server. These two actions can be separated, and it should be possible to set up an RPC server that merely serves data from CAR files and does not connect to the Filecoin network. Such an RPC server would be useful for performing historical queries, testing, and benchmarking.

Tasks:

 - [X] Add `forest-tool api serve [CAR_FILES]` command which runs an RPC server.
 - [X] Ask to download a snapshot if no snapshot files are given.
 - [X] Default to the standard Forest API port, but make it easy to change.
 - [X] The sync-stage should claim to be `SyncStage::Complete` even though we're not following HEAD. (Maybe `SyncStage::Idle` is more appropriate.)
 - [X] CI: Test the API server against itself. Use `forest-tool api compare` with two identical node-less RPC endpoints.

**Other information and links**

**Comment by davidgasquez** [comment]
This would be awesome! Can you give any ETA on it? Would love to try it out. :raised_hands:

**Comment by davidgasquez** [comment]
> it should be possible to set up an RPC server that merely serves data from CAR files and does not connect to the Filecoin network

Random idea: the CAR files can live on IPFS and `forest-tool api serve` could fetch the required data at query time.

Much slower, but also much easier to get started?

**Comment by aatifsyed** [comment]
I don't like the name "node-less" - I'd propose renaming this to "offline RPC" or something.

**Comment by lemmih** [comment]
> I don't like the name "node-less" - I'd propose renaming this to "offline RPC" or something.

Done.

**Comment by ruseinov** [comment]
Nodeless sounded cooler :)
