### ISSUE TITLE
fvm_shared::PoStProof should implement `Hash`, `Ord` and `PartialOrd`

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#3852]
_Originally posted by @aatifsyed in https://github.com/ChainSafe/forest/pull/3851#discussion_r1444038232_

**Comment by LesnyRumcajs** [comment]
Why is this an issue in this repository? `fvm_shared::PoStProof` is defined in the `ref-fvm`.

**Comment by lemmih** [comment]
Not actionable in Forest. Closing.
