### ISSUE TITLE
Be strict when handling params in JSON-RPC server

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#3966]
**Issue summary**

We should always validate parameter correctness in our RPC API, even if the method doesn't take some.

This is the case for:

- `sync_state`
- `state_network_name`
- `start_time`
- `version`
- `session`
- `shutdown`
- `net_addrs_listen`
- `net_peers`
- `net_info`
- `chain_get_genesis`
- `chain_head`
- `eth_accounts`
- `eth_block_number`
- `eth_chain_id`
- `eth_gas_price`

**Task summary**

- [ ] Always parse params in methods above
- [ ] Test that incorrect parameter types generate a -32700 error code

**Other information and links**

https://www.jsonrpc.org/specification#response_object

**Comment by aatifsyed** [comment]
I don't really understand this issue - the current parameter checking already forbids trailing arguments:
https://github.com/ChainSafe/forest/blob/ab10cdbe73aa770d44e2debe5bba06ee62fb251e/src/rpc/reflect/parser.rs#L155-L169

```console
$ curl -X POST 'http://127.0.0.1:2345/rpc/v1' -H 'Content-Type: application/json' --data '{"jsonrpc": "2.0", "method": "Filecoin.ChainHead", "id": null}'
{"jsonrpc":"2.0","result":{ .. },"id":null}

$ curl -X POST 'http://127.0.0.1:2345/rpc/v1' -H 'Content-Type: application/json' --data '{"jsonrpc": "2.0", "method": "Filecoin.ChainHead", "id": null, "params": []}'
{"jsonrpc":"2.0","result":{ .. },"id":null}

$ curl -X POST 'http://127.0.0.1:2345/rpc/v1' -H 'Content-Type: application/json' --data '{"jsonrpc": "2.0", "method": "Filecoin.ChainHead", "id": null, "params": ["unexpected"]}'
{"jsonrpc":"2.0","error":{"code":-32602,"message":"unexpected trailing arguments","data":{"count":1}},"id":null}
```

```console
$ git show --summary
commit 247c31153c572c95d2064942cd23f5b9d5629ed7 (HEAD, origin/main, origin/HEAD)
Author: hanabi1224 <harlowmoo@gmail.com>
Date:   Wed Jun 26 19:44:09 2024 +0800

    fix(rpc): update StateSectorPreCommitInfo against v1 spec (#4443)
```

**Comment by aatifsyed** [comment]
Note we return `-32602 (invalid params - Invalid method parameter(s))` instead of `-32700 (parse error - Invalid JSON was received by the server`, which I think is correct
