### ISSUE TITLE
Add subcommands to `forest-cli` to handle channels

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#4001]
**Issue summary**

This is a follow up of https://github.com/ChainSafe/forest/pull/3978.

Right now, we're using some javascript code to exercise our pubsub RPC code.
We would like to have some subcommand achieving similar functionality.

**Task summary**

- [ ] Add a subcommand to open a channel
- [ ] Add a subcommand to cancel a subscription

**Acceptance Criteria**

**Other information and links**

**Comment by lemmih** [comment]
`forest-cli` should not have a subcommand for opening a channel. The Forest RPC library should have support for channels. Otherwise, we cannot support the `chain_notify` method.

**Comment by lemmih** [comment]
Closing as not-actionable.
