### ISSUE TITLE
Remove `jsonrpc-v2` from `Cargo.toml`

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#4008]
**Issue summary**

Since we have migrated to `jsonrpsee`, we should completely remove the old `jsonrpc-v2` crate

**Other information and links**

**Comment by elmattic** [comment]
Maybe we can get rid of `tokio_tungstenite` as well (can be done in a separate PR)?

**Comment by hanabi1224** [comment]
> Maybe we can get rid of tokio_tungstenite as well (can be done in a separate PR)?

@elmattic I'd prefer tracking it in a separate issue
