### ISSUE TITLE
Offline RPC from multiple snapshots

### ISSUE THREAD

**Issue by davidgasquez** [ChainSafe/forest#4058]
**Describe the bug**

Can't load multiple snapshots with `forest-tool api serve`

**To Reproduce** Steps to reproduce the behaviour:

1. Get two snapshots or more.
```bash
mkdir data
wget https://forest-archive.chainsafe.dev/mainnet/diff/forest_diff_mainnet_2020-08-24_height_0+3000.forest.car.zst -P data
wget https://forest-archive.chainsafe.dev/mainnet/lite/forest_snapshot_mainnet_2020-08-24_height_0.forest.car.zst -P data
```

2. Serve them.

```bash
forest-tool api serve data/forest_snapshot_mainnet_2020-08-24_height_0.forest.car.zst data/forest_diff_mainnet_2020-08-24_height_0+3000.forest.car.zst 
```

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```
error: unexpected argument 'data/forest_diff_mainnet_2020-08-24_height_0+3000.forest.car.zst' found

Usage: forest-tool api serve [OPTIONS] [SNAPSHOT_FILE]

For more information, try '--help'.
  ```
</details>

**Expected behaviour**

RPC being served from these snapshots

**Environment (please complete the following information):**

- OS: Running from `ghcr.io/chainsafe/forest:edge`
- Branch/commit: `ghcr.io/chainsafe/forest:edge`

**Comment by LesnyRumcajs** [comment]
Hey, @davidgasquez, this will be resolved via https://github.com/ChainSafe/forest/pull/4059.

**Comment by davidgasquez** [comment]
Thanks for the quick fix @LesnyRumcajs!
