### ISSUE TITLE
snapshots do not work well with `lotus --import-chain`

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#4087]
**Issue summary**

Error: ([full CI log](https://github.com/ChainSafe/forest/actions/runs/8368921866/job/22913947404#step:6:123))
```
ERROR: chain validation failed: getting block messages for tipset: failed to get messages for block: failed to load msgmeta (bafy2bzaced3hf4mfqir6dwr57v3eeiafrvba54a57ma3vwcqmxgo33ricm2es): ipld: could not find bafy2bzaced3hf4mfqir6dwr57v3eeiafrvba54a57ma3vwcqmxgo33ricm2es
```

And this is also why `Filecoin.StateSearchMsg*` methods fail without re-validating tipsets in a snapshot

**Other information and links**

**Comment by lemmih** [comment]
That's expected. `--import-chain` is not the same as `--import-snapshot`. The former flag tries to re-validate the chain all the way back to genesis which won't work unless you use a full snapshot.
