### ISSUE TITLE
Ethereum RPC Methods 

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#4165]
**Issue summary**

The following RPC methods are necessary to be compatible with the glif.io public RPC provider (post-FVM).

- [ ] Everything in https://github.com/ChainSafe/forest/issues/4164
- [x] EthAccounts
- [x] #4686
- [x] EthBlockNumber
- [x] Filecoin.EthCall
- [x] EthChainId
- [x] #4556
- [x] #4493
- [x] #4167
- [x] #4183
- [x] #4360
- [x] #4307
- [x] #4310
- [ ] Filecoin.EthGetFilterChanges #4670 
- [ ] Filecoin.EthGetFilterLogs #4671 
- [ ] Filecoin.EthGetLogs #4669 
- [x] #4368
- [x] #4341
- [x] #4701
- [x] #4702
- [x] #4463
- [x] #4703
- [x] #4487 
- [x]  #4506
- [x] #4689
- [ ] #4704
- [x] #4511 
- [x] #4666 
- [x] #4665 
- [x] #4667 
- [x] Filecoin.EthProtocolVersion
- [x] #4706
- [ ] #4707
- [x] EthSyncing
- [ ] #4708
- [ ] #4709
- [x] #4668 
- [ ] #4710
- [ ] #4839

Lotus documentation for the RPC methods: https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md

**Other information and links**

**Comment by ansermino** [comment]
@LesnyRumcajs @elmattic @sudo-shashank I would like to break this out into smaller chunks. I propose:

Log Methods:
- https://github.com/ChainSafe/forest/issues/4670
- https://github.com/ChainSafe/forest/issues/4671
- https://github.com/ChainSafe/forest/issues/4669

General State Queries:
- https://github.com/ChainSafe/forest/issues/4704
- https://github.com/ChainSafe/forest/issues/4839 

Subscriptions:
- https://github.com/ChainSafe/forest/issues/4707
- https://github.com/ChainSafe/forest/issues/4710

Trace methods:
- https://github.com/ChainSafe/forest/issues/4708
- https://github.com/ChainSafe/forest/issues/4709

**Comment by LesnyRumcajs** [comment]
Looks good to me. @elmattic does any of the proposed groupings depend on any of the other?

**Comment by elmattic** [comment]
I'm good with that. I've just removed `Filecoin.EthGetLogs` issue as it was already done.

**Comment by elmattic** [comment]
> Looks good to me. @elmattic does any of the proposed groupings depend on any of the other?

I believe they should be fairly independent by now.

**Comment by ansermino** [comment]
Closing in favour of #4974, #4975, #4976, #4977.
