### ISSUE TITLE
Filecoin.EthGetBlockByHash

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#4167]
Lotus documentation: https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md#EthGetBlockByHash

This method could be implemented together with `Filecoin.EthGetBlockByNumber`.

**Comment by elmattic** [comment]
I've created a dedicated issue for `Filecoin.EthGetBlockByNumber`. The PR is already significant, and `EthGetBlockByHash` is not straightforward.
