### ISSUE TITLE
TODO in PendingSubscriptionSink

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#4188]
https://github.com/ChainSafe/forest/commit/363aac16433c43b3c1abf21417061ed755b753bc#diff-78e932c0563f39b9d22b2cb2cc901ceeac49b68952476be94bb17e40346b9203R127

**Comment by aatifsyed** [comment]
Introduced in #3978

**Comment by elmattic** [comment]
I think our plan is to get rid of the `PendingSubscriptionSink`: https://github.com/ChainSafe/forest/issues/4000

**Comment by elmattic** [comment]
This is some TODO comment originating from the `jsonrpsee` crate.

**Comment by LesnyRumcajs** [comment]
So, should the comment be removed and closed? Otherwise, let's have a meaningful description on what is to be done.

**Comment by elmattic** [comment]
We can close it.
