### ISSUE TITLE
Research Clock Sync

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/forest#42]
The nodes clock is expected to be sync'd every hour using an NTP server (pool.ntp.org recommended). More research is required into how we can do this.

http://localhost:1313/#clock-requirements (e9b36c7)

**Comment by austinabell** [comment]
For the foreseeable future, we won't be doing this as it isn't an explicit part of the protocol. 

Currently up to users to handle clock sync through ntp or otherwise, and system time will be used within the client.
