### ISSUE TITLE
error: failed to run custom build command for `neptune-triton v0.2.2`

### ISSUE THREAD

**Issue by lxj-my** [ChainSafe/forest#420]
Compiling ocl-core-vector v0.1.0
   Compiling tokio-tcp v0.1.4
   Compiling tempfile v3.1.0
   Compiling libsecp256k1 v0.3.5
   Compiling tls-api v0.3.2
The following warnings were emitted during compilation:

warning: ./lib/a.c:14:10: fatal error: CL/cl.h: No such file or directory
warning:  #include <CL/cl.h>
warning:           ^~~~~~~~~
warning: compilation terminated.

error: failed to run custom build command for `neptune-triton v0.2.2`

Caused by:
  process didn't exit successfully: `/home/sw/workspace/filecoin/forest/target/release/build/neptune-triton-f8e585453ad11c46/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-shared" "-Wall" "-Wextra" "-fPIC" "-lOpenCL" "-o" "/home/sw/workspace/filecoin/forest/target/release/build/neptune-triton-532c42a02dd1b116/out/./lib/a.o" "-c" "./lib/a.c"
cargo:warning=./lib/a.c:14:10: fatal error: CL/cl.h: No such file or directory
cargo:warning= #include <CL/cl.h>
cargo:warning=          ^~~~~~~~~
cargo:warning=compilation terminated.
exit code: 1

--- stderr

error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-shared" "-Wall" "-Wextra" "-fPIC" "-lOpenCL" "-o" "/home/sw/workspace/filecoin/forest/target/release/build/neptune-triton-532c42a02dd1b116/out/./lib/a.o" "-c" "./lib/a.c" with args "cc" did not execute successfully (status code exit code: 1).

warning: build failed, waiting for other jobs to finish...
error: failed to compile `forest v0.1.0 (/home/sw/workspace/filecoin/forest/forest)`, intermediate artifacts can be found at `/home/sw/workspace/filecoin/forest/target`

Caused by:
  build failed
Makefile:4: recipe for target 'install' failed
make: *** [install] Error 101

**Comment by austinabell** [comment]
ah, so you just need OpenCL to compile the Filecoin proofs. Our documentation should probably be updated. Thanks for the issue :)

One way to install the OpenCL package on Ubuntu is:

```bash
sudo apt update
sudo apt install ocl-icd-opencl-dev
```

**Comment by lxj-my** [comment]
thanks
