### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/forest#4219]
**Issue summary**

The readme could use a refresh. Some ideas I intend to propose in a PR:
- Add RPC info + links
- Update Forest description (align with roadmap annoucement)
- Reduce duplicated docs (favour docs site over readme)
- Mention snapshot service

Suggestions welcomed!

**Other information and links**

N/A

**Comment by LesnyRumcajs** [comment]
@ansermino Seems like a duplicate of https://github.com/ChainSafe/forest/issues/2118.

**Comment by ansermino** [comment]
Will move to the existing issue 👍
