### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#4226]
## Issue summary

This is an umbrella issue for the documentation improvement initiative for 2024.

### Scope

- Conduct workshop to review examples of node documentation and identify pros/cons
- Define a structure for the updated documentation
- Refactor existing docs to satisfy new format
    - Distribute tasks to update docs or add new docs as needed
- User guides etc
    - defining the user profiles and scope of the guides
- RPC/CLI etc docs (CLI docs autogenerated)
    - CLI https://github.com/ChainSafe/forest/issues/4227
- Ensure sufficient analytics to understand what pages people are using and how they are finding them

### Other improvements
- https://github.com/ChainSafe/forest/issues/2118
- https://github.com/ChainSafe/forest/issues/3758
- https://github.com/ChainSafe/forest/issues/3731
- https://github.com/ChainSafe/forest/issues/3109
- https://github.com/ChainSafe/forest/issues/2602
- https://github.com/ChainSafe/forest/issues/2563
- https://github.com/ChainSafe/forest/issues/1263

### Sources of inspiration

https://docs.nethermind.io/
https://besu.hyperledger.org/
https://erigon.gitbook.io/erigon
https://geth.ethereum.org/docs

**Comment by ansermino** [comment]
Remaining issues will be tracked independantly
