### ISSUE TITLE
RPC tests should support failure tests

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#4241]
## Issue summary

              I'm okay with the condition that it's explicit for this particular test (like `should_fail`). I wouldn't like the behaviour like before, where all matching internal server errors were considered a success.

_Originally posted by @LesnyRumcajs in https://github.com/ChainSafe/forest/pull/4238#discussion_r1571999743_

**Comment by lemmih** [comment]
Done via `.policy_on_rejected()`.
