### ISSUE TITLE
[Enhancement] Consider replacing string representation for ChainEpoch.

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#4272]
This would work, we just need to make sure to convert a potential `try_into` error into something readable.

```
i64::from_le_bytes(self.db.read_bin(SETTINGS_KEY)?.unwrap_or_default().try_into()?)
```

Edit: Actually, now that I think about it - `unwrap_or_default` might need to be replaced with `0::to_le_bytes` or something along those lines. 

_Originally posted by @aatifsyed in https://github.com/ChainSafe/forest/pull/4270#discussion_r1583107462_

**Comment by lemmih** [comment]
I'm okay with the code as it is. It's readable, and performance doesn't matter.
