### ISSUE TITLE
Static RPC conformance checks

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#4309]
## Issue summary

It'd be beneficial for tracking RPC progress and conformance to have a way to statically check conformance between Forest and Lotus RPC API.

Lotus API spec is defined in [here](https://github.com/filecoin-project/lotus/blob/main/build/openrpc/full.json)
Forest API spec might be defined along the lines of [this](https://github.com/ChainSafe/forest/blob/3283adcb4cfdd9d829540f39045c0255977f82e4/src/rpc/snapshots/forest_filecoin__rpc__tests__openrpc.snap)

Challenges:
- completely different formats that included complex types from different programming languages - how much work will it be? Is it worth the time invested?,
- Lotus spec is missing some methods, e.g., `ChainNotify`. If we do this, we should inquire Lotus team.
- Is the `snap` format stable?  Is Lotus spec format stable?

Ideas:
- Can the spec formats between implementations be somehow unified? The `snap` files seem to be specific to Rust `insta` tool. What I'd like to see is some sort of `OpenAPI` language-agnostic approach.

**Comment by lemmih** [comment]
Related issue: https://github.com/ChainSafe/forest/issues/4365

**Comment by LesnyRumcajs** [comment]
This is covered by the common node API initiative.
