### ISSUE TITLE
Boost-related RPC Methods

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/forest#4333]
- [x] ChainGetMessage
- [x] ChainHead
- [ ] ~CheckFullNodeApiVersion~ (Helper method)
- [ ] ~CreateSectorAccessor~ (Helper method)
- [ ] ~GetFullNodeAPIV1~ (Helper method)
- [ ] ~GetFullNodeApi~ (Helper method)
- [x] MpoolPending
- [x] NetAddrsListen (Testing issues - unable to verify against Lotus)
- [x] NetConnect (Testing issues - no integration test)
- [x] #4353
- [x] StateAccountKey
- [x] StateCall (Testing issues - unable to verify against Lotus)
- [x] StateDealProviderCollateralBounds
- [x] StateGetActor
- [x] #4335
- [x] #4336
- [x] StateLookupID
- [x] StateMarketBalance
- [x] StateMarketStorageDeal
- [x] StateMinerInfo
- [x] StateMinerSectors
- [x] StateNetworkVersion
- [x] StateSearchMsg
- [x] #4334
- [x] StateSectorGetInfo
- [x] StateVerifiedClientStatus
- [x] StateWaitMsg
- [x] Version
- [x] WalletList (Testing issue - no integration tests)
- [x] WalletSign

Update
- [x] MpoolPushMessage
- [x] StateMinerActiveSectors
- [x] #4380

**Comment by lemmih** [comment]
Lotus RPC documentation: https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-v1-unstable-methods.md

**Comment by lemmih** [comment]
Done.
