### ISSUE TITLE
Investigate connection limiting and trimming in rust lib-p2p.

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#4355]
## Issue summary

This came up as part of `NetProtectAdd` RPC endpoint implementation, which prevents certain peers from being disconnected, unless the process is low on memory. This is tightly coupled with go-libp2p connection manager implementation.

See https://github.com/filecoin-project/lotus/blob/2086b219d2828cc2bd4c943b0b792e61ab6321f9/node/impl/net/protect.go#L11-L17 for details.

**Comment by lemmih** [comment]
We've looked into libp2p connection limits in the past and decided to hold off until we have more experience with running Forest.
