### ISSUE TITLE
Implement FIP-0091

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#4366]
> https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0091.md is planned to be shipped as well, requiring node changes. See the corresponding Lotus PR that implements this FIP https://github.com/filecoin-project/lotus/pull/11969

_Originally posted by @LesnyRumcajs in https://github.com/ChainSafe/forest/issues/4318#issuecomment-2129119208_

**Comment by arajasek** [comment]
Feel free to assign this to me. I'll take a steb at it next week, and provide an update by the end of the week.

**Comment by LesnyRumcajs** [comment]
Thanks @arajasek !

**Comment by arajasek** [comment]
Hey sorry about the silence here. Unfortunately, I don't think I'm going to have the bandwidth to take this on. I'm really sorry to abandon it.

**Comment by LesnyRumcajs** [comment]
@arajasek no worries!
