### ISSUE TITLE
Fix `Filecoin.StateCall` test (or implementation)

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#4433]
## Issue summary

The method was disabled in https://github.com/ChainSafe/forest/pull/4429. Once fixed, it should be removed from the filter lists.

**Comment by hanabi1224** [comment]
same cause as https://github.com/ChainSafe/forest/issues/4432#issuecomment-2180557858

**Comment by lemmih** [comment]
Can this issue be replaced by https://github.com/ChainSafe/forest/issues/3733?

**Comment by LesnyRumcajs** [comment]
@lemmih #3733 doesn't capture that this method is broken in its current state, so I'd leave them separate. Alternatively, we can rename the and modify #3733 to capture both cases.

**Comment by lemmih** [comment]
Reproducible with calibnet snapshot from epoch 1891055. I've uploaded the snapshot to `debug/#4433` in our DO space: https://cloud.digitalocean.com/spaces/forest-snapshots?i=88c522&path=debug%2F%234433%2F
