### ISSUE TITLE
Complete State Manager

### ISSUE THREAD

**Issue by ec2** [ChainSafe/forest#446]
**Issue summary**

We have a very basic implementation of the State Manager right now. To be able to achieve parity we need to complete the other functionality like StateReply, GetBaseInfo, etc...

**Other information and links**

**Comment by amerameen** [comment]
@ec2 will break this down further

**Comment by dutterbutter** [comment]
This should be set as an epic for state manager related tasks.

**Comment by dutterbutter** [comment]
closing in favor of #487 since its an epic and could not figure out how to convert this into one haha
