### ISSUE TITLE
RPC Interface

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#447]

**Comment by amerameen** [comment]
Update: We need to add tasks to this in order for it to be comprehensive (e.g. Message Pool). Also, after Wallet, State, Message Pool, we should have everything we need to integrate Storage Miner. We're also still blocked on Websockets (waiting on Tide), which we need for ChainNotify.

**Comment by amerameen** [comment]
Update: We are blocked on the Paychannel RPC while changes are being made in Lotus.  (https://filecoinproject.slack.com/archives/C015G3B5RQE/p1595606540057100).

Otherwise, mostly done (Message Pool RPC PR needs a review). We may need to do the Events API for go-fil-markets integration.

**Comment by cryptoquick** [comment]
Does this cover the client, the daemon, or both?

Also, @austinabell , would you say this is a useful reference?
https://github.com/rs-ipfs/rust-ipfs/tree/master/http

**Comment by austinabell** [comment]
> Does this cover the client, the daemon, or both?
> 
> Also, @austinabell , would you say this is a useful reference?
> https://github.com/rs-ipfs/rust-ipfs/tree/master/http

This covers the daemon, aside from some cli commands, there is no client. And that API is different and specific to ipfs. This API is not used for anything consensus related (aside from miner -> daemon interactions) so there isn't any hard specifications, but we need to match the reference implementation to ensure compatibility with dev tooling.

Docs here:
https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-methods.md
