### ISSUE TITLE
FIP-0091 support for Ethereum RPC methods.

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#4477]
## Issue summary

While consensus-critical logic was implemented in the linked PR, corresponding RPC methods still require changes.

## Other information and links

Follow-up for https://github.com/ChainSafe/forest/pull/4473

**Comment by LesnyRumcajs** [comment]
@elmattic Would you be interested in taking this?

**Comment by hanabi1224** [comment]
It turns out the fix to #4518 and #4519 fixes this one as a side effect.
