### ISSUE TITLE
Two different StoragePower types

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/forest#455]
**Describe the bug**
We now have two `StoragePower` types, one is a `BigInt` in [`types/src/sector/mod`](https://github.com/ChainSafe/forest/blob/master/types/src/sector/mod.rs#L24) and another thats a `BigUint` in [`vm/actor/src/`](https://github.com/ChainSafe/forest/blob/master/vm/actor/src/lib.rs#L29).

I don't believe StoragePower should ever be negative but I am not a hundred percent sure.

**Comment by austinabell** [comment]
Well, not necessarily a bug, since it will still be handled correctly. But yeah this should be consolidated to one type/alias
