### ISSUE TITLE
Forest can't bootstrap a Lotus node

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#4576]
## Issue summary

It turns out a Forest node (`v0.19.0`) is not a able to bootstrap a Lotus node. It can, however, bootstrap another Forest node.

To reproduce on calibnet:
1. Start a Forest node, grab it's multiaddr with peer id.
2. Compile Lotus with the above as bootstrap node (make sure to set `LOTUS_SYNC_BOOTSTRAP_PEERS=1`)
3. With `lotus net peers` observe that the only peer it is connected to is the bootstrap node, whereas `forest-cli net peers` shows way more peers.

Similarly, do the same with another Forest and observe that the second instance has many other peers.

This behaviour _might_ stem from the fact that the peer exchange is not implemented in gossipsub in rust-libp2p ( [code mention](https://github.com/libp2p/rust-libp2p/blob/a749a41b95441a3dc87c61c472e7a9f00ca997fc/protocols/gossipsub/src/config.rs#L230-L234) and [issue](https://github.com/libp2p/rust-libp2p/issues/2398)) while [explicitly](https://github.com/filecoin-project/lotus/blob/ff0e889b587621a9bbb973a6e1ef0f145a565216/node/modules/lp2p/pubsub.go#L331-L344) enabled in Lotus. 

Does peer exchange over Kademlia and Identify not work in Lotus? If so, can this be mitigated? The alternative would be implementing peer exchange in gossipsub, which to my understanding, is not a trivial task.

To work on this, and ensure it doesn't break in the future, once fixed, we also need a CI job to check Forest-bootstrapper compatibility with Lotus (and another Forest).

**Comment by LesnyRumcajs** [comment]
@hanabi1224 I'll work on `CI job to check Forest-bootstrapper compatibility with Lotus`.

**Comment by hanabi1224** [comment]
The issue has been `fixed` by #4580 as a workaround
We decided to keep the issue open until a proper fix is made to the upstream `rust-libp2p`, `go-libp2p-kad-dht` or `lotus`

**Comment by hanabi1224** [comment]
Confirmed that the issue has been fixed in `rust-libp2p`, see https://github.com/libp2p/rust-libp2p/issues/5269 
We just need to upgrade `libp2p-kad` once it's released and revert #4580

**Comment by LesnyRumcajs** [comment]
Forest _can_ bootstrap a Lotus node now, so closing. We'll track the removal of workaround in https://github.com/ChainSafe/forest/issues/4602
