### ISSUE TITLE
Add devnet support to `forest-tool api serve` and document the functionality

### ISSUE THREAD

**Issue by lemmih** [ChainSafe/forest#4628]
## Issue summary

TDB

**Comment by LesnyRumcajs** [comment]
These need to be ported to `forest-tool api serve` https://github.com/ChainSafe/forest/blob/ded933f18c652e9c38d65553881f9692901b50fd/scripts/devnet/docker-compose.yml#L200-L206

**Comment by LesnyRumcajs** [comment]
Linked to #4598, given one is hardly useful without the other.
