### ISSUE TITLE
Investigate `EthCall`

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#4653]
## Issue summary

The `EthCall` is an important Ethereum RPC method that is supposedly a large beast. There is an existing issue to implement it https://github.com/ChainSafe/forest/issues/4613

The goal of this task is to investigate the work required to implement this method, if large (> 1 week of work), try to split it into smaller issues.

This should be timeboxed to 1 day.

**Comment by LesnyRumcajs** [comment]
Great! So there isn't anything to split and we can move to implementation? What about testing? Can we do more than the `api compare`?

**Comment by elmattic** [comment]
> Great! So there isn't anything to split and we can move to implementation? What about testing? Can we do more than the `api compare`?

Yes, we can move to implementation. I've got a first draft [here](https://github.com/ChainSafe/forest/pull/4659). If we can use `api compare`, let's use it. If more is needed, let's write some calibnet test script (e.g., create some Ethereum-style account, send some fil token there, check balance, etc.).

**Comment by LesnyRumcajs** [comment]
What tests are implemented in Lotus for `EthCall`?

**Comment by elmattic** [comment]
> What tests are implemented in Lotus for `EthCall`?

I found no tests for the `EthCall` method in the Lotus codebase. Only some tests, like in `TestFEVMErrorParsing` use this method, but it's more used for testing the FEVM than the RPC method itself. They do have tests in `eth_transactions_test.go`, but those are more generic high-level tests.

**Comment by LesnyRumcajs** [comment]
Thanks for investigating. Shall we close this?
