### ISSUE TITLE
Move all methods to `v1`

### ISSUE THREAD

**Issue by aatifsyed** [ChainSafe/forest#4678]
As a prerequisite to #3960, following the failure of #4516, I think we should, for all methods:
- bump `API_VERSION: ApiVersion = ApiVersion::V1` if possible.

This should be done in parts, as our tests will break when we come across incompatible methods.

Adding support back in for V0 should be a future task.

This is necessary for producing an up-to-date Common Node API spec - we must be confident that all methods are V1, so we should prioritize Common Node API methods

**Comment by hanabi1224** [comment]
FYI, as of CI in https://github.com/ChainSafe/forest/pull/4448 run, all RPC methods were V1 compatible
