### ISSUE TITLE
EthGetTransactionByBlockHashAndIndex

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#4701]
# Summary

This method is now supported in Lotus v1.31.0, and so we should support it as well.

# Completion Criteria

- [ ] Implement method
- [ ] Add api compare tests

# Additional Links & Resources

https://github.com/filecoin-project/lotus/pull/12618

**Comment by hanabi1224** [comment]
This method has been implemented in Lotus v1.31.0-rc1
