### ISSUE TITLE
Implement message methods in state_manager 

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/forest#472]
**Issue summary**

The state manager requires the ability to wait on a message. This is primarily used in the interaction with the market adapters. 

**Other information and links**

- [Lotus - WaitForMessage](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/stmgr.go#L483)
- [Lotus - tipsetExecutedMessage](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/stmgr.go#L637)
- [Lotus - searchBackForMsg](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/stmgr.go#L593) 
- [Lotus - GetReceipt](https://github.com/filecoin-project/lotus/blob/master/chain/stmgr/stmgr.go#L460)

**Comment by austinabell** [comment]
@AshantiMutinta can this be closed from #532 ?

**Comment by AshantiMutinta** [comment]
Yes absolutely
