### ISSUE TITLE
[NV24] F3 activation epoch

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#4803]
Post NV24 (~2 weeks) after the NV24 upgrade on mainnet, F3 is supposed to be activated. It's not yet clear what the solution will look like. Likely hard-coding the epoch (with some environmental variables) will be the solution both in Lotus and Forest. The issue is that the initial power table needs to be stored somewhere and we cannot read past 2000 epochs.

- [ ] F3 activation epoch is set (and configurable via an environmental variable),
- [ ] There's an option to opt-out from F3 if need be (currently it's opt-in, we may need to inverse that logic).

**Comment by LesnyRumcajs** [comment]
@hanabi1224 Could you please coordinate with the FilOz team on this? I believe there will be some testing on Butterflynet next week. Also, we tentatively scheduled F3 activation to 1 day after the calibnet upgrade.

**Comment by LesnyRumcajs** [comment]
See https://github.com/filecoin-project/lotus/pull/12552

**Comment by hanabi1224** [comment]
Will do.

**Comment by LesnyRumcajs** [comment]
Determine the number for calibnet and mainnet.

**Comment by hanabi1224** [comment]
Update on release process. We will need to make a patch release right after F3 activation (on calibnet and mainnet respectively) to include the initial power table cid to avoid late F3 participation issue.

**Comment by hanabi1224** [comment]
@LesnyRumcajs Yes, it will be a one-liner change to hard code the initial power table for F3, to workaround late participation issue described in https://github.com/filecoin-project/go-f3/issues/477
