### ISSUE TITLE
[F3] Implement manifest package

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#4829]
1. Implement configuration manifest structs and logic.
2. Integrate into relevant packages

needed to configure cert exchange and other packages.

**Comment by LesnyRumcajs** [comment]
Re-organize to static and dynamic @ruseinov @hanabi1224

**Comment by ruseinov** [comment]
> Re-organize to static and dynamic @ruseinov @hanabi1224

In the end it looks like we don't need to deal with dynamic manifest provider, @hanabi1224 double-checked this. So I have modified the issue to deal with the static config.

**Comment by LesnyRumcajs** [comment]
Pausing Rust-F3 development, will re-create issues as needed.
