### ISSUE TITLE
Support `eth_getBlockReceipts`

### ISSUE THREAD

**Issue by LesnyRumcajs** [ChainSafe/forest#4839]
# Summary

Another method is supported in Lotus, and so we should support it as well, eventually. See https://github.com/filecoin-project/lotus/issues/12429. The reference implementation is around 200 LoC.

# Completion Criteria

- [ ] Implement the method
- [ ] Add tests

# Additional Links & Resources

**Comment by elmattic** [comment]
Blocked by #4780

**Comment by LesnyRumcajs** [comment]
Unblocked!
