### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/forest#4847]
# Summary

Establish a basic CONTRIBUTING.md to provide direction for external contributors.

# Completion Criteria

- [ ] CONTRIBUTING.md with some instructions for how to contribute
- [ ] Issue(s) created for any additional material that should be added directly or via other sources (eg. developer docs)
- [ ] Add link to `Introduction` page of user docs

# Additional Links & Resources

Examples:
- https://github.com/ChainSafe/lodestar/blob/unstable/CONTRIBUTING.md
- (naive AI) https://www.phind.com/search?cache=qb9tm66uj8h7fvxz8n8qnltx
- https://gitlab.com/gitlab-org/gitlab/-/blob/master/CONTRIBUTING.md

**Comment by LesnyRumcajs** [comment]
We already have some! :rofl: https://github.com/ChainSafe/forest/blob/main/documentation/src/developer_documentation/contributing.md
