### ISSUE TITLE
F3 testing on butterflynet

### ISSUE THREAD

**Issue by hanabi1224** [ChainSafe/forest#4860]
# Summary

# Completion Criteria

- [ ] generate an f3(BLS) wallet for testing
- [x] run Forest on butterflynet with proper F3(Fast Finality) parameters on a DO droplet
- [ ] validate the correctness of F3 consensus

# Additional Links & Resources

**Comment by hanabi1224** [comment]
Notes on testing steps:

1. build forest(make install) on https://github.com/ChainSafe/forest/pull/4877 branch (or `main` once it's merged)
2. build F3 sidecar `cd f3-sidecar && go build -v .`
3. run forest with F3 sidecar
   a. run forest with built-in F3 sidecar 
       `FOREST_F3_SIDECAR_FFI_ENABLED="1" FOREST_F3_FINALITY="200" FOREST_F3_BOOTSTRAP_EPOCH="2760" forest --chain butterflynet --encrypt-keystore false`
   b. or run forest and F3 sidecar separately for easier log inspection
       `FOREST_F3_SIDECAR_FFI_ENABLED="0" forest --chain butterflynet --encrypt-keystore false`
       and
       `./f3-sidecar -bootstrap 2760 -finality 200 -root /tmp/f3/butterflynet`

**Comment by LesnyRumcajs** [comment]
@hanabi1224 do we consider this done?

**Comment by hanabi1224** [comment]
Yes
