### ISSUE TITLE
implement fund_mgr 

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/forest#490]
**Task summary**

Market integration requires the implementation of a fund manager to ensure available funds. Dependant on the #488 method in state_manager and the completion of #121. 

**Specification reference**

- [fund_mgr - Lotus](https://github.com/filecoin-project/lotus/blob/master/chain/market/fundmgr.go)

**Other information and links**

**Comment by austinabell** [comment]
Why is there a need to do this rn? it's possible this logic won't even lie within our codebase until we reimplement markets in rust

**Comment by dutterbutter** [comment]
I don't think there is a need to do this right now hence the low priority but wouldn't we need to implement this when we integrate with markets?

**Comment by austinabell** [comment]
Depends on how the markets are integrated, it's possible this lives outside of our node
