### ISSUE TITLE
chore: take care of debug log spam for api compare tests

### ISSUE THREAD

**Issue by ruseinov** [ChainSafe/forest#4989]
we have a lot of spam in our log dumps, mainly those two lines:
```  2024-11-16T07:10:25.675752Z DEBUG forest_filecoin::rpc::auth_layer: Decoded JWT Claims: read,write,sign,admin
  2024-11-16T07:10:25.675839Z DEBUG forest_filecoin::rpc::log_layer: RPC#19ed50 OK: F3.GetParent. Took 31.819µs
```

That makes it harder to see what's wrong with api compare tests. Creating an issue.

_Originally posted by @ruseinov in https://github.com/ChainSafe/forest/issues/4983#issuecomment-2485596993_

**Comment by kamuik16** [comment]
> ```
>           we have a lot of spam in our log dumps, mainly those two lines:
> ```
> 
> ```
>   2024-11-16T07:10:25.675839Z DEBUG forest_filecoin::rpc::log_layer: RPC#19ed50 OK: F3.GetParent. Took 31.819µs
> ```
> 
> That makes it harder to see what's wrong with api compare tests. Creating an issue.
> 
> _Originally posted by @ruseinov in [#4983 (comment)](https://github.com/ChainSafe/forest/pull/4983#issuecomment-2485596993)_

Hey, I am pretty new here and want to contribute. Looking at the code. It seems this happens here:
https://github.com/ChainSafe/forest/blob/48f0a4e28f96bd1cf7ce03576f3b9102bee7c101/src/rpc/log_layer.rs#L65
Do you want to remove it completely? I can open a PR for it.

**Comment by ruseinov** [comment]
> > ```
> >           we have a lot of spam in our log dumps, mainly those two lines:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >   2024-11-16T07:10:25.675839Z DEBUG forest_filecoin::rpc::log_layer: RPC#19ed50 OK: F3.GetParent. Took 31.819µs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That makes it harder to see what's wrong with api compare tests. Creating an issue.
> > _Originally posted by @ruseinov in [#4983 (comment)](https://github.com/ChainSafe/forest/pull/4983#issuecomment-2485596993)_
> 
> Hey, I am pretty new here and want to contribute. Looking at the code. It seems this happens here:
> 
> https://github.com/ChainSafe/forest/blob/48f0a4e28f96bd1cf7ce03576f3b9102bee7c101/src/rpc/log_layer.rs#L65
> 
> 
> Do you want to remove it completely? I can open a PR for it.

Hello Krishang! It's nice to see your interest, though we should discuss and prioritise this. 
I'm pretty sure that disabling this completely is not what we are looking for, but rather adjusting log levels for a particular endpoint/module for certain CI jobs.
