### ISSUE TITLE
Syncing Improvement: Concurrent processing of recieved blocks

### ISSUE THREAD

**Issue by ec2** [ChainSafe/forest#499]
When we get blocks over pubsub, we are only able to process one at a time. This is not good, since each epoch will have multiple blocks to form a tipset. So we need to make processing concurrent in order to stay in sync.

**Comment by amerameen** [comment]
You're working on this right now, right Eric?

**Comment by ec2** [comment]
Yup. But as I was doing it, realized we need to get Bitswap in, so im currently doing that right now
