### ISSUE TITLE
EthGetTransactionByBlockNumberAndIndex

### ISSUE THREAD

**Issue by elmattic** [ChainSafe/forest#5020]
# Summary

This method is now supported in Lotus v1.31.0, and so we should support it as well.

# Completion Criteria

- [ ] Implement method
- [ ] Add api compare tests

# Additional Links & Resources

https://github.com/filecoin-project/lotus/pull/12618

**Comment by LesnyRumcajs** [comment]
@elmattic Let's have more fleshed-out descriptions, at least one that makes it easier to reason about a year from now or so.
