### ISSUE TITLE
Port over Miner Actor Related Tests

### ISSUE THREAD

**Issue by RajarupanSampanthan** [ChainSafe/forest#504]
**Issue summary**

There are 4 tests related to the miner actor that test different parts of its functionality. 

These are the links to the implementations in Lotus : 
https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/deadlines_test.go
https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/miner_internal_test.go
https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/miner_state_test.go
https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/miner_test.go

**Other information and links**

**Comment by snaumov** [comment]
I'll work on this.

**Comment by austinabell** [comment]
I would hold off for a bit, there has been a huge refactor of this actor and I haven't gone through and updated yet, so the tests will be very hard to port over. #559

**Comment by snaumov** [comment]
I see. I'll stand by and work on something else meanwhile.

**Comment by amerameen** [comment]
On hold since the Conformance Vectors cover a lot of the relevant code. Will import the rest of the tests in the future.
