### ISSUE TITLE
PayChannel RPC methods

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#529]
**Task summary**

PayChannel methods should be exposed from the JSON-RPC server. The Paych methods are for interacting with and managing payment channels. The logic for most of these methods exists in `paychmgr.Manager`, and requires building out the `store` and `state` files in paychmgr as well. Keep in mind, there is likely going to be a refactor on the lotus code for this component. 

Methods include:

- [ ] PaychGet 

- [ ] PaychList

- [ ] PaychStatus

- [ ] PaychClose

- [ ] PaychAllocateLane

- [ ] PaychNewPayment

- [ ] PaychVoucherCheckValid

- [ ] PaychVoucherCheckSpendable

- [ ] PaychVoucherCreate

- [ ] PaychVoucherAdd

- [ ] PaychVoucherSubmit

**Comment by amerameen** [comment]
@dutterbutter will break this down to clarify scope (especially when it comes to scope of testing)

**Comment by LesnyRumcajs** [comment]
Stale
