### ISSUE TITLE
Exposing Blockstore thru RPC

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/forest#538]
**Task summary**

We will need to have the Blockstore accessible via RPC.

**Specification reference**

- 

**Other information and links**

**Comment by ec2** [comment]
Do you have an API definition for this somewhere? Or a reference?

**Comment by dutterbutter** [comment]
The API definition still needs to be defined.

**Comment by austinabell** [comment]
for context, it's needed to be able to access the store from the external go binary (unless you can come up with another way around this that's cleaner for usage in markets)

**Comment by dutterbutter** [comment]
Putting this task in the backlog, for now, go-fil-markets [latest release](https://github.com/filecoin-project/go-fil-markets/blob/release/v0.5.0/CHANGELOG.md) no longer assumes data lives in a shared blockstore, and they are likely going to move towards having a separate blockstore for each deal. These changes haven't been reflected in Lotus yet as they are still utilizing v0.4.1, but I think we should wait for that update.

**Comment by amerameen** [comment]
@dutterbutter is this still necessary? can we close this?

**Comment by dutterbutter** [comment]
I'd like to keep it open until we finalize market integration
