### ISSUE TITLE
State CLI Commands

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#541]
Implementing the State commands for our CLI client. 

Notes
We have to implement whatever we think is useful from the list below (likely 3 or more)

List of Commands:
power Query network or miner power
sectors Query the sector set of a miner
proving Query the proving set of a miner
pledge-collateral Get minimum miner pledge collateral
list-actors list all actors in the network
list-miners list all miners in the network
get-actor Print actor information
lookup Find corresponding ID address
replay Replay a particular message within a tipset
sector-size Look up miners sector size
read-state View a json representation of an actors state
list-messages list messages on chain matching given criteria
compute-state Perform state computations
call Invoke a method on an actor locally
get-deal View on-chain deal info
wait-msg Wait for a message to appear on chain
miner-info Retrieve miner information

**Comment by nannick** [comment]
Subcommands for State in  Lotus

COMMANDS:
     power              Query network or miner power
     sectors            Query the sector set of a miner
     proving            Query the proving set of a miner
     pledge-collateral  Get minimum miner pledge collateral
     list-actors        list all actors in the network
     list-miners        list all miners in the network
     get-actor          Print actor information
     lookup             Find corresponding ID address
     replay             Replay a particular message within a tipset
     sector-size        Look up miners sector size
     read-state         View a json representation of an actors state
     list-messages      list messages on chain matching given criteria
     compute-state      Perform state computations
     call               Invoke a method on an actor locally
     get-deal           View on-chain deal info
     wait-msg           Wait for a message to appear on chain
     miner-info         Retrieve miner information

**Comment by amerameen** [comment]
On hold for now, since we don't have HTTP support, and we are focused on interop. Will come back to this after interop.
