### ISSUE TITLE
Use released version of filecoin-proofs-api

### ISSUE THREAD

**Issue by vmx** [ChainSafe/forest#545]
**Describe the bug**

`cargo test` within the `ipld` directory currently fails. It's due to the `rust-filecoin-proofs-api` version specified in `commcid`. It's pined to a specific commit.

If you use a rleases version (e.g. `0.4`) it builds for me.

**To Reproduce**
1. `cd ipld`
2. `cargo test`.

**Expected behaviour**

`ipld` crate builds.

**Environment (please complete the following information):**
 - OS: Linux 
 - Rust version: 1.46.0-nightly (4f74d9b2a 2020-07-08
 - Branch/commit: HEAD

**Other information and links**

There are more crates using `filecoin-proofs-api`, that are pinned to that specific commit, hence there might be a reason why you don't use the released version, hence I didn't do a PR.

**Comment by austinabell** [comment]
Which branch are you on? We switched to using releases a while ago. I assume this is on master because I see that still references the commit that had a breaking patch added to it? If so, we switched our default branch to `main`

**Comment by vmx** [comment]
Thanks for the quick reply. I was indeed on `master`. Things build fine when on `main`.
