### ISSUE TITLE
Import Genesis CAR file and create corresponding state within Forest

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#574]
For the purpose of Genesis verification, we need to compare the state that the provided (Genesis) CAR file gives us, to what's expected. 

In order to do so, we import the CAR file before doing some checks on the resulting state. 

Currently we can import a CAR file to start a new chain and start syncing. This issue covers any architectural changes we need to allow us to do sanity checks against the Genesis State (rather than starting a new chain with the Genesis State and starting to sync)

**Comment by austinabell** [comment]
can you explain or reword this? By definition of this, it's already done

**Comment by amerameen** [comment]
Good point! Perhaps we don't need to modify it in any way. Let me explain more of what we need for Genesis Verification.  Assuming that we're already have what we need, we can close this.

**Comment by austinabell** [comment]
> ... This issue covers any architectural changes we need to allow us to do sanity checks against the Genesis State (rather than starting a new chain with the Genesis State and starting to sync)

That's a good enough reason to keep this issue! I don't think there will be any architectural changes necessary (should just need access to the store and the root given back to verify, but that's opinionated and I'm sure there could be changes for this to be done as cleanly as possible
