### ISSUE TITLE
Define format for Genesis File in JSON. Create GenesisTemplate type in Forest.

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#579]
https://github.com/filecoin-project/lotus/blob/9b1d2f4c137433c1fe1f5ed44ba2e70105a409f0/genesis/types.go#L64

**Comment by snaumov** [comment]
I needed this for #580, so I ended up adding the `GenesisTemplate` type in MR: https://github.com/ChainSafe/forest/pull/612.

**Comment by snaumov** [comment]
this can be closed

**Comment by nannick** [comment]
> this can be closed

We must've missed this in the Sprint planning. Thanks for the reminder!
