### ISSUE TITLE
Check for non-utf-8 characters when converting Addresses from string slices

### ISSUE THREAD

**Issue by neithanmo** [ChainSafe/forest#595]
**Issue summary**

A *panic* occurs when trying to convert an Address from a string slice with non-utf-8 characters, instead of returning an error, which would allow users to handle it gracefully. 
In the implementation of the *FromStr* trait for  Address in [vm/address/src/lib.rs](https://github.com/ChainSafe/forest/blob/main/vm/address/src/lib.rs#L158), there are three [places](https://github.com/ChainSafe/forest/blob/main/vm/address/src/lib.rs#L165) where the panics can happen as a result of sub-slicing by indexing a possible non-boundary character.

**Other information and links**

There is a function that helps with this in the standard [library](https://doc.rust-lang.org/beta/std/primitive.str.html#method.get).

**Comment by austinabell** [comment]
nah, the indexing can never fail because of the length checks right above, here https://github.com/ChainSafe/forest/blob/main/vm/address/src/lib.rs#L161 

As for handling Address from non utf8 characters, I don't see anything that would panic instead of returning an error, but I don't see any reasonable use of why this would need to support this. Using non utf8 bytes as a string in rust is unsafe and there _should_ be no reason to need it with the Filecoin protocol.

Can you give an example of when this can panic? I've even tried using non utf8 bytes and I can't get it to panic on anything

**Comment by neithanmo** [comment]
Yes, the indexing would not fail because of length, but this can panic when looking at the network and protocol identifiers even at the address payload.  for example, let's say we have this valid Filecoin address:

- ` let valid = "f1mk3zcefvlgpay4f32c5vmruk5gqig6dumc7pz6q";`

An attacker might send crafted transaction data with a malformed address field like:

- `let invalid = "fömk3zcefvlgpay4f32c5vmruk5gqig6dumc7pz6q";`

Notice the non-utf8 character `ö` in the string which can be created safely, check [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=f54fabff03e40ef1e838cf0e66869f46) for an example of what happens if we want to get a slice at such character, that in this case would correspond to address protocol. 

However, this won't panic if the "invalid" character is at a different place for example:

- `"f1mk3zcefvlgpay4f32c5vmruk5öqig6dumc7pz6q"`

[here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=3a6fc8ed2d31ae202ee9fdc5d6657c42) a link to the playground for this case

**Comment by austinabell** [comment]
Ah interesting, yes you are right about this. This isn't an attack vector for us because there is no way to get non-utf8 string to run against this, but I will fix this regardless so other use cases of this lib don't run into this issue.

Thanks, I'll fix this now :)

**Comment by neithanmo** [comment]
great!, I already fixed this locally on my branch but would be great having this in master. 

Thanks.

**Comment by austinabell** [comment]
> great!, I already fixed this locally on my branch but would be great having this in master.
> 
> Thanks.

Feel free to open a PR if you'd like! I'm just adding tests and checking all non-ascii permutations to be sure of things rn and then I will open one

**Comment by neithanmo** [comment]
sure!

**Comment by austinabell** [comment]
Thank you!
