### ISSUE TITLE
VM check_message is confusing Zero and EmptyInt

### ISSUE THREAD

**Issue by ec2** [ChainSafe/forest#596]
**Describe the bug**

In Lotus, when they do [CheckMessage](https://github.com/filecoin-project/lotus/blob/master/chain/vm/vm.go#L268), they check if Value and GasPrice are empty ints, not 0 as we are doing [here](https://github.com/ChainSafe/forest/blob/main/vm/interpreter/src/vm.rs#L416). 

It is most certainly the case that it is possible to send messages with Value = 0 (example [here](https://filfox.info/en/message/bafy2bzaceahhze5r6ceij7ctcxadje2miweqxzcuuamzup2k5bb423tyoopve?block=bafy2bzacebtfstfnqx7sc6phjxbdzin6vm4gvel5vcnnoqm6eegum3cj5bdra). 

So I wonder if we can skip that check? I'm not entirely sure what EmptyInt is in Lotus... Guessing its similar to some nil maybe?

**Comment by austinabell** [comment]
Ah yeah it is just a nil check in the go implementation. I missed fixing that in my pass because I didn't look into what that type was. Will update now, thanks :)
