### ISSUE TITLE
Inline CIDs for objects smaller than 64 bytes. 

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#613]
Using inline CIDs for objects smaller than 64 bytes. This means that for small objects in the state tree, we currently always hash them, and include their CID (~40 bytes) in the chain, with the actual object stored separately. This change would use identity multihashes to inline the object, saving us disk reads, and overall space, without much downside. 

PR on Lotus: https://github.com/filecoin-project/specs-actors/pull/783

**Comment by austinabell** [comment]
Currently this cannot be picked up and there will be more changes needed than the PR into specs-actors (as handling pulling data from a raw cid will need to be handled in the blockstore implementation(s)

**Comment by austinabell** [comment]
Not going into mainnet, and uncertain when and if this is coming in, so going to close
