### ISSUE TITLE
`verify_secp256k1_sig` use an invalid hash for signature

### ISSUE THREAD

**Issue by rllola** [ChainSafe/forest#725]
**Describe the bug**
`verify_secp256k1_sig` seems to use an invalid hash of the message in order to verify the signature. The hash is different than the one actually signed so the public key recover doesn't match the one in the `from` field.

**To Reproduce**
1. Get a signature from lotus
2. Verify signature using the function
3. See "Secp signature verification failed" error

**Other information and links**
You can see the difference between the digest used in our project and the one used in the forest verify function. https://github.com/Zondax/filecoin-signing-tools/pull/293/files#diff-46b5d15cb95e5866c7ed4a201c2fed7fR861

**Comment by austinabell** [comment]
Well, the diff here is that you're comparing a hash of a serialized message to a hash of the message Cid. Our function assumes you are passing in the blake 2b hash of the Cid. 

Let me look into this and add some tests and at least improve docs (reading the docs on the ecrecover seems outdated, as it does say a hash of the message)

**Comment by rllola** [comment]
Oh I think I see what you mean.

So the error actually show up when I am using the function `SignedMessage::new_from_parts` It verifies that the signature fits the message. I was trying to debug why. From what you are saying before `verify_secp256k1_sig` is being called we should get the CID of the unsigned message so it can be passed to `verify_secp256k1_sig`.

**Comment by austinabell** [comment]
Ah, yeah you're right. The `new_from_parts` function was doing incorrect validation. (I'm actually not sure why it's validating at all, that's not what this function is for)

I'll have a PR in very soon and will publish new versions of these crates. Sorry this interface and logic isn't really setup the best, it was something setup near the start of the project, and we only use a certain segment just for validation.

If you have an idea for an interface that will be useful for your wallet, please don't hesitate to suggest.
