### ISSUE TITLE
Allow snapshot to be loaded from an http request and add progress

### ISSUE THREAD

**Issue by austinabell** [ChainSafe/forest#762]
**Issue summary**

Once #761 is in, would be very nice to allow for loading a snapshot from a url, as Lotus does it. 

They also added in a progress bar for the snapshot import, and I think this would be a very nice UX to add. For this progress to show up well, it has to be before any of the async tasks are started, as the logger conflicts with the progress bar output (see `fetch-params` progress bar when requests are done async), but should be pretty straightforward

This issue is definitely low priority since it wouldn't add any new functionality.

**Other information and links**

**Comment by snaumov** [comment]
I can look into it this week :)

**Comment by ec2** [comment]
Just for more guidance, I made this PR for importing snapshots https://github.com/ChainSafe/forest/pull/789
