### ISSUE TITLE
Add Block Validation Check Methods

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/forest#78]
While these exact parameters are likely to change we can start to include some these checks and document those that aren't yet implementable.

Must meet the criteria outlined here:
- [Validation.md](https://github.com/filecoin-project/specs/blob/6ab401c0b92efb6420c6e198ec387cf56dc86057/validation.md)

In the spec:
- [Syntactical Validation](https://filecoin-project.github.io/specs/#block-syntax-validation)
- [Semantic Validation](https://filecoin-project.github.io/specs/#block-semantic-validation)

Reference from existing implementations:
- [Lotus Block Validations](https://github.com/filecoin-project/lotus/blob/master/chain/sync.go#L482)
- [Go-Filecoin Block Validations](https://github.com/filecoin-project/go-filecoin/blob/master/internal/pkg/consensus/block_validation.go)

**Tasks required to complete this task:**
- [ ] Block validation trait(s)
- [ ] Semantic validations
- [ ] Syntactic validations

**Comment by amerameen** [comment]
On Ice for now due to dependancies on VM and HAMT

**Comment by austinabell** [comment]
Some of this has been done, but should revisit to make sure we complete all or document what is missing, shouldn't be on ice for any reason I don't think

**Comment by amerameen** [comment]
@nannick please update the issue with what our implementation is missing.
