### ISSUE TITLE
Blocksync: Implement dynamic request length 

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#801]
**Issue summary**

Currently, for Blocksync, we're using a static request length (10) (the number of blocks requested at once). 

It would be better to have dynamic requests (i.e. make longer requests when we can successfully, or make shorter requests when they fail)

For example:  Lotus starts with 500 and if request fails, they shrink request size.

**Acceptance Criteria**
The Blocksync request lengths are dynamic and adjust (i.e. get bigger or smaller) based on what's feasible with current peers and network conditions.

**Comment by austinabell** [comment]
To clarify, Lotus has a default window size of 500, and they send the request to 16 peers before changing window size (used to be 5, so this should also change on our side, assuming there is a good reason for this).

**Comment by dutterbutter** [comment]
After discussing with @austinabell rather than having a dynamic window size as described above, I will be implementing a sync configuration that will sit within the `chainsyncer` where users can update the window size via command line as well as the number worker tasks related to syncing.
