### ISSUE TITLE
Add GetPaychState to State Manager

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#827]
**Issue summary**

In the State Manager, we need a function to return the state of the paychannel actor (GetPaychState)

[See the Lotus implementation](https://github.com/filecoin-project/lotus/blob/efd2dff0cac40934ec5b4472e48887ecbb2efe44/chain/stmgr/stmgr.go#L1158)

This is used by paychannel manager (state accessor and channel accessor) [here](https://github.com/filecoin-project/lotus/blob/efd2dff0cac40934ec5b4472e48887ecbb2efe44/paychmgr/paych.go#L340) & [here](https://github.com/filecoin-project/lotus/blob/efd2dff0cac40934ec5b4472e48887ecbb2efe44/paychmgr/state.go#L16)

**Comment by LesnyRumcajs** [comment]
stale.
