### ISSUE TITLE
Add GetMarketState to State Manager

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#828]
**Issue summary**
In [State Manager](https://github.com/ChainSafe/forest/blob/main/blockchain/state_manager/src/lib.rs), implement a function to return the state of the Market Actor. 

[See Lotus implementation here](https://github.com/filecoin-project/lotus/blob/efd2dff0cac40934ec5b4472e48887ecbb2efe44/chain/stmgr/stmgr.go#L1176)

**Other information and links**

- Used for State API methods: [StateMarketDeals](https://github.com/filecoin-project/lotus/blob/efd2dff0cac40934ec5b4472e48887ecbb2efe44/node/impl/full/state.go#L573), [StateMarketParticipants](https://github.com/filecoin-project/lotus/blob/efd2dff0cac40934ec5b4472e48887ecbb2efe44/node/impl/full/state.go#L533).

**Comment by austinabell** [comment]
Unclear whether this will be needed, it's used for `StateMarketParticipants` and `StateMarketDeals` but we don't have those yet, no point implementing until we decide we need
