### ISSUE TITLE
Add GetNtwkVersion to State Manager

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#830]
**Issue summary**

Implement a function to get network version based on the epoch in the State Manager. 

[See Lotus implementation](https://github.com/filecoin-project/lotus/blob/efd2dff0cac40934ec5b4472e48887ecbb2efe44/chain/stmgr/stmgr.go#L1140)

[We have this implemented in Forest already](https://github.com/ChainSafe/forest/blob/0b7a49b6ac3879ecea953c487218a994a91c14f7/types/src/version.rs#L66)

**Other information and links**

**Comment by AshantiMutinta** [comment]
This is going to be in my PR
