### ISSUE TITLE
Fix CodeCov

### ISSUE THREAD

**Issue by austinabell** [ChainSafe/forest#846]
**Describe the bug**

- Reporting inaccurate coverage (~3.8%) when coverage should be ~55% (running locally)
Also, if possible, if we can remove the codecov from our CI checks that would be ideal. Also, the badge could be fixed so it doesn't show unknown

**Other information and links**

**Comment by vmx** [comment]
I currently work on code coverage reporting for rust-fil-proofs. So I'll probably run into the same issue and will try to find a fix. So if this isn't urgent, feel free to wait and I'll report back.

**Comment by dutterbutter** [comment]
For background info, the ~55% reported locally uses html as the coverage report whereas codecov coverage is using lcov INFO format. The HTML report hits ~14722 of 24630 lines (resulting in ~55% coverage), whereas codecov is reporting only ~~1,133 hits of 29,225 lines (resulting in ~3.xx%). Even if you include partially hit lines reported in codecov it still does not come close to the locally reported coverage.
