### ISSUE TITLE
Finish Getting RPC Fixes In

### ISSUE THREAD

**Issue by AshantiMutinta** [ChainSafe/forest#864]
**Task summary**

At the moment there is a uncompleted task of some rpc implementations and fixes. The state of that branch allows configuration of the storage miner before attempting to mine. Addressing the concerns in the review would be a way to start

**Specification reference**

- 

**Other information and links**

#841

**Comment by austinabell** [comment]
I'm confused, is there any added scope to this? or this issue is just saying "get PR in"?

**Comment by AshantiMutinta** [comment]
It's just completing whatever is left. I'm not doing a full day so not able to get it in
