### ISSUE TITLE
Optimize forming tipsets

### ISSUE THREAD

**Issue by timvermeulen** [ChainSafe/forest#878]
`TipsetTracker` could be improved in a few ways:

* `TipsetTracker::add` holds the write handle of the `RwLock` for the entire duration of the function call, including blockstore reads.
  * Consider cloning the `Vec<Cid>` in order to release the lock before reading from the blockstore, and acquire it again at the end to add the new block to the hash map.
  * Consider not doing any blockstore reads at all by storing each block's miner address inside the `TipsetTracker`.

* `TipsetTracker::expand`, similarly, holds the read handle of the `RwLock` during blockstore reads.
  * Consider cloning the `Vec<Cid>` like in `TipsetTracker::add`.
  * Consider caching the parent `TipsetKeys` internally, similar to `TipsetTracker::add`.
  * Consider combining `add` and `expand`  into a single function that adds all blocks of the tipset to the tracker, and expands the tipset by adding existing blocks to it that qualify.

**Comment by amerameen** [comment]
Reducing priority since this would be a small performance improvement.
