### ISSUE TITLE
Fix actors non-determinism issue

### ISSUE THREAD

**Issue by austinabell** [ChainSafe/forest#904]
**Issue summary**

Reflective of:
https://github.com/filecoin-project/specs-actors/pull/1334

Which changes the sorting based on network version 9 changes

Also with this issue, consensus fault reporting should be disabled around the Orange upgrade height inside of `verify_consensus_fault`

**Other information and links**

**Comment by austinabell** [comment]
Looking more in depth with this, it doesn't seem to be possible to match their behaviour.

The issue is just matching pre-version 9 actually, since before then they do not sort the deadlines and instead return the array in order of the golang map iteration order (not something that can be replicated afaik yet). 

There is no change needed to be compliant with the fork, but for now it seems as if we won't be able to sync with pre version 9 network (depending on when the ordering differs).

Going to keep the issue open for now for discussion, until we decide how to move forward with this

**Comment by amerameen** [comment]
Closing this because we can't match before version 9.
