### ISSUE TITLE
Enable Gossipsub after initial sync

### ISSUE THREAD

**Issue by ec2** [ChainSafe/forest#913]
** Acceptance Criteria **
Gossipsub is only enabled when the Syncing State is set to Follow (thus disable otherwise).

**Issue summary**

We receive and discard gossipsub messages during initial sync which wastes bandwidth. We should enable gossipsub or subscribe to relevant topics after we've sufficiently caught up to head. 

**Other information and links**

**Comment by amerameen** [comment]
Closing this issue, because we should keep gossipsub enabled because it will allow us to keep track of our peers (and their current heads) during syncing.
