### ISSUE TITLE
Crates.io binary

### ISSUE THREAD

**Issue by cryptoquick** [ChainSafe/forest#956]
**Issue summary**
It'd be really convenient to install this binary via `cargo install`.

**Other information and links**
When you'd go to publish on Crates, you'll notice there's someone squatting [`forest`](https://crates.io/crates/forest)

However, I'd recommend just going for the gold here. Nobody's had the bravery to publish a `filecoin` Rust binary just yet. So. The question you should ask yourselves... Are you thinking of cutting an actual release yet?

**Comment by austinabell** [comment]
Great question, this is definitely a plan, but we will go through the process of releasing all subcrates when we are maintaining interop and things stabilized, not worth the time sink yet.

**Comment by cryptoquick** [comment]
I think the concrete need is simply from a user perspective. It's also not too difficult, unless you haven't published to Crates yet. For some reason, the Crates publish process is a lot more rigorous, so sometimes things pop up on a dry run. What's harder is when someone else squats the crate, which is my primary concern. If you want to publish under `forest`, then you'll have to deal with Crate-squatting, which, I'm not sure if there's a good solution to that yet. If you're fine with `filecoin`, you don't have to worry about squatting... Yet.

**Comment by austinabell** [comment]
> I think the concrete need is simply from a user perspective. It's also not too difficult, unless you haven't published to Crates yet. For some reason, the Crates publish process is a lot more rigorous, so sometimes things pop up on a dry run. What's harder is when someone else squats the crate, which is my primary concern. If you want to publish under `forest`, then you'll have to deal with Crate-squatting, which, I'm not sure if there's a good solution to that yet. If you're fine with `filecoin`, you don't have to worry about squatting... Yet.

No I agree this is ideal to have, but the issue is releasing and maintaining versions is a bit premature, as we are still a week or two away from maintaining interop and having and usable client. As I mentioned, we have a lot of the core crates released, but it's not worth the maintenance yet, especially with things that are changing in the Filecoin protocol

**Comment by cryptoquick** [comment]
Gotcha, I don't have a good sense for the project timeline. Nonetheless, a worthwhile feature to keep around.

There's also two somewhat orthogonal matters here. I haven't looked, but I'm assuming you have a HTTP JSON-RPC API that you want to make available. However, I think it might be a good idea to distribute a sort of `filecoin_embed`, in addition to, say, `filecoin_http` and a CLI binary, simply, `filecoin`. It's good to have many use-cases covered in a tool like this. It's a huge selling point for the project.

**Comment by lemmih** [comment]
Done!
