### ISSUE TITLE
Dependency on Crate "bs58" sets Minimum Rust Version to > 1.46

### ISSUE THREAD

**Issue by bodo-hugo-barwich** [ChainSafe/forest#992]
**Issue summary**

I'm trying to compile the project on Debian Buster with Default _Rust_ Compiler `1.41.1`
```
$ uname -a
Linux <hostname> 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
$ rustc --version
rustc 1.41.1
```

This fails at the Crate `bs58` with Error `E0658`:
```
$ cargo build
[...]
   Compiling bs58 v0.4.0
error[E0658]: `while` is not allowed in a `const fn`
   --> /path/to/home/.cargo/registry/src/github.com-1ecc6299db9ec823/bs58-0.4.0/src/alphabet.rs:107:9
    |
107 | /         while i < encode.len() {
108 | |             if base[i] >= 128 {
109 | |                 return Err(Error::NonAsciiCharacter { index: i });
110 | |             }
...   |
120 | |             i += 1;
121 | |         }
    | |_________^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/52000
```
The GitHub Reference takes me to the Pull Request
[Milestone 1.46 Pull Request](https://github.com/rust-lang/rust/pull/72437)

So, I understand this Error as the Crate `bs58` requires at least `rustc 1.46` to compile which only was released in August 2020.

The Project Documentation states that it only requires `rustc 1.40` to compile. So, it should compile with the Default Debian _Rust_ Compiler.

(I found most _Ubuntu_ Distributions ship already _Rust_ 1.47 but _Debian Buster_ still ships the older version.)

**Other information and links**

```
$ rustc --explain E0658|more
An unstable feature was used.

Erroneous code example:

"
#[repr(u128)] // error: use of unstable library feature 'repr128'
enum Foo {
    Bar(u64),
}
"

If you're using a stable or a beta version of rustc, you won't be able to use
any unstable features. In order to do so, please switch to a nightly version of
rustc (by using rustup).

If you're using a nightly version of rustc, just add the corresponding feature
to be able to use it:

"
#![feature(repr128)]

#[repr(u128)] // ok!
enum Foo {
    Bar(u64),
}
"
```
The GitHub Reference takes me to the Pull Request
[Milestone 1.46 Pull Request](https://github.com/rust-lang/rust/pull/72437)

Debian Buster Default _Rust_ Compiler
[Debian Buster _Rust_ Package](https://packages.debian.org/buster/rustc)

**Comment by bodo-hugo-barwich** [comment]
This issue is reproducable with the GitHub Workflow Container Facilities
[GitHub Workflow Debian Container](https://github.com/bodo-hugo-barwich/forest/pull/1/checks?check_run_id=1849684313)
```
Operating System:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Rust Compiler Version:
rustc 1.41.1
```

**Comment by austinabell** [comment]
Ah yes, thanks for pointing this out. The minimum version hasn't been updated in a while. This should be made sure to not happen with adding a msrv check in the CI. I'll try to find some time to do that soon (or now)

**Comment by austinabell** [comment]
Going to close for now because we do not have control over this msrv requirement and I've updated the `README.md` to reflect the requirement and made the change to the CI to make sure this doesn't happen again.

Feel free to open if you feel there is something else we can do. Thanks!

**Comment by bodo-hugo-barwich** [comment]
I was studying if newer _Debian Bullseye_ `rustc` compiler library packages are installable on _Debian Buster_. This would produce a nice **predictable and reproducible Build Environment**.

Unfortunately the tight dependency of the _Rust Standard Library_ on the systems `libc` library version makes them uninstallable.
As seen in this test:
[`rustc` from _Debian Bullseye_](https://github.com/bodo-hugo-barwich/forest/pull/1/checks?check_run_id=1982347092)
```text
libstd-rust-1.48:amd64 depends on libc6 (>= 2.29); however:
  Version of libc6:amd64 on system is 2.28-10.
```
Actually this a known limitation that precompiled _Rust_ binaries are not backwards compatible and thus not portable.
