### ISSUE TITLE
JSON-RPC v2 thread-safe error message serialization 

### ISSUE THREAD

**Issue by amerameen** [ChainSafe/forest#995]
**ACs**
- [ ] Fix the issue with sending JSON-RPC v2 error messages across threads in the Tide Websocket connection handler

**Notes**
- The issue is serializing dynamic data within JSON-RPC v2 which makes it difficult to send across threads. 
- Blocking #986

**Comment by cryptoquick** [comment]
We were able to sort of solve for this, but we would still need the forked crate, and we're having enough issues with using jsonrpc-v2, it might just be time to use a better crate. I've made #1006 to encapsulate that effort.
